google/gvisor

pkg/sentry/fs/inode_overlay.go
Simplify overlayBoundEndpoint.
=> Simplify overlayBoundEndpoint.

kokoro/common.cfg, kokoro/run_tests.sh
Switch to new dedicated RBE project.
=> Switch to new dedicated RBE project.

runsc/boot/loader.go
=> Remove spurious period

.bazelrc
Update straggling copyright holder
=> Update straggling copyright holder

runsc/boot/controller.go, runsc/boot/fds.go, runsc/boot/fs.go, runsc/boot/loader.go, runsc/boot/loader_test.go
=> Refactor container FS setup

pkg/sentry/fs/file.go
gvisor/fs: return a proper error from FileWriter.Write in case of a short-write
=> gvisor/fs: return a proper error from FileWriter.Write in case of a short-write

pkg/abi/linux/socket.go, pkg/sentry/fs/gofer/socket.go, pkg/sentry/fs/host/socket.go, pkg/sentry/socket/epsocket/BUILD, pkg/sentry/socket/epsocket/epsocket.go, pkg/sentry/socket/epsocket/provider.go, pkg/sentry/socket/hostinet/BUILD, pkg/sentry/socket/hostinet/socket.go, pkg/sentry/socket/netlink/provider.go, pkg/sentry/socket/rpcinet/BUILD, pkg/sentry/socket/rpcinet/socket.go, pkg/sentry/socket/socket.go, pkg/sentry/socket/unix/transport/connectioned.go, pkg/sentry/socket/unix/transport/connectionless.go, pkg/sentry/socket/unix/transport/unix.go, pkg/sentry/socket/unix/unix.go, pkg/sentry/strace/socket.go, pkg/sentry/syscalls/linux/sys_socket.go
Use common definition of SockType.
=> Use common definition of SockType.

pkg/sentry/fs/proc/task.go, test/syscalls/linux/proc.cc
There will be a deadloop when we use getdents to read /proc/{pid}/task
of an exited process
Like this:
Process A is running
Process B: open /proc/{pid of A}/task
Process A exits
Process B: getdents /proc/{pid of A}/task
Then, process B will fall into deadloop, and return "." and ".."
in loops and never ends.
This patch returns ENOENT when use getdents to read /proc/{pid}/task
if the process is just exited.
Signed-off-by: chris.zn <chris.zn@antfin.com>
=> Return ENOENT when reading /proc/{pid}/task of an exited process

pkg/sentry/fs/dev/BUILD, pkg/sentry/fs/dev/dev.go, pkg/sentry/fs/dev/tty.go, test/syscalls/linux/dev.cc
Actual implementation to follow, but this will satisfy applications that want it to just exist.
=> Stub /dev/tty

pkg/sentry/arch/arch.go, pkg/sentry/loader/elf.go
=> Add ARM64 support to pkg/sentry/loader

pkg/sentry/syscalls/linux/sys_epoll.go
Allocate a larger memory buffer and combine multiple copies into one copy,
to reduce the number of copies from kernel memory to user memory.
Signed-off-by: Hang Su <darcy.sh@antfin.com>
=> Combine multiple epoll events copies

pkg/refs/refcounter.go, runsc/boot/config.go, runsc/boot/loader.go, runsc/main.go
=> Add option to configure reference leak checking

scripts/build.sh
This should correct the continuous build.
=> Fix build when no tags are present

pkg/sentry/hostcpu/BUILD, pkg/sentry/hostcpu/getcpu_arm64.s
Signed-off-by: Haibo Xu haibo.xu@arm.com
Change-Id: I333872da9bdf56ddfa8ab2f034dfc1f36a7d3132
=> Enable pkg/sentry/hostcpu support on arm64.

pkg/sentry/fs/host/tty.go
How to reproduce:
$ echo "timeout 10 ls" > foo.sh
$ chmod +x foo.sh
$ ./foo.sh
(will hang here for 10 secs, and the output of ls does not show)
When "ls" process writes to stdout, it receives SIGTTOU signal, and
hangs there. Until "timeout" process timeouts, and kills "ls" process.
The expected result is: "ls" writes its output into tty, and terminates
immdedately, then "timeout" process receives SIGCHLD and terminates.
The reason for this failure is that we missed the check for TOSTOP (if
set, background processes will receive the SIGTTOU signal when they do
write).
We use drivers/tty/n_tty.c:n_tty_write() as a reference.
Fixes: #862
Reported-by: chris.zn <chris.zn@antfin.com>
Signed-off-by: chenglang.hy <chenglang.hy@antfin.com>
=> tty: fix sending SIGTTOU on tty write

pkg/sentry/fs/proc/net.go, test/syscalls/linux/ip_socket_test_util.cc, test/syscalls/linux/ip_socket_test_util.h, test/syscalls/linux/proc_net_tcp.cc
Fixes: #829
Signed-off-by: Jielong Zhou <jielong.zjl@antfin.com>
=> Implement /proc/net/tcp6

pkg/sleep/BUILD, pkg/sleep/commit_arm64.s, pkg/sleep/commit_noasm.go
Change-Id: I9071e698c1f222e0fdf3b567ec4cbd97f0a8dde9
=> Enable pkg/sleep support on arm64.

pkg/atomicbitops/BUILD, pkg/atomicbitops/atomic_bitops.go, pkg/atomicbitops/atomic_bitops_arm64.s, pkg/atomicbitops/atomic_bitops_common.go
Change-Id: I1646aaa6f07b5ec31c39c318b70f48693fe59a7c
=> Enable pkg/atomicbitops support on arm64.

runsc/container/container.go, runsc/specutils/BUILD, runsc/specutils/cri.go, runsc/specutils/specutils.go
Obligatory https://xkcd.com/927
Fixes #626
=> Add runsc OCI annotations to support CRI-O

runsc/boot/controller.go
=> remove duplicated period

runsc/boot/BUILD, runsc/boot/compat.go, runsc/boot/compat_arm64.go, runsc/boot/compat_test.go
Change-Id: I3fd5e552f5f03b5144ed52647f75af3b8253b1d6
=> Enable runsc compatLog support on arm64.

pkg/sentry/platform/kvm/testutil/testutil_arm64.s
=> Add a floating test case for Arm64

pkg/sentry/platform/kvm/BUILD, pkg/sentry/platform/kvm/physical_map.go, pkg/sentry/platform/kvm/physical_map_amd64.go, pkg/sentry/platform/kvm/physical_map_arm64.go
=> Optimize kvm/physical_map.go on Arm platform

pkg/tcpip/transport/tcp/endpoint.go, pkg/tcpip/transport/tcp/rcv.go, pkg/tcpip/transport/tcp/tcp_test.go
This is on top of https://github.com/google/gvisor/pull/1494
=> Fix 1522 silly window rx

pkg/sentry/syscalls/linux/sys_utsname.go
Change-Id: I206f38416a64d7c6a8531d8eb305c6ea239616b8
=> Enable uname syscall support on arm64.

test/syscalls/linux/BUILD, test/syscalls/linux/bad.cc, test/syscalls/linux/chroot.cc, test/syscalls/linux/fork.cc, test/syscalls/linux/getdents.cc, test/syscalls/linux/preadv2.cc, test/syscalls/linux/proc.cc, test/syscalls/linux/pwritev2.cc, test/syscalls/linux/seccomp.cc, test/syscalls/linux/stat.cc, test/util/signal_util.h, test/util/test_util.cc
Change-Id: I277d6c708bbf5c3edd7c3568941cfd01dc122e17
=> Enable build of test/syscall tests on arm64.

pkg/abi/linux/netfilter.go, pkg/sentry/socket/netfilter/BUILD, pkg/sentry/socket/netfilter/netfilter.go, pkg/sentry/socket/netfilter/targets.go, pkg/tcpip/iptables/iptables.go, pkg/tcpip/iptables/targets.go, pkg/tcpip/iptables/types.go, test/iptables/filter_input.go, test/iptables/iptables_test.go, test/iptables/iptables_util.go
Support jump in iptables. For example:
$ iptables -N foochain
$ iptables -A INPUT -j foochain
=> iptables: jump

.travis.yml, Dockerfile, Makefile, test/syscalls/linux/32bit.cc, test/syscalls/linux/rseq/uapi.h, test/syscalls/linux/udp_socket_test_cases.cc
@lubinszARM @xiaobo55x, could you review this patch?
=> arm64: add a travis build ci

pkg/sentry/arch/arch_aarch64.go
Fixes #1708
Signed-off-by: Haibo Xu haibo.xu@arm.com
Change-Id: Ib15768692ead17c81c06f7666ca3f0a14064c3a0
=> Add definition of arch.ARMTrapFlag.

pkg/sentry/platform/ring0/pagetables/BUILD, pkg/sentry/platform/ring0/pagetables/pcids.go
@lubinszARM @xiaobo55x, could you review this patch?
=> pcids.go isn't arch-specific

test/syscalls/linux/bad.cc, test/syscalls/linux/seccomp.cc
=> code clean: minor changes to compatible with ubuntu18.04

test/syscalls/linux/time.cc, test/syscalls/linux/vsyscall.cc
=> skip vsyscall test cases on Arm64

pkg/sentry/platform/kvm/bluepill_arm64.s, pkg/sentry/platform/kvm/bluepill_arm64_unsafe.go, pkg/sentry/platform/ring0/aarch64.go
Change-Id: I9e1bf2513c23bdd8c387e5b3c874c6ad3ca9aab0
=> Enable bluepill dieTrampoline operation on arm64.

pkg/sentry/platform/kvm/kvm.go, pkg/sentry/platform/kvm/kvm_amd64.go, pkg/sentry/platform/kvm/kvm_arm64.go
Change-Id: Iefbdf53e8e8d6d23ae75d8a2ff0d2a6e71f414d8
=> Code Clean: Move arch independent codes to common file in kvm pkg.

test/syscalls/linux/seccomp.cc
Change-Id: Ibc926c917d98b31fc92bbf8d82d6818c39b0f93c
=> Enable syscall seccomp test on arm64.

pkg/sentry/platform/ring0/entry_arm64.s
Mainly job was finished in this patch:
Switch gVisor sentry from host_user mode into guest_kernel mode:
a, load the context into guest:
R0-R17, R19-R30, pc, pstate, sp_el1 
Notice:
The stack pointer is very sensitive, it should be same as the stack pointer in host.
PS:
3 stacks were used in guest:
1 is captured by sigaction, it will be used in guest_kernel mode.
1 for container application, it will be used in guest_user mode.
And the last one is for temporary usage, it will be used in guest_kernel mode.
=> Prepare the vcpu environment for sentry on Arm64

test/syscalls/linux/BUILD, test/syscalls/linux/sysret.cc
Fixes #2058
Change-Id: I05750d238a6425d3a47fae15720901f4dd924a32
=> Enable syscall sysret_test on arm64.

test/syscalls/linux/getrandom.cc, test/syscalls/linux/lseek.cc, test/syscalls/linux/mlock.cc, test/syscalls/linux/mmap.cc
Change-Id: I8008c0375fc7e23225a21026f359e78e691729e5
=> Cleanup for syscall tests on arm64.

test/syscalls/linux/fork.cc
Change-Id: I033692bcf4f8139df29e369a12b150d10fccbe32
=> Enable syscall fork_test on arm64.

pkg/sentry/arch/arch.go, pkg/sentry/arch/syscalls_amd64.go, pkg/sentry/arch/syscalls_arm64.go, pkg/sentry/kernel/task_syscall.go, test/syscalls/linux/ptrace.cc
Change-Id: I5bb8fa7d580d173b1438d6465e1adb442216c8fa
=> Enable syscall ptrace test on arm64.

runsc/boot/loader.go
Suppose I start a runsc container using kvm platform like this:
$ sudo runsc --debug=true --debug-log=1.txt --platform=kvm run rootbash
The donating FD and the corresponding cmdline for runsc-sandbox is:
D0313 17:50:12.608203   44389 x:0] Donating FD 3: "1.txt"
D0313 17:50:12.608214   44389 x:0] Donating FD 4: "control_server_socket"
D0313 17:50:12.608224   44389 x:0] Donating FD 5: "|0"
D0313 17:50:12.608229   44389 x:0] Donating FD 6: "/home/ziqian.lzq/bundle/bash/runsc/config.json"
D0313 17:50:12.608234   44389 x:0] Donating FD 7: "|1"
D0313 17:50:12.608238   44389 x:0] Donating FD 8: "sandbox IO FD"
D0313 17:50:12.608242   44389 x:0] Donating FD 9: "/dev/kvm"
D0313 17:50:12.608246   44389 x:0] Donating FD 10: "/dev/stdin"
D0313 17:50:12.608249   44389 x:0] Donating FD 11: …
=> checkpoint/restore: make sure the donated stdioFDs have the same value

pkg/sentry/arch/signal_arm64.go, pkg/sentry/kernel/task_signals.go
x86-64 should always use SA_RESTORER, but SA_RESTORER is optional on other platforms.
So, we need to do special treatment for restorer.
For Arm64 platform, if SA_RESTORER is not configured, we can use the sigreturn trampolines
the vdso provides instead.
=> Arm64 signal#3: signal support in arch module

pkg/tcpip/network/ipv4/BUILD, pkg/tcpip/network/ipv4/ipv4_test.go
Based on ipv6's TestReceiveIPv6Fragments.
=> Add basic incoming ipv4 fragment tests

pkg/sentry/arch/signal_arm64.go
=> Add fpsimd support in sigreturn on Arm64

pkg/sentry/socket/netfilter/netfilter.go
We weren't properly checking whether the inserted default rule was
unconditional.
=> iptables: check for truly unconditional rules

pkg/goid/BUILD, pkg/goid/goid_arm64.s
Adding a method to get g on Arm64
=> add arm64 support to goid

g3doc/user_guide/tutorials/docker.md
=> Fix typo in Wordpress tutorial page

README.md
Small patch to fix a broken link to GOVERNANCE.md in the README :)
=> README: fix link to GOVERNANCE document

.github/workflows/go.yml, tools/go_branch.sh
=> Normalize permissions in the go branch.

tools/bazel.mk
The --groups command will fail if the group is not defined in
/etc/groups, even though it is specified by GID.
By coincidence, the group happens to be there for many installations of
Ubuntu 18.04 (which uses 999 for the Docker group), but it is strangely
absent in others (which use 130).
Fixes #2765
=> Ensure docker group exists in the container.

runsc/cmd/spec.go
This adds the `cwd` option to the `run spec` command, as asked in #2554.
Since this option is simple and straightforward, I only added a simple formatting rule when retrieving the spec template. I do realize this is not "maintainable" as we add more options, so there are some points that I'd like to raise:
1. I didn't see a lot of tests for cmd files, should I add one for the spec file? If so, any kind of template or good practices I should follow?
2. Other options asked in #2554 are a little more complex since the difference between the default and specified options aren't trivial. I was thinking of creating a full struct specification for OCI configuration files (following [this](https://github.com/opencontainers/runtime-spec/blob/master/config.md)). Any opinions on that matter?
---
``` …
```
=> Add cwd option to spec cmd

test/syscalls/linux/exec_binary.cc
=> minor changes in exec_binary test case for Arm64

pkg/sentry/platform/kvm/machine_arm64.go
=> minor change in kvm module for Arm64

g3doc/README.md
Small typo fix in the README.md
=> README.md: Commpatibility > Compatibility

runsc/container/container.go
Much like the boot process, apply pdeathsig to the gofer for cases where
the sandbox lifecycle is attached to the parent (runsc run/do).
This isn't strictly necessary, as the gofer normally exits once the
sentry disappears, but this makes that extra reliable.
=> Apply pdeathsig to gofer for runsc run/do

pkg/sentry/fsimpl/fuse/BUILD, pkg/sentry/fsimpl/fuse/dev.go, pkg/sentry/fsimpl/fuse/fusefs.go, pkg/sentry/syscalls/linux/vfs2/mount.go, pkg/sentry/vfs/options.go, runsc/boot/vfs.go, test/syscalls/linux/dev.cc, test/syscalls/linux/mount.cc
This change adds some of the foundation of the fuse filesystem.
The filesystem can now be mounted as well.
=> Stub FUSE filesystem implementation

pkg/sentry/platform/kvm/kvm_arm64_unsafe.go, pkg/sentry/platform/kvm/machine_arm64_unsafe.go
Support the operation of asid, so that I can optimize tlb performance
by combining with nG in pagetable.
=> add asid support to Arm64

pkg/test/dockerutil/container.go, test/iptables/BUILD, test/iptables/filter_input.go, test/iptables/filter_output.go, test/iptables/iptables.go, test/iptables/iptables_test.go, test/iptables/iptables_util.go, test/iptables/nat.go, test/iptables/runner/main.go
We skip gVisor tests for now, as ip6tables aren't yet implemented.
=> ip6tables testing

pkg/sentry/platform/kvm/testutil/testutil_arm64.go, pkg/sentry/platform/kvm/testutil/testutil_arm64.s
=> add usr-tls test cases for Arm64

runsc/boot/loader.go
Currently the stdio FDs are not dupped and will be closed
unexpectedly in VFS2 when starting a child container. This
patch fixes this issue.
Fixes: #3821
=> Dup stdio FDs for VFS2 when starting a child container

pkg/sentry/fsimpl/proc/task_fds.go, test/syscalls/linux/proc.cc
Currently the returned offset is an index, and we can't
compare it with file descriptors. Instead, we can return
the next fd to serialize plus 2 (which accounts for "."
and "..") as the offset.
Fixes: #3894
=> Fix proc.(*fdDir).IterDirents for VFS2

pkg/sentry/fs/g3doc/fuse.md
=> fuse: update design doc with I/O implementation

pkg/sentry/fs/proc/BUILD, pkg/sentry/fs/proc/sys_net.go, pkg/sentry/fs/proc/sys_net_state.go, pkg/sentry/fs/proc/sys_net_test.go, pkg/sentry/inet/BUILD, pkg/sentry/inet/inet.go, pkg/sentry/inet/test_stack.go, pkg/sentry/socket/hostinet/BUILD, pkg/sentry/socket/hostinet/stack.go, pkg/sentry/socket/netstack/stack.go, pkg/sentry/socket/rpcinet/stack.go, pkg/tcpip/buffer/BUILD, pkg/tcpip/buffer/prependable.go, pkg/tcpip/buffer/prependable_test.go, pkg/tcpip/network/ipv4/ipv4.go, pkg/tcpip/stack/nic.go, pkg/tcpip/stack/stack.go, pkg/tcpip/stack/stack_test.go, pkg/tcpip/stack/transport_test.go, test/syscalls/linux/proc_net.cc
I’ve played with gvisor and found a couple of easy to implement TODOs. 
Is it ok to go this way?
=> Add /proc/sys/net/ipv4/ip_forward

g3doc/architecture_guide/resources.md
2 typos spotted and fixed
Best
Didier
=> Fix 2 typos in resources.md

g3doc/architecture_guide/performance.md
2 typos spotted in current version and fixed.
Best
Didier
=> Fix a couple of typos on performance.md

pkg/sentry/platform/kvm/kvm_const_arm64.go, pkg/sentry/platform/ring0/entry_arm64.s, pkg/sentry/platform/ring0/pagetables/pagetables_aarch64.go
=> arm64: fix some issue for arm64

pkg/tcpip/transport/udp/forwarder.go
=> Assign ep.effectiveNetProtos in UDP forwarder's CreateEndpoint

pkg/sentry/platform/ring0/pagetables/pagetables_arm64.go
The ASID offset in TTBR_ELx register is 48
=> arm64: the ASID offset of TTBR register is 48

pkg/sentry/platform/ring0/kernel_arm64.go, pkg/sentry/platform/ring0/lib_arm64.go
=> ARM64: follow nogo rules add function description

tools/checkescape/checkescape.go
Signed-off-by: Lai Jiangshan <laijs@linux.alibaba.com>
=> typo: change whicy to which

pkg/sentry/platform/kvm/machine_arm64_unsafe.go, pkg/sentry/platform/ring0/aarch64.go, pkg/sentry/platform/ring0/entry_arm64.s, pkg/sentry/platform/ring0/offsets_arm64.go
Add more comments and more handling for exceptions.
=> arm64 kvm: add more handling of el0_exceptions

pkg/tcpip/network/arp/arp_test.go, pkg/tcpip/stack/neighbor_cache_test.go, pkg/tcpip/stack/neighbor_entry_test.go
=> Rewrite diff check to match example in cmp.Diff docs

g3doc/user_guide/containerd/quick_start.md
https://gvisor.dev/docs/user_guide/containerd/quick_start/
=> chore(docs): remove an extra back quote

.bazelignore, .devcontainer.json, .vscode/tasks.json
GitHub Codespaces are a wrapper around VSCode that enables "online" workspaces.
With a basic VSCode configuration, this works reasonably well for basic targets, and
can simplify editing and testing in some cases.
=> Add basic Codespaces configuration.

pkg/sentry/socket/unix/transport/unix.go
transport.baseEndpoint.receiver and transport.baseEndpoint.connected are
protected by transport.baseEndpoint.Mutex. In order to access them without
holding the mutex, we must make a copy.
Notifications must be sent without holding the mutex, so we need the values
without holding the mutex.
=> Fix race in unix socket transport.

pkg/ring0/pagetables/pagetables_arm64_test.go
=> apply hostarch on pagetables_arm64_test.go

test/syscalls/linux/32bit.cc
=> fix brace misplaced error

pkg/tcpip/link/fdbased/endpoint.go
Running multiple instances of netstack in the same network namespace can
cause collisions when enabling packet fanout for fdbased endpoints. The
only bulletproof fix is to run in different network namespaces, but by
using `getpid()` instead of 0 as the fanout ID starting point we can
avoid collisions in the common case, particularly when
testing/experimenting.
Addresses #6124
=> Avoid fanout group collisions with best effort

pkg/sentry/kernel/msgqueue/msgqueue.go, pkg/sentry/syscalls/linux/BUILD, pkg/sentry/syscalls/linux/linux64.go, pkg/sentry/syscalls/linux/sys_msgqueue.go, test/syscalls/linux/BUILD, test/syscalls/linux/msgqueue.cc
This PR implements msgsnd(2) and msgrcv(2). 
~It is currently dependent on changes in #6108, which is still in review. When #6108 is merged, I'll drop the commits, and rebase the branch over master.~ Done
Updates #135
=> Implement msgsnd(2) and msgrcv(2).

pkg/abi/linux/msgqueue.go, pkg/sentry/kernel/ipc/object.go, pkg/sentry/kernel/msgqueue/msgqueue.go, pkg/sentry/kernel/semaphore/semaphore.go, pkg/sentry/kernel/shm/shm.go, pkg/sentry/syscalls/linux/linux64.go, pkg/sentry/syscalls/linux/sys_msgqueue.go, pkg/sentry/syscalls/linux/sys_sem.go, test/syscalls/linux/msgqueue.cc
This PR provides functionality for msgctl(2). ~This is currently dependent on #6171, which is still being reviewed. When #6171 is merged, I'll rebase this branch over master.~ Done
Fixes #135
=> Implement msgctl(2).

go.mod, test/packetimpact/README.md, test/packetimpact/tests/udp_icmp_error_propagation_test.go
hello !
fix typo spelling grammar on documentation, and replace to correct words
=> fix: typo spelling grammar

pkg/sentry/fs/proc/sys.go, pkg/sentry/fsimpl/proc/tasks.go, pkg/sentry/fsimpl/proc/tasks_sys.go, test/syscalls/linux/proc_isolated.cc
Add the following static files
- `/proc/sys/kernel/msgmni`
- `/proc/sys/kernel/msgmnb`
- `/proc/sys/kernel/msgmax`
=> Add proc files for SysV message queues

README.md, tools/bazel.mk
=> Fix "Installing from source" instructions

g3doc/README.md
=> Fix typo in README.md

pkg/sentry/platform/kvm/machine_arm64.go
Only when PageFault happened, we need set accessType in order to
mapping the fault address.
Otherwise, it would trap in endless loop when exit vector is
El0ErrNMI or El0SyncUndef.
=> kvm/arm64: set accessType when signal is SIGSEGV

pkg/sentry/socket/unix/transport/connectioned.go
I am working on the lock validator and this change helps to avoid
false-positive reports of nested dependencies.
=> socket/unix: close sockets from acceptedChan after releasing the endpoint lock

pkg/sentry/fsimpl/testutil/kernel.go, pkg/sentry/kernel/kernel.go, pkg/sentry/kernel/task.go, pkg/sentry/kernel/task_clone.go, pkg/sentry/kernel/task_exit.go, pkg/sentry/kernel/task_start.go, test/syscalls/linux/BUILD, test/syscalls/linux/rlimits.cc
This is simplified version without supporting hierarchical
user-namespace counters.
=> Implement RLIMIT_NPROC

tools/checklocks/README.md
=> tools/checklocks: fix typo in readme

pkg/abi/linux/fuse.go, pkg/sentry/fsimpl/fuse/BUILD, pkg/sentry/fsimpl/fuse/dev.go, pkg/sentry/fsimpl/fuse/file.go, pkg/sentry/fsimpl/fuse/fusefs.go, pkg/sentry/fsimpl/fuse/read_write.go, pkg/sentry/fsimpl/fuse/request_response.go, pkg/sentry/vfs/filesystem_type.go, test/fuse/BUILD, test/fuse/linux/BUILD, test/fuse/linux/mount_test.cc, test/fuse/linux/statfs_test.cc, test/fuse/linux/write_test.cc
PR addresses issues:
* #7086
* fuse fsync, fuse rename, fuse flock
* #6964
* #3413
* #7001
Tested it locally.
=> extended fuse support

pkg/cpuid/cpuid_amd64_test.go, pkg/cpuid/native_amd64.go
=> cpuid: handle CPUID(0x80000006): L2 cache information

pkg/sentry/platform/kvm/context.go
Otherwise it can deadlock with as.invalidate.
Fixes: #7416
=> kvm: emulate cpuid after releasing the current vcpu

.buildkite/pipeline.yaml, tools/bazel.mk
https://github.com/google/gvisor/issues/5248
=> Run ptrace syscall tests on ARM64

runsc/sandbox/network.go
When multiple ipv4 ips are added on interfaces, gvisor fails to delete the additional ips from the
interface in sandbox networking mode with the following error:
`
starting container: setting up network: creating interfaces from net namespace "/proc/909056/ns/net":
removing address 10.0.2.101/24 from device "tun0": cannot assign requested address
`
This is due to the fact that additional ips on these interfaces are tagged as secondary ips.
When gvisor deletes the primary ip, secondary ips get deleted at the same time and cease to exist
on the interface.
This behavior is easily reproducible with the following commands:
```
$ sudo ip l a dev dum0 type dummy
$ sudo ip a l dum0
10: dum0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default qlen 1000
link/ether 72:5e:56:ba:e8:96 brd …
```
=> Check the ip is still on the interface when encountering an error while deleting an ip in sandbox networking mode

pkg/sentry/kernel/task_exit.go, test/syscalls/linux/exit.cc
Setting t.tg.exiting during PrepareGroupExit prevents a SIGKILL that
arrives while the task is zombied from changing the exit status (see
ThreadGroup.applySignalSideEffectsLocked).
However, PrepareExit does not set t.tg.exiting, meaning that if the last
task exits via exit(2), then a SIGKILL _can_ change the exit status.
This does not match Linux.
Fix this by detecting that we are the last task in PrepareExit and, if
so, going through the PrepareGroupExit path.
My initial version of this CL had Task.exitThreadGroup set t.tg.exiting
if it wasn't already set. This leaves a small window between return from
exit(2) and the start of the runExit state where a SIGKILL could still
change the exit status. While this window likely doesn't matter much in
practice, I suspect it is observable via …
=> Set tg.exiting on group exit via exit(2)

pkg/sentry/kernel/thread_group.go, test/syscalls/linux/pty.cc
Fixes two issues in TTOU handling while handling TIOCSPGRP on a tty
device.
fixes #7941; see that issue for details of the bugs.
Updates the tests to test the fixed behavior; both tests are verified
to fail without the `thread_group.go` fixes.
=> Fixes to TTOU handling in TIOCSPGRP

WORKSPACE, go.mod, go.sum, runsc/cgroup/BUILD, runsc/cgroup/cgroup_v2.go
Sync changes in runc https://github.com/opencontainers/runc/pull/3219
=> Replace bitset with stdlib math/big

pkg/sentry/fs/proc/task.go, pkg/sentry/fsimpl/proc/task.go, pkg/sentry/fsimpl/proc/task_files.go, pkg/sentry/fsimpl/proc/tasks_test.go, test/syscalls/linux/proc.cc
support /proc/[pid]/root file
Signed-off-by: Chen Hui <cedriccchen@tencent.com>
=> procfs: support /proc/[pid]/root file

pkg/abi/linux/ptrace_arm64.go, pkg/sentry/arch/arch_aarch64.go, pkg/sentry/arch/signal_arm64.go
Reported-by: syzbot+8c197c80d05172b4c587@syzkaller.appspotmail.com
=> arm64: validate registers that come from user-space

tools/make_apt.sh
=> Add "Origin: Google" to the APT repo metadata

pkg/tcpip/stack/route.go, pkg/tcpip/transport/tcp/endpoint_state.go
oof, no idea if you can even accept this change. feel free to close or whatever.
=> pkg/tcpip/stack: HasDisconncetOkCapability -> HasDisconnectOkCapability

pkg/tcpip/transport/udp/forwarder.go
=> netstack: fix UDP forwarding refcount bug

pkg/sentry/fsimpl/devpts/line_discipline.go, pkg/sentry/fsimpl/devpts/terminal.go
This fixes the ctrl-c/ctrl-z part of #422
I'm new to this codebase and I'm not sure if this way is the correct way to do it though.
=> Support some PTY control characters

pkg/sentry/kernel/task_exec.go
Reported-by: syzbot+c58795dc8124b39436a8@syzkaller.appspotmail.com
=> kernel: release kernel.taskSetRWMutex before calling TaskImage.Release

runsc/cmd/boot.go, runsc/cmd/exec.go, runsc/cmd/fd_mapping.go, runsc/cmd/run.go, runsc/donation/donation.go
Hello @nlacasse,
I just realized that the changes since the internal review in #8634 (https://github.com/google/gvisor/pull/8634#pullrequestreview-1333868455) got lost in merge 36793c0. d1f3b45 should have gotten merged. However, it looks like feb40ac got merged. This commit is the diff between feb40ac and d1f3b45.
Also see `git diff d1f3b45~1 d1f3b45 --name-only | xargs git diff d1f3b45 36793c0 --`.
=> Add lost changes to --pass-fd merge

pkg/tcpip/link/channel/channel.go, pkg/tcpip/link/fdbased/endpoint.go, pkg/tcpip/link/loopback/loopback.go, pkg/tcpip/link/waitable/waitable.go
=> tcpip/link: avoid attempts to deliver packets to nil dispatchers

Makefile
"systemctl reload docker" just sends SIGHUP to a docker daemon, but it doesn't wait for the signal to be handled.
=> make: wait for docker to load a new runtime

pkg/tcpip/transport/tcp/dispatcher.go
Several of these functions don't use their receivers, and can be reused in a later change.
=> netstack: convert TCP processor methods to functions

test/benchmarks/tcp/xdp.go
This was the classic "os.File loves to close important file descriptors" problem.
=> netstack: fix tcp_benchmark with XDP

pkg/tcpip/link/fdbased/processors.go
Ref: https://github.com/celzero/firestack/issues/59
=> fdbased: uint32 to int may overflow on 32-bit

g3doc/user_guide/FAQ.md
Mention two SELinux-related errors that we have seen in Fedora systems, explain how can the user verify that they trigger them, and provide a workaround.
The first error that we mention will be triggered by every user running gVisor in a Fedora system, so it's good to have a solution for them. The second error was found during the development of Dangerzone, which uses a nested gVisor container within a rootless Podman container. This use case is niche, but it still may help people who are experimenting with gVisor within another container.
Refs freedomofpress/dangerzone#880
=> doc: Add troubleshooting guide for SELinux errors

.buildkite/pipeline.yaml, Makefile, WORKSPACE, external/tools/plugin-stack/plugin-stack.BUILD, images/default/Dockerfile, runsc/sandbox/sandbox.go, test/root/runsc_test.go, tools/bazel.mk
=> buildkite: start testing the tldk network plugin

test/gpu/ffmpeg_test.go
This PR adds a NVDEC test by running the following ffmpeg command:
```
ffmpeg -y -vsync 0 -c:v h264_cuvid -i video.mp4 output.yuv
```
This command decodes `video.mp4` using `NVDEC`. I believe CUVID is just the [legacy name for NVDEC](https://en.wikipedia.org/wiki/Nvidia_NVDEC). I found the command from Section 4.2 of this PDF: https://docs.nvidia.com/video-technologies/video-codec-sdk/pdf/Using_FFmpeg_with_NVIDIA_GPU_Hardware_Acceleration.pdf
Also see #10988.
=> Add `ffmpeg` decoding GPU test with h264_cuvid (which uses NVDEC).

pkg/tcpip/transport/udp/endpoint.go, pkg/tcpip/transport/udp/forwarder.go
From: https://github.com/celzero/firestack/issues/98
=> tcpip/udp: deadlock in forwarder.go:CreateEndpoint

g3doc/user_guide/containerd/configuration.md
The link for Shim Configuration is out of date, so i fix it.
=> docs: Fix Shim Configuration link

g3doc/user_guide/tutorials/knative.md
use latest method for configurating gvisor across Knative Services
=> feat: update gVisor Knative user guide to use deployment config

g3doc/user_guide/containerd/configuration.md
see https://github.com/google/gvisor/issues/11326
=> Improve Documentation on gVisor's inotify Behavior with Shared Volumes

pkg/sentry/loader/elf.go
This is Xuzhou from Snowflake. We are currently working on a project which requires to use gVisor as secured sandbox for out workloads. As part of testing gVisor capabilities, we have found an issue on how gVisor loads elf file into memory, and we identified a fix to this issue, thus contributing the fix back.
The reproduce step is simple, create a gVisor container (ubuntu base image), and run `pip install prophet` to install latest prophet. Then following python script would crash with `segmentation fault`:
```
import os
import io
import sys
import pandas as pd
from prophet import Prophet
import logging
import sys
import time
def handler():
input_data = '''
"ds","y"
"2007-12-10",9.59076113897809
"2007-12-11",8.51959031601596
"2007-12-12",8.18367658262066
"2007-12-13",8.07246736935477
''' …
```
=> Only zero-out additional .load memory when memsz > filesz when loading elf file

g3doc/user_guide/tutorials/falco.md
=> update Falco chart links

images/gpu/cuda-tests-12-8/run_sample.go, images/gpu/cuda-tests/run_sample.go
fix some minor issues in the comments
=> chore: fix some minor issues in the comments
