- pkg/tcpip/transport/tcp/endpoint.go
- pkg/tcpip/transport/tcp/endpoint_state.go
- pkg/tcpip/transport/tcp/protocol.go
- pkg/tcpip/transport/tcp/segment_queue.go
Change segment queue limit to be of fixed size.
Netstack sets the unprocessed segment queue size to match the receive
buffer size. This is not required as this queue only needs to hold enough
for a short duration before the endpoint goroutine can process it.
> Change segment queue limit to be of fixed size.

- BUILD
- WORKSPACE
- cloudbuild/go.Dockerfile
- cloudbuild/go.yaml
- go.mod
- kokoro/run_tests.sh
- tools/go_branch.sh
Add tooling for Go-compatible branch.
The WORKSPACE go_repositories can be generated from a standard go.mod file. Add
the necessary gazelle hooks to do so, and include a test that sanity checks
there are no changes. This go.mod file will be used in a subsequent commit to
generate a go gettable branch of the repository.
This commit also adds a tools/go_branch.sh script, which given an existing go
branch in the repository, will add an additional synthetic change to the branch
bringing it up-to-date with HEAD.
> Add tooling for Go-compatible branch.

- pkg/sentry/mm/syscalls.go
gvisor: validate a new map region in the mremap syscall
Right now, mremap allows to remap a memory region over MaxUserAddress,
this means that we can change the stub region.
> gvisor: validate a new map region in the mremap syscall

- pkg/sentry/kernel/pipe/node.go
- pkg/sentry/kernel/pipe/node_test.go
- pkg/sentry/kernel/pipe/pipe.go
Remove the Dirent field from Pipe.
Dirents are ref-counted, but Pipes are not. Holding a Dirent inside of a Pipe
raises difficult questions about the lifecycle of the Pipe and Dirent.
> Remove the Dirent field from Pipe.

- pkg/tcpip/link/fdbased/endpoint.go
- pkg/tcpip/link/fdbased/endpoint_test.go
- pkg/tcpip/sample/tun_tcp_connect/main.go
- pkg/tcpip/sample/tun_tcp_echo/main.go
- pkg/urpc/urpc.go
- runsc/boot/config.go
- runsc/boot/network.go
- runsc/main.go
- runsc/sandbox/network.go
- runsc/test/testutil/testutil.go
Add multi-fd support to fdbased endpoint.
This allows an fdbased endpoint to have multiple underlying fd's from which
packets can be read and dispatched/written to.
This should allow for higher throughput as well as better scalability of the
network stack as number of connections increases.
> Add multi-fd support to fdbased endpoint.

- test/syscalls/linux/getdents.cc
Tests run at HEAD (35719d52):
```
$ bazel test $(bazel query 'filter(".*getdents.*", //test/syscalls:all)')
<snip>
//test/syscalls:getdents_test_native                                     PASSED in 0.3s
//test/syscalls:getdents_test_runsc_ptrace                               PASSED in 4.9s
//test/syscalls:getdents_test_runsc_ptrace_overlay                       PASSED in 4.7s
//test/syscalls:getdents_test_runsc_ptrace_shared                        PASSED in 5.2s
//test/syscalls:getdents_test_runsc_kvm                                  FAILED in 4.0s
```
Tests run at ab6774ce~1 (6f933a93):
```
$ bazel test $(bazel query 'filter(".*getdents.*", //test/syscalls:all)')
//test/syscalls:getdents_test_native                                     PASSED in 0.2s …
```
> Add regression test for #128 (fixed in ab6774ce)

- pkg/sentry/kernel/syslog.go
It feels like "reticulating splines" is missing from the list of meaningless
syslog messages.
> sentry/kernel: add syslog message

- runsc/boot/loader.go
> Fix use of "2 ^ 30".

- pkg/sentry/fs/proc/task.go
Readdir of /proc/x/task/ will get direntry entries
from tasks of specified taskgroup. Now the tasks
slice is unsorted, use sort.SearchInts search entry
from the slice may cause infinity loops.
The fix is sort the slice before search.
This issue could be easily reproduced via following
steps, revise Readdir in pkg/sentry/fs/proc/task.go,
force set taskInts into test slice
[]int{1, 11, 7, 5, 10, 6, 8, 3, 9, 2, 4},
then run docker image and run ls /proc/1/task, the
command will cause infinity loops.
> Fix deadloop in proc subtask list

- pkg/sentry/kernel/task_start.go
When leader of process group exit, the process
group ID is holding by other processes in the
process group, so the process group ID can not
be reused.
If reusing the process group ID as new process
group ID for new process, this will cause session
create failed, and later runsc crash when access
process group.
The fix skip the tid if it is using by a process
group when allocating a new tid.
We could easily reproduce the runsc crash follow
these steps:
1. build loop program
int main(int argc, char *argv[])
{
while(1) {
usleep(1);
}
return 0;
}
2. build hello program
int main(int argc, char *argv[])
{
printf("Current PID is %ld\n", (long) getpid());
return 0;
}
3. run script in container which run loop inside container
/test/loop &
ps -aef
4. run script on host which run hello inside …
> Skip tid allocation which is used by process group

- tools/go_generics/defs.bzl
- tools/go_generics/generics.go
- tools/go_generics/generics_tests/anon/input.go
- tools/go_generics/generics_tests/anon/opts.txt
- tools/go_generics/generics_tests/anon/output/output.go
- tools/go_generics/globals/globals_visitor.go
If I treat the Sel part of an ast.SelectorExpr I am able to use anonymous fields with renamed types.
I need this to allow for a lighter configuration file, as suggested [here](https://github.com/kubernetes/test-infra/pull/12440#issuecomment-506911877) by @cjwagner from Kubernetes SIG-testing.
Please let me know if I'm doing something wrong here...
> go_generics: handle anonymous fields with renamed types.

- pkg/sentry/syscalls/linux/sys_time.go
- pkg/sentry/syscalls/linux/sys_timerfd.go
- test/syscalls/linux/clock_gettime.cc
- test/syscalls/linux/timerfd.cc
- test/syscalls/linux/vdso_clock_gettime.cc
- vdso/vdso.cc
Makes CLOCK_BOOTTIME available with
* clock_gettime
* timerfd_create
* clock_gettime vDSO
CLOCK_BOOTTIME is implemented as an alias to CLOCK_MONOTONIC.
CLOCK_MONOTONIC already keeps track of time across save
and restore. This is the closest possible behavior to Linux
CLOCK_BOOTIME, as there is no concept of suspend/resume.
Updates google/gvisor#218
> Add CLOCK_BOOTTIME as a CLOCK_MONOTONIC alias

- pkg/sentry/control/proc.go
- pkg/sentry/kernel/kernel.go
- runsc/boot/fs.go
- runsc/boot/loader.go
- runsc/container/container_test.go
- runsc/container/multi_container_test.go
The different containers in a sandbox used only one pid
namespace before. This results in that a container can see
the processes in another container in the same sandbox.
This patch use different pid namespace for different containers.
Signed-off-by: chris.zn <chris.zn@antfin.com>
issue: https://github.com/google/gvisor/issues/217
gerrit: https://gvisor-review.googlesource.com/c/gvisor/+/17400
> Use different pidns among different containers

- pkg/fdnotifier/BUILD
- pkg/fdnotifier/fdnotifier.go
- pkg/sentry/socket/rpcinet/notifier/BUILD
- pkg/sentry/socket/rpcinet/notifier/notifier.go
syscall.EPOLLET has been defined with different values on amd64 and
arm64(-0x80000000 on amd64, and 0x80000000 on arm64), while unix.EPOLLET
has been unified this value to 0x80000000(golang/go#5328). ref #63
Change-Id: Id97d075c4e79d86a2ea3227ffbef02d8b00ffbb8
> Change syscall.EPOLLET to unix.EPOLLET

- scripts/build.sh
- scripts/common_bazel.sh
- scripts/release.sh
- tools/make_repository.sh
This has the following fixes:
* Packages are passed to the tools/make_repository.sh command.
* All matching tags are built, for commits with multiple.
* The binary path is generated by the build command.
* Output from signing the repository is supressed.
* The output path is cleaned for artifact copying.
Change-Id: I2d08954ba76e35612f352be99d5bb99080f80892
> Fix repository build scripts

- runsc/main.go
Only Dup & Dup3 were supported on Arm64 platform.
> Change syscall.Dup2 to syscall.Dup3

- pkg/fd/BUILD
- pkg/fd/fd.go
- runsc/boot/config.go
- runsc/cmd/gofer.go
- runsc/container/container.go
- runsc/fsgofer/filter/config.go
- runsc/fsgofer/filter/filter.go
- runsc/fsgofer/fsgofer.go
- runsc/main.go
This pull request adds the ability for mounting a Unix Domain Socket (UDS) from the host, and using the mounted socket from the container. The feature required implementing the `Connect` callback for the Gofer filesystem, adding the supported filetypes, and changing the implementation of the `Attach` point. Additionally, further `seccomp` permissions were added to allow for the filesystem process to connect to a host UDS.
This functionality operates as expected under circumstances where no networking is allowed.
Example output has been included below.
```
vagrant@ubuntu-xenial:/vagrant$ bazel build runsc && sudo systemctl restart docker && sudo docker run --runtime=runsc -it -v /home/vagrant/uds_socket:/uds_socket:rw gvisor_test bashINFO: Analyzed target //runsc:runsc (0 packages loaded, …
```
> Container mounting of host Unix Domain Socket support

- pkg/sentry/syscalls/linux/sys_utsname.go
- test/syscalls/linux/uname.cc
Previously, when we set hostname:
$ strace hostname abc
...
sethostname("abc", 3) = -1 ENAMETOOLONG (File name too long)
...
According to `man 2 sethostname`:
"The len argument specifies the number of bytes in name. (Thus, name
does not require a terminating null byte.)"
We wrongly use the CopyStringIn() to check terminating zero byte in
the implementation of sethostname syscall.
To fix this, we use CopyInBytes() instead.
Fixes: #861
Reported-by: chenglang.hy <chenglang.hy@antfin.com>
> fix set hostname

- pkg/sentry/usermem/usermem.go
`bytealg/indexbyte` will use AVX or SSE instruction set, if possible,
which could accelerate `CopyStringIn` function by 28%.
In worst case(CPU doesn't support SSE), `bytealg/indexbyte`
will degenerate to traversal lookup. When dealing with
short strings, `bytealg/indexbyte` has the same performance level as
before.
Signed-off-by: Hang Su <darcy.sh@antfin.com>
> Accelerate byte lookup in string with `bytealg/indexbyte`

- runsc/specutils/namespace.go
This commit adds the clone flag of cgroup namespace.
Signed-off-by: Kenta Tada <Kenta.Tada@sony.com>
> runsc: add the clone flag of cgroup namespace

- pkg/sentry/platform/kvm/testutil/BUILD
- pkg/sentry/platform/kvm/testutil/testutil.go
- pkg/sentry/platform/kvm/testutil/testutil_amd64.go
- pkg/sentry/platform/kvm/testutil/testutil_arm64.go
- pkg/sentry/platform/kvm/testutil/testutil_arm64.s
enable kvm/testutil to support arm64
The Arm64 user-mode execution stat consists of:
1, X0- X30
2, PC, SP, PSTATE
3, TPIDR_EL0, used for TLS
4, V0-V31: 32 128-bit registers for floating point and simd
5, FPSR
Currently, we first achieve goals 1 and 2.
This patch provids basic test utils for goals 1 & 2
> enable kvm/testutil to support arm64

- pkg/abi/linux/netlink_route.go
- pkg/sentry/fs/proc/BUILD
- pkg/sentry/fs/proc/net.go
- pkg/sentry/inet/inet.go
- pkg/sentry/socket/hostinet/stack.go
- pkg/sentry/socket/netstack/netstack.go
- pkg/sentry/socket/netstack/stack.go
- pkg/tcpip/tcpip.go
- pkg/tcpip/transport/tcp/accept.go
- pkg/tcpip/transport/tcp/connect.go
- pkg/tcpip/transport/tcp/endpoint.go
- pkg/tcpip/transport/tcp/snd.go
- test/syscalls/linux/BUILD
- test/syscalls/linux/proc_net.cc
Support for /proc/net/dev, /proc/net/route, and /proc/net/snmp [1]. This should enable the use of tools such as route[2].
[1] https://tools.ietf.org/html/rfc2013
[2] http://man7.org/linux/man-pages/man8/route.8.html
> Support /proc/net/dev, /proc/net/route, /proc/net/snmp

- pkg/abi/linux/BUILD
- pkg/abi/linux/file.go
- pkg/abi/linux/file_amd64.go
- pkg/abi/linux/file_arm64.go
In glibc, some structures are defined differently on different
platforms.
Such as: C.struct_stat
> slight changes to pkg/abi

- pkg/p9/p9.go
- runsc/fsgofer/fsgofer.go
Since the syscall.Stat_t.Nlink is defined as different types on
amd64 and arm64(uint64 and uint32 respectively), we need to cast
them to a unified uint64 type in gVisor code.
Change-Id: I7542b99b195c708f3fc49b1cbe6adebdd2f6e96b
> Cast the Stat_t.Nlink to uint64 on arm64.

- runsc/fsgofer/BUILD
- runsc/fsgofer/filter/BUILD
- runsc/fsgofer/filter/config.go
- runsc/fsgofer/filter/config_amd64.go
- runsc/fsgofer/filter/config_arm64.go
- runsc/fsgofer/fsgofer_amd64_unsafe.go
- runsc/fsgofer/fsgofer_arm64_unsafe.go
- runsc/fsgofer/fsgofer_unsafe.go
newfstatat() syscall is not supported on arm64, so we resort
to use the fstatat() syscall.
Change-Id: I9e89d46c5ec9ae07db201c9da5b6dda9bfd2eaf0
> Enable runsc/fsgofer support on arm64.

- WORKSPACE
This includes https://github.com/bazelbuild/bazel-gazelle/pull/666, which should allow building gVisor on NixOS (or anywhere else with custom SSL certificate requirements).
> Bump gazelle to v0.19.1

- pkg/sentry/platform/ring0/BUILD
- pkg/sentry/platform/ring0/aarch64.go
- pkg/sentry/platform/ring0/defs.go
- pkg/sentry/platform/ring0/defs_arm64.go
- pkg/sentry/platform/ring0/entry_arm64.go
- pkg/sentry/platform/ring0/entry_arm64.s
- pkg/sentry/platform/ring0/kernel_arm64.go
- pkg/sentry/platform/ring0/lib_arm64.go
- pkg/sentry/platform/ring0/offsets_arm64.go
This patch enabled the basic framework for arm64 guest.
Serveral jobs were finished in this patch:
1, ring0.Vectors()
2, switchToUser()
3, basic framwork for Arm64 guest.
...
> enable ring0 to support arm64

- pkg/seccomp/seccomp_test_victim.go
- pkg/sentry/fs/gofer/inode.go
- runsc/boot/BUILD
- runsc/boot/filter/BUILD
- runsc/boot/filter/config.go
- runsc/boot/filter/config_amd64.go
- runsc/boot/filter/config_arm64.go
- runsc/boot/loader.go
- runsc/boot/loader_amd64.go
- runsc/boot/loader_arm64.go
Change-Id: I00beb9cc492e44c762ebaa3750201c63c1f7c2f3
> Enable runsc/boot support on arm64.

- runsc/fsgofer/fsgofer.go
Refer to golang mallocgc(), each time of allocating an object > 32 KB,
a gc will be triggered.
When we do readdir, sentry always passes 65535, which leads to a malloc
of 65535 * sizeof(p9.Direnta) > 32 KB.
Let's define a smaller maxCount to avoid this.
Command for test:
Before this change:
(container)$ time tree linux-5.3.1 > /dev/null
real    0m54.272s
user    0m2.010s
sys     0m1.740s
(CPU usage of Gofer: ~30 cores)
(host)$ perf top -p <pid-of-gofer>
42.57%  runsc        [.] runtime.gcDrain
23.41%  runsc        [.] runtime.(*lfstack).pop
9.74%  runsc        [.] runtime.greyobject
8.06%  runsc        [.] runtime.(*lfstack).push
4.33%  runsc        [.] runtime.scanobject
1.69%  runsc        [.] runtime.findObject
1.12%  runsc        [.] runtime.findrunnable
0.69%  runsc        [.] …
> gofer: reduce CPU usage on GC as of frequent readdir

- pkg/sentry/fs/gofer/path.go
Fix UDS bind cause fd leak in gofer
After the finalizer optimize in 76039f895995c3fe0deef5958f843868685ecc38
commit, clientFile needs to closed before finalizer release it.
The clientFile is not closed if it is created via
gofer.(*inodeOperations).Bind, this will cause fd leak which is hold
by gofer process.
Fixes #1396
> Fix UDS bind cause fd leak in gofer

- pkg/sentry/fs/inode_overlay.go
Copy up parent when binding UDS on overlayfs is supported in commit
02ab1f187cd24c67b754b004229421d189cee264.
But the using of copyUp in overlayBind will cause sentry stuck, reason
is dead lock in renameMu.
1 [Process A] Invoke a Unix socket bind operation
renameMu is hold in fs.(*Dirent).genericCreate by process A
2 [Process B] Invoke a read syscall on /proc/task/mounts
waitng on Lock of renameMu in fs.(*MountNamespace).FindMount
3 [Process A] Continue Unix socket bind operation
wating on RLock of renameMu in fs.copyUp
Root cause is recursive reading lock of reanmeMu in bind call trace,
if there are writing lock between the two reading lock, then deadlock
occured.
Fixes #1397
> Fix deadlock in overlay bind

- runsc/boot/config.go
- runsc/cgroup/cgroup.go
- runsc/main.go
- runsc/sandbox/sandbox.go
When application is not cgroups-aware, it can spawn excessive threads
which often defaults to CPU number.
Introduce a opt-in flag that will set CPU number accordingly to CPU
quota (if available).
Fixes #1391
```bash
$ docker run --rm --cpus 6 ubuntu nproc
6
$ docker run --rm --cpus 0.5 ubuntu nproc
1
```
To enable this feature, user can configure additional runtime, something like:
```json
{
"runtimes": {
"runsc-autocpu": {
"path": "/usr/bin/runsc",
"runtimeArgs": [
"--cpu-num-from-quota"
]            
},
"runsc": {
"path": "/usr/bin/runsc"
}
}
}
```
> Set CPU number to CPU quota

- pkg/sentry/platform/ring0/BUILD
- pkg/sentry/platform/ring0/defs_arm64.go
- pkg/sentry/platform/ring0/entry_arm64.s
- pkg/sentry/platform/ring0/lib_arm64.go
- pkg/sentry/platform/ring0/lib_arm64.s
- pkg/sentry/platform/ring0/offsets_arm64.go
Several jobs were finished in this patch:
1, provide functions to get/set fpcr/fpsr/vregs
2, support lazy-fpsimd-context-switch in el1
> supporting lazy-fpsimd in guest on Arm64

- tools/go_stateify/defs.bzl
- tools/go_stateify/main.go
2 jobs were finished in this patch:
1, add a new attribute to specify the target platform.
2, add 2 extra rules to generate codes for different target platforms.
> Add tools/go_stateify to support Arm64

- pkg/sentry/platform/ring0/entry_arm64.s
- pkg/sentry/platform/ring0/lib_arm64.s
- pkg/sentry/platform/ring0/pagetables/BUILD
There are 2 jobs have been finished in this patch:
1, a comment was added to explain the purpose of the extra NOPs in Vectors().
2, some merge errors were fixed.
> slight changes to ring0&pagetables for Arm64

- pkg/sentry/platform/ptrace/subprocess.go
- pkg/sentry/platform/ptrace/subprocess_linux.go
Linux PTRACE_SYSEMU support on arm64 was merged to mainline from
V5.3, and the corresponding support in go also enabled recently.
Since the "syscall" package is locked down from go 1.4, so the ptrace
PTRACE_SYSEMU definition can't be added to package "syscall" on arm64.
According to the golang community, updates required by new systems or
versions should use the corresponding package in the golang.org/x/sys
repository instead(https://golang.org/pkg/syscall/).
Change-Id: I2f917bb2be62f990c3e158e2bb99e094ea03f751
> Replace syscall.PTRACE_SYSEMU with unix.PTRACE_SYSEMU

- pkg/tcpip/transport/tcp/endpoint.go
- pkg/tcpip/transport/tcp/rcv.go
- pkg/tcpip/transport/tcp/tcp_test.go
When receiving data, netstack avoids sending spurious acks. When
user does recv() should netstack send ack telling the sender that
the window was increased? It depends. Before this patch, netstack
_will_ send the ack in the case when window was zero or window >>
scale was zero. Basically - when recv space increased from zero.
This is not working right with silly-window-avoidance on the sender
side. Some network stacks refuse to transmit segments, that will fill
the window but are below MSS. Before this patch, this confuses
netstack. On one hand if the window was like 3 bytes, netstack
will _not_ send ack if the window increases. On the other hand
sending party will refuse to transmit 3-byte packet.
This patch changes that, making netstack treat a window below MTU
as a zero window. …
> #1398 - treat receive buffer smaller than MTU as zero window

- pkg/sentry/platform/kvm/machine_amd64.go
- pkg/sentry/platform/kvm/machine_arm64.go
When PCID is disabled, there would throw a panic
when dropPageTables() access to c.PCID without check.
Signed-off-by: Lai Jiangshan <eag0628@gmail.com>
> Avoid panic when c.PCIDs is nil

- pkg/sentry/platform/ring0/entry_arm64.s
For test case "TestKernelFault", memory-fault in guest kernel level will be trapped in el1_da. 
And in el1_da, we use mmio_exit to leave the KVM guest.
> passed the kvm test case of "TestKernelFault" on Arm64 platform

- test/util/save_util_linux.cc
There is no syscall_create_module on Arm64.
And the errno also can be set as ENOSYS by syscall(-1) on amd64/arm64.
So, syscall_create_module can be replaced by syscall(-1) in my opinion.
My test command:
bazel test --test_tag_filters=runsc_ptrace //test/syscalls/... --test_output=streamed --action_env=GVISOR_COOPERATIVE_SAVE_TEST=1
> Add test/util/save_util_linux.cc:MaybeSave to support arm64

- test/syscalls/linux/proc.cc
Problems with different platform architectures have been solved.
> enable //test/syscalls:proc_test support on Arm64

- pkg/sentry/platform/ring0/entry_arm64.s
For test case "TestApplicationSyscall",
Syscall in guest user level will be trapped in el0_svc.
And in el0_svc, we use mmio_exit to leave the KVM guest for now.
> passed the kvm test case of "TestApplicationSyscall" on Arm64 platform

- pkg/sentry/platform/ring0/entry_arm64.s
For test case "TestApplicationFault",
Memory-fault in guest user level will be trapped in el0_da.
And in el0_da, we use mmio_exit to leave the KVM guest.
> passed the kvm test case of "TestApplicationFault" on Arm64 platform

- pkg/tcpip/adapters/gonet/gonet.go
PacketConn.LocalAddr() already returns *net.UDPAddr correctly.
> gonet PacketConn.RemoteAddr() incorrectly returns *net.TCPAddr, shouldd be *net.UDPAddr

- test/syscalls/linux/fault.cc
Change-Id: I9b2b2e0d84946c10cf136abeef6c60642fa3b6ec
> Enable fault() syscall test on arm64.

- pkg/tcpip/adapters/gonet/gonet.go
gonet.Conn can be created with both gonet.NewConn and gonet.Dial.
gonet.PacketConn was created only by gonet.DialUDP. This prevented
us from being able to use PacketConn in udp.NewForwarder() context.
This simple constructor - NewPacketConn, allows user to create
correct structure from that context.
> Expose gonet.NewPacketConn, for parity with gonet.NewConn API

- pkg/sentry/kernel/tty.go
If we don't hold taskset.mu in TTY(), it may cause a "unlock of
unlocked mutex" problem, since signalHandlers may be replaced by
CopyForExec() in runSyscallAfterExecStop after TTY() holds the
signalHandlers.mu.
The problem is easy to recur with keeping to do "runsc ps".
The crash log is :
```
fatal error: sync: unlock of unlocked mutex
goroutine 5801304 [running]:
runtime.throw(0xfd019c, 0x1e)
GOROOT/src/runtime/panic.go:774 +0x72 fp=0xc001ba47b0 sp=0xc001ba4780 pc=0x431702
sync.throw(0xfd019c, 0x1e)
GOROOT/src/runtime/panic.go:760 +0x35 fp=0xc001ba47d0 sp=0xc001ba47b0 pc=0x431685
sync.(*Mutex).unlockSlow(0xc00cf94a30, 0xc0ffffffff)
GOROOT/src/sync/mutex.go:196 +0xd6 fp=0xc001ba47f8 sp=0xc001ba47d0 pc=0x4707d6
sync.(*Mutex).Unlock(0xc00cf94a30)
GOROOT/src/sync/mutex.go:190 +0x48 …
```
> Hold taskset.mu when getting tty

- pkg/sentry/platform/ring0/aarch64.go
- pkg/sentry/platform/ring0/entry_arm64.s
- pkg/sentry/platform/ring0/offsets_arm64.go
For test case 'TestBounce', I used KVM_SET_VCPU_EVENTS to trigger sError to leave the guest.
Maybe irqfd is better.
> supporting sError in guest kernel on Arm64

- test/syscalls/linux/fcntl.cc
- test/syscalls/linux/pipe.cc
- test/syscalls/linux/proc.cc
- test/util/fs_util.h
Change-Id: Id9d6ae98305a4057d55d622ea4c3ac2228fea212
> Unify the kOLargeFile definition in syscall tests.

- pkg/sentry/socket/netfilter/netfilter.go
- pkg/tcpip/iptables/iptables.go
- pkg/tcpip/iptables/targets.go
- pkg/tcpip/iptables/types.go
- test/iptables/filter_input.go
- test/iptables/iptables_test.go
- Adds creation of user chains via `-N <chainname>`
- Adds `-j RETURN` support for built-in chains, which triggers the
chain's underflow rule (usually the default policy).
- Adds tests for chain creation, default policies, and `-j RETURN' from
built-in chains.
> iptables: user chains

- WORKSPACE
ARM64 PTRACE_SYSEMU support was added to Linux kernal from
v5.3 and the corresponding support in golang is also enabled
in the latest org.golang/x/sys repository.
Fixes #1876
Change-Id: I10750c4c8b68f6f68d0a4d828e266966434c92fe
> Force downloading new version of org_golang_x_sys.

- pkg/sentry/platform/ring0/entry_arm64.s
- pkg/sentry/platform/ring0/kernel_arm64.go
For kvm test case "TestKernelSyscall",
redpill/syscall(-1) in guest kernel level will be trapped in el1_svc.
And in el1_svc, we use mmio_exit to leave the guest.
> passed the kvm test case of "TestKernelSyscall" on Arm64 platform

- pkg/sentry/arch/arch_aarch64.go
- pkg/sentry/arch/arch_arm64.go
- pkg/sentry/arch/signal_arm64.go
This patch defines the structures and
adds the implementations for fpsimd initialization.
> Lazy-fpsimd supporting#1: add Arm64-fpsimd support to arch module

- pkg/sentry/arch/arch_arm64.go
- pkg/sentry/kernel/task_run.go
There is no cpuid instruction on arm64, but we need to defined it
just to avoid a compile time error.
> Define CPUIDInstruction for arm64

- vdso/vdso.cc
The glibc uses vdso to call getres on Arm64 platform.
Test command:
bazel test //test/syscalls:clock_getres_test_runsc_ptrace
> passed the syscall test case 'clock_getres' on Arm64 platform

- test/runner/gtest/gtest.go
- test/syscalls/linux/tuntap_hostinet.cc
The benchmark_filter options accepts regex-s, but
the gtest-filter option accepts shell-like wildcards.
Fixes #2034
Signed-off-by: Andrei Vagin <avagin@gmail.com>
> test/runner: use proper filters for test cases and benchmarks

- test/syscalls/linux/BUILD
The error was introduced in the merge of PR #1471.
Some codes are missing when adding bazel select_arch
command to the test/syscall/linux/BUILD file.
Change-Id: I8cae3f4ae78c2e14671f3ac6e7361dc2806d9305
> Fix syscall test build error on arm64.

- pkg/sentry/control/pprof.go
- runsc/boot/controller.go
- runsc/cmd/debug.go
- runsc/sandbox/sandbox.go
Now runsc only supports CPU and heap profiles.
I added the following new debug option!
- `--profile-goroutine`
- `--profile-block`
- `--profile-mutex`
ref: https://github.com/google/gvisor/issues/220
> Add profiling option for debug

- WORKSPACE
This includes https://github.com/bazelbuild/rules_python/pull/279, which makes files generated by `rules_python` reproducible. Necessary to upgrade gvisor in NixOS (NixOS/nixpkgs#80875)
> WORKSPACE: bump rules_python to include reproducibility fix

- pkg/abi/linux/elf.go
- pkg/sentry/arch/arch_aarch64.go
- pkg/sentry/arch/arch_arm64.go
- pkg/sentry/platform/ptrace/BUILD
- pkg/sentry/platform/ptrace/ptrace_arm64_unsafe.go
- pkg/sentry/platform/ptrace/subprocess.go
Linux use the task.thread.uw.tp_value field to store the
TLS pointer on arm64 platform, and we use a similar way
in gvisor to store it in the arch/State struct.
Change-Id: Ie76b5c6d109bc27ccfd594008a96753806db7764
> Enable thread local storage support on arm64.

- scripts/iptables_tests.sh
- test/iptables/filter_input.go
- test/iptables/filter_output.go
- test/iptables/iptables_test.go
- test/iptables/iptables_util.go
- test/iptables/nat.go
Fixed flakes (tested via --runs_per_test=100) and added skips for
not-yet-implemented features. Once submitted, the iptables tests will be
ready to enable in kokoro.
> iptables: ready tests to be enabled in kokoro

- pkg/abi/linux/netfilter.go
- pkg/sentry/socket/netfilter/netfilter.go
- pkg/tcpip/iptables/iptables.go
- pkg/tcpip/iptables/types.go
- test/iptables/filter_input.go
- test/iptables/filter_output.go
- test/iptables/iptables_test.go
- test/iptables/iptables_util.go
- test/iptables/nat.go
Enables commands such as:
$ iptables -A INPUT -d 127.0.0.1 -j ACCEPT
$ iptables -t nat -A PREROUTING ! -d 127.0.0.1 -j REDIRECT
Also adds a bunch of REDIRECT+destination tests.
> iptables: filter by IP address (and range)

- pkg/sentry/arch/arch_aarch64.go
- pkg/sentry/arch/syscalls_arm64.go
This issue was caused by 'restart_syscall'.
The value of Register R0 should be stored after finishing sysemu.
So that we can restore the value and restart syscall.
> passed the syscall test case 'alarm' on Arm64 platform

- test/iptables/filter_input.go
- test/iptables/iptables_util.go
These tests could timeout because net.DialTCP didn't respect the
timeout.
> iptables: deflake DropTCP*Port tests

- BUILD
- tools/BUILD
- tools/go_marshal/gomarshal/generator.go
- tools/nogo.js
- tools/nogo.json
This enforces basic sanity checks, such as ensuring that Log arguments align
with the format, and that locks are not copied. Exceptions are encoded for all
existing violations, which should be removed over time.
Updates #2243
> Enable nogo analyzers.

- pkg/abi/linux/netfilter.go
- pkg/abi/linux/netfilter_test.go
- pkg/sentry/kernel/task.go
- pkg/sentry/socket/netfilter/BUILD
- pkg/sentry/socket/netfilter/netfilter.go
- pkg/sentry/socket/netfilter/owner_matcher.go
- pkg/sentry/socket/netstack/provider.go
- pkg/tcpip/network/ipv4/ipv4.go
- pkg/tcpip/stack/packet_buffer.go
- pkg/tcpip/stack/transport_test.go
- pkg/tcpip/tcpip.go
- pkg/tcpip/transport/icmp/endpoint.go
- pkg/tcpip/transport/packet/endpoint.go
- pkg/tcpip/transport/raw/endpoint.go
- pkg/tcpip/transport/tcp/accept.go
- pkg/tcpip/transport/tcp/connect.go
- pkg/tcpip/transport/tcp/endpoint.go
- pkg/tcpip/transport/tcp/forwarder.go
- pkg/tcpip/transport/tcp/protocol.go
- pkg/tcpip/transport/udp/endpoint.go
- test/iptables/filter_output.go
- test/iptables/iptables_test.go
Owner matching will match UID/GID of packet creator, for locally
generated packets. This is only valid in the OUTPUT and POSTROUTING
chains.
Added tests to check owner matching for TCP and UDP packets.
> Support owner matching for iptables.

- test/syscalls/linux/BUILD
- test/syscalls/linux/exec_binary.cc
Added the binary data for corresponding Arm64 test cases, and modified pt_regs related to the platform.
> Enable exec_binary syscall test on Arm64

- pkg/sentry/mm/lifecycle.go
- pkg/sentry/mm/metadata.go
- pkg/sentry/mm/mm.go
Store the arch-specific vdso features directly in the MemoryManager.
I stored the address of the VDSO_Sigreturn into MemoryManager directly.
So that, I can copy the address of vdso_sigreturn into R30 in setup_return().
This method is same with Linux cdoe.
Please see the linux code as reference:
https://github.com/torvalds/linux/blob/master/arch/arm64/kernel/signal.c#L735
Related PR-s: 
Arm64 signal#2: VDSO support for signal #1818
Arm64 signal#3: signal support in arch module #1819
> Arm64 signal#1: add arch-specific feature into mm

- pkg/sentry/socket/netfilter/tcp_matcher.go
- pkg/sentry/socket/netfilter/udp_matcher.go
- pkg/tcpip/buffer/view.go
- pkg/tcpip/buffer/view_test.go
- pkg/tcpip/link/loopback/loopback.go
- pkg/tcpip/link/sharedmem/sharedmem_test.go
- pkg/tcpip/link/sniffer/sniffer.go
- pkg/tcpip/network/arp/arp.go
- pkg/tcpip/network/ipv4/icmp.go
- pkg/tcpip/network/ipv4/ipv4.go
- pkg/tcpip/network/ipv6/icmp.go
- pkg/tcpip/network/ipv6/icmp_test.go
- pkg/tcpip/network/ipv6/ipv6.go
- pkg/tcpip/stack/forwarder_test.go
- pkg/tcpip/stack/iptables.go
- pkg/tcpip/stack/iptables_targets.go
- pkg/tcpip/stack/nic.go
- pkg/tcpip/stack/packet_buffer.go
- pkg/tcpip/stack/stack_test.go
- pkg/tcpip/stack/transport_test.go
- pkg/tcpip/transport/icmp/endpoint.go
- pkg/tcpip/transport/tcp/segment.go
- pkg/tcpip/transport/tcp/tcp_test.go
- pkg/tcpip/transport/udp/endpoint.go
- pkg/tcpip/transport/udp/protocol.go
These methods let users eaily break the VectorisedView abstraction, and
allowed netstack to slip into pseudo-enforcement of the "all headers are
in the first View" invariant. Removing them and replacing with PullUp(n)
breaks this reliance and will make it easier to add iptables support and
rework network buffer management.
The new View.PullUp(n) method is low cost in the common case, when when
all the headers fit in the first View.
> Remove View.First() and View.RemoveFirst()

- pkg/sentry/loader/loader.go
- pkg/sentry/loader/vdso.go
- vdso/syscalls.h
- vdso/vdso.cc
- vdso/vdso_amd64.lds
The vdso is enabled, so we can use the sigreturn trampolines
the vdso provides in arch module.
> Arm64 signal#2: VDSO support for signal

- benchmarks/README.md
bazel run :benchmarks only works from the benchmarks directory.
bazel run //benchmarks works from anywhere in the workspace.
Also fix help commands, which should be a multiline code section.
> benchmarks: use absolute bazel target

- runsc/cmd/do.go
- runsc/main.go
Previously we unconditionally failed to cleanup the networking files
(hostname, resolve.conf, hosts), and failed to cleanup the netns, etc on
partial setup failure.
We can drop the iptables commands from cleanup, as the routes
automatically go away when the device is deleted. Those commands were
failing previously.
Forward signals to the container, allowing it to exit normally when a
signal is received, and then for runsc to run the cleanup. This doesn't
cover cleanup when runsc is signalled before the container start, it
covers the most common case.
Fixes #2539
Fixes #2540
> runsc: extend do network cleanup

- runsc/container/BUILD
- runsc/container/container.go
Use the sighandling package for Container.ForwardSignals, for
consistency with other signal forwarding.
Fixes #2546
> container: use sighandling package

- pkg/sentry/fs/filesystems.go
- runsc/boot/fs.go
- runsc/container/container_test.go
- runsc/container/multi_container_test.go
- runsc/specutils/specutils.go
This fixes behavior of `getMountNameAndOptions` func based on OCI runtime spec(https://github.com/opencontainers/runtime-spec/blob/master/config.md#posix-platform-mounts).
In detail, if the mount type is equal to "none" or other dummy string and the mount option includes either "bind" or  "rbind",  `getMountNameAndOptions` behave as the mount type is equal to "bind".
Fix: https://github.com/google/gvisor/issues/2330
Signed-off-by: moricho <ikeda.morito@gmail.com>
> Make mount type optional for bind mounts

- pkg/sentry/socket/netfilter/netfilter.go
- pkg/sentry/socket/netfilter/targets.go
- pkg/sentry/socket/netfilter/tcp_matcher.go
- pkg/sentry/socket/netfilter/udp_matcher.go
- pkg/tcpip/header/tcp.go
- pkg/tcpip/network/ipv4/ipv4.go
- pkg/tcpip/stack/BUILD
- pkg/tcpip/stack/conntrack.go
- pkg/tcpip/stack/iptables.go
- pkg/tcpip/stack/iptables_targets.go
- pkg/tcpip/stack/iptables_types.go
- pkg/tcpip/stack/nic.go
- pkg/tcpip/stack/packet_buffer.go
- pkg/tcpip/stack/route.go
- pkg/tcpip/stack/stack.go
- pkg/tcpip/transport/tcp/BUILD
- pkg/tcpip/transport/tcp/rcv.go
- pkg/tcpip/transport/tcp/rcv_test.go
- pkg/tcpip/transport/tcpconntrack/BUILD
- pkg/tcpip/transport/tcpconntrack/tcp_conntrack.go
- test/iptables/filter_output.go
- test/iptables/iptables_test.go
- test/iptables/iptables_util.go
- test/iptables/nat.go
Connection tracking is used to track packets in prerouting and
output hooks of iptables. The NAT rules modify the tuples in
connections. The connection tracking code modifies the packets by
looking at the modified tuples.
> Support for connection tracking of TCP packets.

- pkg/sentry/arch/arch_aarch64.go
Test steps:
cd pkg/sentry/arch/
bazel build .
The error log is below:
/root/.cache/bazel/_bazel_root/f3b369e7325850c58bec1b7d63bbc49c/sandbox/linux-sandbox/588/execroot/__main__/pkg/sentry/arch/arch_aarch64.go:277:15: undefined: ptraceRegsSize
/root/.cache/bazel/_bazel_root/f3b369e7325850c58bec1b7d63bbc49c/sandbox/linux-sandbox/588/execroot/__main__/pkg/sentry/arch/arch_aarch64.go:290:15: undefined: ptraceRegsSize
> code clean in arch module

- tools/bazel.mk
Without this fix, make exits with zero code when "bazel build" failed:
```
$ make run TARGETS="--abra --kadabra"
ERROR: Unrecognized option: --abra
$ echo $?
0
```
> make: exit with non-zero code when "bazel build" failed

- pkg/sentry/socket/netfilter/owner_matcher.go
- test/iptables/filter_output.go
- test/iptables/iptables_test.go
- Added support for matching gid owner and invert flag for uid
and gid.
$ iptables -A OUTPUT -p tcp -m owner --gid-owner root -j ACCEPT
$ iptables -A OUTPUT -p tcp -m owner ! --uid-owner root -j ACCEPT
$ iptables -A OUTPUT -p tcp -m owner ! --gid-owner root -j DROP
- Added tests for uid, gid and invert flags.
> iptables: support gid match for owner matching.

- test/syscalls/linux/BUILD
- test/syscalls/linux/fpsig_fork.cc
Some functions were added for Arm64 platform:
a, get_fp/set_fp
b, inline_tgkill
Test step:
bazel test //test/syscalls:fpsig_fork_test_runsc_ptrace
> passed the syscall test case 'fpsig_fork' on Arm64 platform

- pkg/sentry/platform/ring0/lib_arm64.go
- pkg/sentry/platform/ring0/lib_arm64.s
AArch64 has a dedicated register (TPIDR_EL0) for TLS.
This patch provides the methods to get/set TPIDR_EL0 in kvm guest.
Related issue: full context-switch supporting for Arm64 https://github.com/google/gvisor/issues/1238
> adding the methods to get/set TLS for Arm64 kvm platform

- Makefile
test_tag_filter => test_tag_filters
Ref: https://docs.bazel.build/versions/master/command-line-reference.html#flag--test_tag_filters
> Fix typo in 'make tests' recipe

- test/runner/runner.go
Signed-off-by: Gaurav Singh <gaurav1086@gmail.com>
* [y ] Have you followed the guidelines in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md)?
* [ y] Have you formatted and linted your code?
* [n ] Have you added relevant tests?
* [y ] Have you added appropriate Fixes & Updates references?
* [- ] If yes, please erase all these lines!
the channel done need to be buffered to prevent the goroutine from hanging indefinitely
when the select statement reads something other than the one the goroutine sends on. i.e. timeouts
> runner: fix goroutine leak

- pkg/sentry/platform/kvm/machine_arm64.go
It's a workaround to treat PROT_NONE as RDONLY temporarily.
TODO(https://github.com/google/gvisor/issues/2686): PROT_NONE should be specially treated.
> PROT_NONE should be specially treated in the step of mapPhysical

- .travis.yml
- Makefile
- tools/bazel.mk
And don't parse binary paths for the build target. Without this,
make build TARGETS=''..." always fails.
> make: Allow to specify bazel startup options.

- pkg/sentry/fs/g3doc/fuse.md
This change adds more information about what needs to be done
to implement `/dev/fuse`
> Add some detail to milestone #1

- benchmarks/workloads/absl/Dockerfile
- benchmarks/workloads/tensorflow/Dockerfile
- images/packetdrill/Dockerfile
optimize the git clone using --depth flag in term of size of clone
and also in term's of time taken to fetch the files and commit history
of whole repository .
More detail can be found at blog
https://www.atlassian.com/git/tutorials/big-repositories
Signed-off-by: Pratik Raj <rajpratik71@gmail.com>
> optimization in git clone using --depth

- test/runner/defs.bzl
A few tests use hard coded port numbers, so we need to guarantee that
these ports will not be used for something else.
> test/syscall: run hostnet tests in separate network namespaces

- pkg/tcpip/network/ipv4/ipv4.go
- pkg/tcpip/stack/nic.go
- test/iptables/iptables_test.go
- test/iptables/nat.go
Loopback traffic is not affected by rules in the PREROUTING chain.
This change is also necessary for istio's envoy to talk to other
components in the same pod.
> iptables: loopback traffic skips prerouting chain

- tools/go_generics/globals/scope.go
It doesn't make sense to update the same symbol with different token.Pos
> scope.add should only record the first position

- pkg/sentry/arch/arch_aarch64.go
We need to clear out and initialize an empty fp state area since the sentry.
> initialize an empty fp state area for sentry on Arm64

- pkg/sentry/kernel/timekeeper.go
Signed-off-by: Gaurav Singh <gaurav1086@gmail.com>
* [y ] Have you followed the guidelines in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md)?
* [y ] Have you formatted and linted your code?
* [n ] Have you added relevant tests?
* [y ] Have you added appropriate Fixes & Updates references?
* [- ] If yes, please erase all these lines!
The PR moves the t.wg.Done() at the top to be unconditional rather than only on t.Stop() executes.
> sentry: use defer wg.Done() unconditionally

- pkg/sentry/platform/kvm/bluepill_amd64_unsafe.go
- pkg/sentry/platform/kvm/bluepill_arm64_unsafe.go
- pkg/sentry/platform/kvm/bluepill_unsafe.go
- pkg/sentry/platform/kvm/kvm_arm64.go
- pkg/sentry/platform/kvm/kvm_const.go
- pkg/sentry/platform/kvm/kvm_const_arm64.go
- pkg/sentry/platform/kvm/machine_arm64_unsafe.go
- pkg/sentry/platform/ring0/entry_arm64.s
On amd64, it uses 'HLT' to leave the guest.
Unlike amd64, arm64 can only uses mmio_exit/psci to leave the guest.
So, I designed the HYPERCALL_VMEXIT to be compatible with amd64/arm64.
To keep it simple, I used the address of exception table as the
MMIO base address, so that I can trigger a MMIO-EXIT by forcibly writing a read-only space.
Then, in host user space, I can calculate this address to find out
which hypercall.
> adding the VM-Exit method for Arm64

- .travis.yml
The travis job has to fail if make smoke-test fails.
Reported-by: @lubinszARM
> travis: set the pipefail option

- test/syscalls/linux/BUILD
- test/syscalls/linux/fpsig_fork.cc
- test/syscalls/linux/fpsig_nested.cc
Some functions were added for Arm64 platform:
a, get_fp/set_fp
b, inline_tgkill
Test step:
bazel test //test/syscalls:fpsig_nested_test_runsc_ptrace
> passed the syscall test case 'fpsig_nested' on Arm64 platform

- pkg/sentry/fs/host/socket.go
When I do high-performance networking,
the value of wmem_max is often set very high,
specially for 10/25/50 Gigabit NIC.
I think maybe this restriction is not suitable.
> Deleting the maxSendBufferSize from fs/host

- pkg/sentry/platform/kvm/bluepill_amd64_unsafe.go
- pkg/sentry/platform/kvm/bluepill_arm64.go
- pkg/sentry/platform/kvm/bluepill_arm64_unsafe.go
- pkg/sentry/platform/kvm/bluepill_unsafe.go
- pkg/sentry/platform/kvm/kvm_arm64.go
- pkg/sentry/platform/kvm/kvm_const.go
- pkg/sentry/platform/kvm/machine_arm64_unsafe.go
There are 3 types of asynchronous exceptions on Arm64: sError, IRQ, FIQ.
In this case, we use the sError injection method in bluepillHandler to force the guest to quit.
So that the test case of "TestBounce" can be passed on Arm64.
> support sError injection in kvm module on Arm64

- test/syscalls/linux/pty.cc
> Add missing ICRNL flag in master termios test

- test/iptables/filter_input.go
- test/iptables/iptables_test.go
- test/iptables/iptables_util.go
- test/iptables/nat.go
Enabling IPv6 in Docker caused IPv4 tests to fail because localAddrs
didn't distinguish between address types. Example failure:
https://source.cloud.google.com/results/invocations/203b2401-3333-4bec-9a56-72cc53d68ddd/log
> ip6tables: handle both IPv4 and v6 addresses

- pkg/sentry/platform/kvm/machine_arm64_unsafe.go
- pkg/sentry/platform/ring0/entry_arm64.s
At present, when doing syscall_kvm test, we need to
enable the function of ESR_ELx_SYS64_ISS_SYS_CTR_READ to
successfully pass the test.
I set SCTLR_EL1.UCT==1, so that the related cases can passed.
> allow guest user applications read ctr_el0 on Arm64

- pkg/sentry/platform/kvm/BUILD
- pkg/sentry/platform/kvm/kvm_amd64_test.go
- pkg/sentry/platform/kvm/kvm_test.go
- pkg/sentry/platform/kvm/testutil/testutil_arm64.s
Split the kvm ut test cases to pass unit-tests on Arm64.
I will add the tls and full-context test cases for Arm64 later.
> Split the kvm ut test cases to correspond to different platforms

- pkg/sentry/socket/hostinet/socket_vfs2.go
When we failed to create the new socket after adding the fd to
fdnotifier, we should remove the fd from fdnotifier, because we
are going to close the fd directly.
Fixes: #3241
> hostinet: fix fd leak in fdnotifier for VFS2

- pkg/sentry/fsimpl/fuse/BUILD
- pkg/sentry/fsimpl/fuse/dev.go
- pkg/sentry/kernel/kernel.go
- pkg/sentry/kernel/syslog.go
- runsc/boot/config.go
- runsc/boot/loader.go
- runsc/boot/vfs.go
- runsc/main.go
- test/runner/defs.bzl
- test/runner/runner.go
- test/syscalls/BUILD
- test/syscalls/linux/dev.cc
- test/util/test_util.cc
- test/util/test_util.h
Resolves https://github.com/google/gvisor/issues/3161.
This change gates all FUSE commands (by gating /dev/fuse) behind a runsc
flag. In order to use FUSE commands, use the --fuse flag with the --vfs2
flag. Check if FUSE is enabled by running dmesg in the sandbox.
Syscall tests that want to use FUSE should specify as such in their build files.
> Gate FUSE behind a runsc flag

- pkg/sentry/fsimpl/devpts/master.go
- pkg/sentry/fsimpl/devpts/slave.go
- pkg/sentry/fsimpl/host/host.go
- pkg/sentry/fsimpl/kernfs/dynamic_bytes_file.go
- pkg/sentry/fsimpl/kernfs/fd_impl_util.go
- pkg/sentry/fsimpl/kernfs/filesystem.go
- pkg/sentry/fsimpl/kernfs/inode_impl_util.go
- pkg/sentry/fsimpl/kernfs/kernfs.go
- pkg/sentry/fsimpl/pipefs/pipefs.go
- pkg/sentry/fsimpl/proc/subtasks.go
- pkg/sentry/fsimpl/proc/task.go
- pkg/sentry/fsimpl/proc/task_files.go
- pkg/sentry/fsimpl/proc/tasks.go
To implement stat(2) in FUSE, we have to embed credentials and pid in request
header. The information should be extracted from the context passed to VFS
layer. Therefore `Stat()` signature in `kernfs.Inode` interface should include
context as first argument. Some other fs implementations need to be modified as
well, such as devpts, host, pipefs, and proc.
Fixes #3235
> Include context in kernfs.Inode.Stat method

- pkg/tcpip/stack/conntrack.go
- pkg/tcpip/stack/iptables.go
- pkg/tcpip/stack/iptables_targets.go
- test/iptables/iptables_test.go
- test/iptables/nat.go
Fixes a NAT bug that manifested as:
- A SYN was sent from gVisor to another host, unaffected by iptables.
- The corresponding SYN/ACK was NATted by a PREROUTING REDIRECT rule
despite being part of the existing connection.
- The socket that sent the SYN never received the SYN/ACK and thus a
connection could not be established.
We handle this (as Linux does) by tracking all connections, inserting a
no-op conntrack rule for new connections with no rules of their own.
Needed for istio support (#170).
> iptables: don't NAT existing connections

- pkg/tcpip/header/icmpv4.go
- pkg/tcpip/header/icmpv6.go
- pkg/tcpip/network/ipv4/icmp.go
- pkg/tcpip/network/ipv6/icmp.go
- pkg/tcpip/stack/registration.go
- pkg/tcpip/transport/tcp/connect.go
- pkg/tcpip/transport/tcp/endpoint.go
- pkg/test/dockerutil/exec.go
- test/packetimpact/runner/packetimpact_test.go
- test/packetimpact/testbench/connections.go
- test/packetimpact/testbench/layers.go
- test/packetimpact/tests/BUILD
- test/packetimpact/tests/tcp_network_unreachable_test.go
Previously, ICMP destination unreachable datagrams were ignored by TCP
endpoints. This caused connect to hang when an intermediate router
couldn't find a route to the host.
This manifested as a Kokoro error when Docker IPv6 was enabled. The Ruby
image test would try to install the sinatra gem and hang indefinitely
attempting to use an IPv6 address.
Fixes #3079.
> make connect(2) fail when dest is unreachable

- pkg/sentry/socket/hostinet/socket.go
Creating sockets by hostinet with VFS2 fails due to triggerring a
seccomp violation. In essence, we fails to pass down the field of
family.
We fix this by passing down this field, family.
Fixes #3141
> hostinet: fix not specifying family field

- test/runner/defs.bzl
Copy the list of tags when passing it to _syscall_test.
This caused `make syscall-native-tests` to run and fail kvm tests.
> Bugfix: non-native tests were tagged as native

- test/iptables/filter_input.go
- test/iptables/iptables_util.go
- test/iptables/nat.go
Sending UDP packets in a loop can be done in a separate goroutine. We
can't do this in ContainerAction because the container will terminate
early.
Locally, scripts/iptables_tests.sh runs ~40 seconds faster.
> Speed up some iptables tests

- pkg/sentry/platform/ring0/entry_arm64.s
At present, when doing syscall_kvm test, we need to
enable the function of ESR_ELx_SYS64_ISS_SYS_CNTVCT/ESR_ELx_SYS64_ISS_SYS_CNTFRQ to
successfully pass the test.
I set CNTKCTL_EL1.EL0VCTEN==1/CNTKCTL_EL1.EL0PCTEN==1, so that the related cases can passed.
> allow guest user applications read CNTVCT_EL0/CNTFRQ_EL0

- benchmarks/workloads/tensorflow/Dockerfile
- images/default/Dockerfile
- tools/vm/ubuntu1604/40_kokoro.sh
Using "--no-cache-dir" flag in pip install ,make sure dowloaded packages
by pip don't cached on system . This is a best practise which make sure
to fetch ftom repo instead of using local cached one . Further , in case
of Docker Containers , by restricing caching , we can reduce image size.
In term of stats , it depends upon the number of python packages
multiplied by their respective size . e.g for heavy packages with a lot
of dependencies it reduce a lot by don't caching pip packages.
Further , more detail information can be found at
https://medium.com/sciforce/strategies-of-docker-images-optimization-2ca9cc5719b6
> optimize size and time using "--no-cache-dir"

- runsc/cgroup/cgroup.go
After deploying a version of gvisor built with Go 1.14, we're seeing errors setting up cgroups (we manually run `runsc` via `runsc run`, which creates the cgroup). This turns out to be a known issue with Go: https://github.com/golang/go/issues/38033. Given that the [fix won't be backported](https://github.com/golang/go/issues/39026#issuecomment-627589315), we should retry writes that may fail with EINTR.
This is also what runc does: https://github.com/opencontainers/runc/pull/2258
> cgroup: retry file writes on EINTR errors

- pkg/abi/linux/fuse.go
- pkg/sentry/fsimpl/fuse/BUILD
- pkg/sentry/fsimpl/fuse/connection.go
- pkg/sentry/fsimpl/fuse/dev.go
- pkg/sentry/fsimpl/fuse/dev_test.go
- pkg/sentry/fsimpl/fuse/fusefs.go
- pkg/sentry/fsimpl/fuse/init.go
- pkg/syserror/syserror.go
This pull request adds the FUSE_INIT to the existing FUSE code: #3097
This change allows the sentry to send FUSE_INIT request and process
the reply. It adds the corresponding structs, employs the fuse
device to send and read the message, and stores the results of negotiation
in corresponding places (inside `connection` struct).
It adds a `CallAsync()` function to the FUSE connection interface:
- like `Call()`, but it's for requests that do not expect immediate response (init, release, interrupt etc.)
- will block if the connection hasn't initialized, which is the same for `Call()`
> fuse: implement the FUSE_INIT command

- pkg/sentry/platform/kvm/kvm_const_arm64.go
- pkg/sentry/platform/kvm/machine_arm64.go
We need to correctly distinguish instruction_abort/data_abort for
mem_abort@Arm64.
So, EC/WNR/FSC in esr_el1 should be checked.
> updated the functions to distinguish IA/DA for Arm64

- pkg/abi/linux/netfilter.go
- pkg/abi/linux/socket.go
- pkg/sentry/socket/netstack/netstack.go
- pkg/sentry/strace/socket.go
- pkg/tcpip/stack/conntrack.go
- pkg/tcpip/stack/iptables.go
- pkg/tcpip/tcpip.go
- pkg/tcpip/transport/tcp/endpoint.go
- test/iptables/BUILD
- test/iptables/iptables_test.go
- test/iptables/iptables_unsafe.go
- test/iptables/iptables_util.go
- test/iptables/nat.go
Envoy (#170) uses this to get the original destination of redirected
packets.
> iptables: support SO_ORIGINAL_DST

- test/syscalls/linux/mount.cc
Before kernel version 4.16-rc6, FUSE mount is protected by `capable(CAP_SYS_ADMIN)`. After this version, it uses `ns_capable(CAP_SYS_ADMIN)` to protect. Before the 4.16 kernel, it was not allowed to mount fuse file systems without the global `CAP_SYS_ADMIN`.
Fixes #3360
> fuse: Fix MountFuseFilesystem tests failing

- pkg/syncevent/waiter_amd64.s
- pkg/syncevent/waiter_arm64.s
- pkg/syncevent/waiter_asm_unsafe.go
- pkg/syncevent/waiter_noasm_unsafe.go
The variable name is g which is collision with the reserved name
for R28. This leads to bazel build failure on ARM with following
information:
(register+register) not supported on this architecture
rename it from g to G
> AARCH64: fix variable name collision with register name

- scripts/fuse_tests.sh
- test/fuse/BUILD
- test/fuse/README.md
- test/fuse/linux/BUILD
- test/fuse/linux/fuse_base.cc
- test/fuse/linux/fuse_base.h
- test/runner/defs.bzl
This commit adds an integration test framework for FUSE support. Please
refer to the test example and test/fuse/README.md for further details.
Fixes #3098
> fuse: add FUSE integration test framework

- test/fuse/linux/fuse_base.cc
The newer version of FUSE_INIT checks the response from the FUSE server if its major number is equal to 7. If it's not, then FUSE_INIT fails and further filesystem operations will get ECONNREFUSED. To mitigate this issue, we can send back a response with major version equals to 7 when consuming the first FUSE_INIT request.
Fixes #3500
> fuse: Fix FUSE integration test failed with ECONNREFUSED

- Makefile
- test/packetimpact/runner/defs.bzl
- test/packetimpact/runner/packetimpact_test.go
- test/packetimpact/testbench/testbench.go
- test/packetimpact/tests/tcp_reordering_test.go
- tools/bazel.mk
This required minor fixes to the bazel wrapper. The "dut_platform" is
also changed to "native" to line-up with the system call tests and
remove the hard-coded "linux" and "netstack" strings.
> Enable "make packetimpact-tests" to work.

- pkg/sentry/platform/kvm/bluepill_arm64.go
- pkg/sentry/platform/kvm/bluepill_arm64_unsafe.go
- pkg/sentry/platform/kvm/machine_arm64_unsafe.go
- pkg/sentry/platform/ring0/aarch64.go
- pkg/sentry/platform/ring0/entry_arm64.s
- pkg/sentry/platform/ring0/kernel_arm64.go
I disabled DAIF(DEBUG, sError, IRQ, FIQ) in guest kernel mode,
and enabled them in guest user mode.
So, I can make sure all DAIF-s come from guest user mode,
and then the case 'TestBounceStress' can passed on Arm64.
Test steps:
1, cd pkg/sentry/platform/kvm
2, bazel test kvm_test --strip=never --test_output=streamed
> supporting sError injection step 2 on Arm64

- tools/go_marshal/marshal/BUILD
- tools/go_marshal/marshal/marshal_impl_util.go
Add a dummy implementation to Marshallable interface, so other structs can embed this implementation and implement their own marshal functions (without adding other marshal interfaces).
> Add stub implementation to marshallable interface

- pkg/abi/linux/fuse.go
- pkg/sentry/fsimpl/fuse/fusefs.go
- test/fuse/BUILD
- test/fuse/linux/BUILD
- test/fuse/linux/fuse_base.cc
- test/fuse/linux/fuse_base.h
- test/fuse/linux/stat_test.cc
- test/runner/defs.bzl
Implement FUSE_GETATTR
FUSE_GETATTR is called when a stat(2), fstat(2), or lstat(2) is issued
from VFS2 layer to a FUSE filesystem.
Fixes #3175
> fuse: implement the FUSE_GETATTR command

- pkg/sentry/arch/arch_aarch64.go
- pkg/sentry/arch/arch_arm64.go
- pkg/sentry/platform/kvm/kvm_const_arm64.go
- pkg/sentry/platform/kvm/machine_arm64_unsafe.go
- pkg/sentry/platform/ring0/entry_arm64.s
- pkg/sentry/platform/ring0/kernel_arm64.go
- pkg/sentry/platform/ring0/pagetables/pagetables_aarch64.go
We can passed 3 things on thunderx2 with this patch:
1, docker run --runtime=runsc-kvm hello-world
2, bazel test kvm_test
3, bazel run kvm_test -- -test.bench=.
Tips:
Currently, there are some small memory with ring0.KernelStartAddress, such as: context pointer.
I set them as strong memory order.
For other addresses with ring0.UserspaceSize, I set them as normal memory.
To-do:
1, flush-dcache-range(), not flush-dcache-all()
2, random issue: bad g in signal handler. When sentry in guest kernel mode, the sentry context should be protected carefully.
3, docker run --runtime=runsc-kvm --rm -it -v $(pwd):/config linuxserver/ffmpeg -i /config/vp92-2-20-10bit-yuv420.webm /config/output.webm
4, extra patches for AMPERE
> Running hello-world on Thunderx2 with kvm

- pkg/seccomp/BUILD
- pkg/seccomp/seccomp_test.go
- pkg/seccomp/seccomp_test_victim.go
- pkg/seccomp/seccomp_test_victim_amd64.go
- pkg/seccomp/seccomp_test_victim_arm64.go
syscalls in ARM64 is different from that in X86_64, use
differen syscallrules for each arch.
The auditnumber are also different for different arch.
Use LINUX_AUDIT_ARCH to get correct auditnumber.
> AARCH64: enable seccomp test on arm64

- pkg/test/testutil/testutil.go
- test/iptables/filter_input.go
- test/iptables/filter_output.go
- test/iptables/iptables.go
- test/iptables/iptables_test.go
- test/iptables/iptables_util.go
- test/iptables/nat.go
- test/iptables/runner/main.go
//test/iptables:iptables_test runs 30 seconds faster on my machine.
* Using contexts instead of many smaller timeouts makes the tests less
likely to flake and removes unnecessary complexity.
* We also use context to properly shut down concurrent goroutines and
the test container.
* Container logs are always logged.
> Speed up iptables tests 

- debian/postinst.sh
In some cases, `systemctl status docker` in the debian package's post install script stucks because of waiting for any inputs to a pager process.
Using systemctl with `--no-pager` resolves this problem, but I think `systemctl is-active` is better in this case.
> [deb package] use "systemctl is-active" instead of "systemctl status"

- pkg/sentry/platform/kvm/virtual_map.go
The device major number may greater than 2 digits in /proc/self/maps on Arm64 N1 machine.
Please see the following as reference:
root@entos-ampere:/tmp/runsc# cat /proc/self/maps 
aaaabc438000-aaaabc440000 r-xp 00000000 103:04 30670923                  /bin/cat
aaaabc44f000-aaaabc450000 r--p 00007000 103:04 30670923                  /bin/cat
aaaabc450000-aaaabc451000 rw-p 00008000 103:04 30670923                  /bin/cat
aaaacc27b000-aaaacc29c000 rw-p 00000000 00:00 0                          [heap]
ffff8ad3b000-ffff8ad5d000 rw-p 00000000 00:00 0 
ffff8ad5d000-ffff8b2cd000 r--p 00000000 103:04 29098157                  /usr/lib/locale/locale-archive
ffff8b2cd000-ffff8b426000 r-xp 00000000 103:04 2884566                   /lib/aarch64-linux-gnu/libc-2.30.so
ffff8b426000-ffff8b436000 ---p …
> Device major number greater than 2 digits in /proc/self/maps on N1

- test/syscalls/linux/symlink.cc
- test/syscalls/linux/write.cc
Added a few tests for write(2) and pwrite(2)
For write(2)
* write zero bytes should not move the offset
* write non-zero bytes should increment the offset the exact amount
* write non-zero bytes after a lseek() should move the offset the exact amount after the seek
* write non-zero bytes with O_APPEND should move the offset the exact amount after original EOF
For pwrite(2), offset is not affected when
* pwrite zero bytes
* pwrite non-zero bytes
Not sure how write(2) interact with EOF
Added a test asserting the EOF (indicated by lseek(SEEK_END)) is updated properly after writing non-zero bytes
Found existing tests in [pipe.cc](https://github.com/google/gvisor/blob/master/test/syscalls/linux/pipe.cc)
Added one pwite64() call for symlink that is written as a counterpart of the existing test …
> Beef up write syscall tests

- pkg/sentry/kernel/kernel.go
The args.MountNamespaceVFS2 is used again after the nil check,
instead, mntnsVFS2 which holds the expected reference should be
used. This patch fixes this issue.
Fixes: #3855
> Fix the use after nil check on args.MountNamespaceVFS2

- .github/workflows/go.yml
We can't actually push the Go branch on pushes to feature branches.
> github: Don't build the Go branch for feature branches

- pkg/sentry/platform/ring0/entry_arm64.s
Some CPUs(eg: ampere-emag) can speculate past an ERET instruction and potentially perform
speculative accesses to memory before processing the exception return.
> arm64:place an SB sequence following an ERET instruction

- pkg/abi/linux/fuse.go
The padding on open out structure is probably lost in rebasing and merging, this fixes the issue.
> fuse: add padding to fuse open out request structure

- pkg/sentry/platform/kvm/machine_arm64_unsafe.go
- pkg/sentry/platform/ring0/defs_arm64.go
- pkg/sentry/platform/ring0/entry_arm64.s
- pkg/sentry/platform/ring0/kernel_arm64.go
- pkg/sentry/platform/ring0/lib_arm64.go
- pkg/sentry/platform/ring0/lib_arm64.s
- pkg/sentry/platform/ring0/offsets_arm64.go
Some optimizations in this pr:
1, Move ASID from TTBR0 to TTBR1
2, tlb_flush_all
To-do: implementations for 
__tlbi(aside1is, asid)
__tlbi_user(aside1is, asid)
> arm64 mm: asid and tlb support

- pkg/sentry/fsimpl/kernfs/filesystem.go
- test/fuse/linux/rmdir_test.cc
- test/fuse/linux/unlink_test.cc
The current name used as the argument for unlinkat and rmdirat is incorrect. They should be the name of the file after path resolve
> Fix kernfs unlinkat and rmdirat incorrect resolved path name

- pkg/sentry/fsimpl/devpts/devpts.go
- pkg/sentry/fsimpl/eventfd/eventfd.go
- pkg/sentry/fsimpl/ext/filesystem.go
- pkg/sentry/fsimpl/ext/symlink.go
- pkg/sentry/fsimpl/fuse/directory.go
- pkg/sentry/fsimpl/fuse/fusefs.go
- pkg/sentry/fsimpl/gofer/filesystem.go
- pkg/sentry/fsimpl/host/host.go
- pkg/sentry/fsimpl/host/tty.go
- pkg/sentry/fsimpl/kernfs/filesystem.go
- pkg/sentry/fsimpl/kernfs/inode_impl_util.go
- pkg/sentry/fsimpl/kernfs/symlink.go
- pkg/sentry/fsimpl/proc/subtasks.go
- pkg/sentry/fsimpl/proc/task.go
- pkg/sentry/fsimpl/proc/task_fds.go
- pkg/sentry/fsimpl/proc/task_files.go
- pkg/sentry/fsimpl/proc/task_net.go
- pkg/sentry/fsimpl/proc/tasks.go
- pkg/sentry/fsimpl/proc/tasks_files.go
- pkg/sentry/fsimpl/proc/tasks_sys.go
- pkg/sentry/fsimpl/signalfd/signalfd.go
- pkg/sentry/fsimpl/sockfs/sockfs.go
- pkg/sentry/fsimpl/timerfd/timerfd.go
- pkg/sentry/fsimpl/tmpfs/filesystem.go
- pkg/sentry/fsimpl/verity/filesystem.go
As noticed by @ayushr2, the "implements" comments are not
consistent, e.g.
// IterDirents implements kernfs.inodeDynamicLookup.
// Generate implements vfs.DynamicBytesSource.Generate.
This patch improves this by making the comments like this
consistently include the package name (when the interface
and struct are not in the same package) and method name.
> fsimpl: improve the "implements" comments

- tools/bazel.mk
In travis, if we don't specify /dev/null, tail exits immediately, then its parent process
which is the init process exits too and kills the bazel server.
> make: specify /dev/null for the tail tool

- runsc/container/container_test.go
- runsc/specutils/seccomp/seccomp_test.go
Fix errors for unit test on ARM64
1. seccomp test
2. TestUserLog
> Fix errors for unit test on ARM64

- pkg/sentry/kernel/BUILD
- pkg/sentry/kernel/kernel.go
- pkg/sentry/socket/hostinet/socket_vfs2.go
- pkg/sentry/socket/netlink/socket_vfs2.go
- pkg/sentry/socket/netstack/netstack_vfs2.go
- pkg/sentry/socket/unix/BUILD
- pkg/sentry/socket/unix/unix.go
- pkg/sentry/socket/unix/unix_vfs2.go
VFS2 socket record is not removed from the system-wide
socket table when the socket is released, which will lead
to a memory leak. This patch fixes this issue.
Fixes: #3874
> Fix socket record leak in VFS2

- pkg/sentry/platform/kvm/bluepill_amd64.s
- pkg/sentry/platform/kvm/kvm.go
- pkg/sentry/platform/kvm/machine.go
- pkg/sentry/platform/kvm/machine_amd64.go
- pkg/sentry/platform/kvm/machine_arm64.go
- pkg/sentry/platform/ring0/defs_amd64.go
- pkg/sentry/platform/ring0/entry_amd64.go
- pkg/sentry/platform/ring0/entry_amd64.s
- pkg/sentry/platform/ring0/kernel.go
- pkg/sentry/platform/ring0/kernel_amd64.go
- pkg/sentry/platform/ring0/kernel_arm64.go
- pkg/sentry/platform/ring0/lib_amd64.go
- pkg/sentry/platform/ring0/lib_amd64.s
- pkg/sentry/platform/ring0/offsets_amd64.go
- pkg/sentry/platform/ring0/x86.go
GVisor has separated page tables between gr0 and gr3.
But the upper half of the userCR3 contains the whole sentry
kernel which makes the kernel vulnerable to gr3 APP
through CPU bugs.
This patch implement full KPTI functionality for gvisor. It doesn't
map the whole kernel in the upper. It maps only the text section
of the binary and the entry area required by the ISA. The entry area
contains the global idt, the percpu gdt/tss etc. The entry area
packs all these together which is less than 350k for 512 vCPUs.
The text section is normally nonsensitive. It is possible to
map only the entry functions (interrupt handler etc.) only.
But it requires some hacks.
The pull request (patchset) uses 3 patches to narrow accessing
from the upper half including instruction fetching and data accessing. …
> implement KPTI for gvisor

- pkg/sentry/fsimpl/host/socket.go
FD notifier should be removed before we close the FD,
otherwise there will be race condition that another FD
which has the same value is opened and added before the
existing FD notifier is removed.
Fixes: #3823
> fsimpl/host: fix the order of removing FD notifier

- pkg/sentry/platform/kvm/bluepill_amd64_unsafe.go
- pkg/sentry/platform/kvm/kvm_const.go
- pkg/sentry/platform/kvm/machine_amd64.go
- pkg/sentry/platform/kvm/machine_amd64_unsafe.go
- pkg/sentry/platform/ring0/entry_amd64.s
- pkg/sentry/platform/ring0/offsets_amd64.go
- pkg/sentry/platform/ring0/x86.go
- tools/checkescape/checkescape.go
Before we thought that interrupts are always disabled in the kernel
space, but here is a case when goruntime switches on a goroutine which
has been saved in the host mode. On restore, the popf instruction is
used to restore flags and this means that all flags what the goroutine
has in the host mode will be restored in the kernel mode. And in the
host mode, interrupts are always enabled.
The long story short, we can't use the IF flag to determine whether a
tasks is running in user or kernel mode.
This patch reworks the code so that in userspace, the first bit of the
IOPL flag will be always set. This doesn't give any new privileges for
a task because CPL in userspace is always 3. But then we can use this
flag to distinguish user and kernel modes. The IOPL flag is never set in
the kernel …
> kvm/x86: handle a case when interrupts are enabled in the kernel space

- runsc/boot/loader.go
With cgroups configured NumCPU is correct, however GOMAXPROCS is still derived from total host core count and ignores cgroup restrictions. This can lead to different and undesired behavior across different hosts.
For example, the total number of threads in the guest process will be larger on machines with more cores.
This change configures the go runtime for the sandbox to only use the number of threads consistent with its restrictions.
> Use consistent thread configuration for sandbox go runtime

- pkg/sentry/platform/ring0/entry_arm64.s
@lubinszARM 
The patch has been test based on our own codebase, I have not test it on KVM, since our kernel is 4.19 (KVM has some issue on this kernel for gvisor). But I think it also works on KVM, without this patch the sentry will hang randomly on our ARM64 platform. I see currently the ASID is changed to TTBR1_EL1, with this patches, I think the ASID can still in TTBR0_EL1 and the kernel address space can be mapped as global.
> arm64: fix tlb and memory map issue

- g3doc/user_guide/networking.md
Removing the link to the netstack repo as the netstack code is now part of gVisor.
> Networking.md: removing stale link to netstack repo

- pkg/sentry/platform/kvm/machine.go
- pkg/sentry/platform/kvm/machine_amd64.go
- pkg/sentry/platform/kvm/machine_arm64.go
Related with issue #3019 #4056.
When running hello-world with gvisor-kvm, there is panic when exits:
"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x3c0 pc=0x7c3f18]
goroutine 284 [running]:
... ...
gvisor.dev/gvisor/pkg/sentry/platform/kvm.(*machine).dropPageTables(0x4000166840, 0x400032a040)
pkg/sentry/platform/kvm/machine_arm64.go:111 +0x88 fp=0x4000479e00 sp=0x4000479da0 pc=0x7c3f18
"
Also make dropPageTables() arch independent.
> arm64 kvm: fix panic in kvm.dropPageTables

- pkg/sentry/platform/ring0/entry_arm64.s
This patch removed some redundant codes to improve the preformance.
I have checked this PR with ffmpeg-testing/unit-test/syscall-kvm-test, no issue was found.
> arm64 kvm: remove some redundant codes to improve the preformance

- pkg/sentry/platform/kvm/BUILD
- pkg/sentry/platform/kvm/kvm_arm64_test.go
- pkg/sentry/platform/kvm/testutil/testutil_arm64.go
- pkg/sentry/platform/kvm/testutil/testutil_arm64.s
The tls of guest-el1-sentry and host-el0-sentry may be different on Arm64.
I added a test case for it.
> arm64 kvm: add a test case for kernel-tls-preservation checking

- pkg/sentry/platform/ring0/entry_arm64.s
Some application (like java) may need DC ZVA.
```
root@i85b08054:~/work/gvisor# pouch run --runtime=runsc -it --net=none arm64v8/openjdk:latest
OpenJDK 64-Bit Server VM warning: DC ZVA is not available on this CPU
Oct 10, 2020 8:48:33 AM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
|  Welcome to JShell -- Version 11.0.2
|  For an introduction type: /help intro
jshell> 
```
With this patch
```
root@i85b08054:~/work/gvisor# pouch run --runtime=runsc -it --net=none arm64v8/openjdk:latest
Oct 10, 2020 8:54:17 AM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
|  Welcome to JShell -- Version 11.0.2
|  For an introduction type: /help intro
jshell> 
```
> arm64: enable DZE bit in SCTLR to make EL0 can use DC ZVA

- test/runner/defs.bzl
Currently strace+debug is always enabled as the setting from
the upper layer isn't passed to _syscall_test(). And it will
negatively affect the performance tests. This patch fixes this
issue.
The "debug" argument of _syscall_test() is also made mandatory
to prevent this happening again.
Fixes #4509
> Disable strace+debug when explicitly requested

- pkg/sentry/platform/kvm/machine_arm64_unsafe.go
- pkg/sentry/platform/ring0/entry_arm64.s
Consistent with the linux approach, we will produce a sigill to handle
el0_undef.
After applying this patch, exec_binary_test_runsc_kvm will be passed on
Arm64.
> arm64 kvm: handle exception from accessing undefined instruction

- runsc/container/container.go
Useful when you want to run multiple containers with the same config.
And runc does that too.
> Use container ID as cgroup name if not provided

- runsc/boot/fs.go
- runsc/specutils/specutils.go
This is useful to optionally set /dev ro,noexec.
Treat /dev and /dev/pts the same as /proc and /sys.
Make sure the Type is right though. Many config.json snippets
on the Internet suggest /dev is tmpfs, not devtmpfs.
> Allow overriding mount options for /dev and /dev/pts

- runsc/cmd/boot.go
- runsc/config/config.go
- runsc/config/flags.go
Sometimes we run into an issue in gVisor (or gets killed because of OOM or something) while having tons of goroutines. When gVisor gets killed in these cases, it prints huge amounts of Goroutine traces (more than 10K lines), but it does forbid us to change the traceback level to something lower than `system`.
I propose to add a debugging flag `--traceback` that sets the value used for the `SetTraceback` call in `runsc/cmd/boot.go`.
> Add --traceback flag to customize debug.SetTraceback level

- test/util/signal_util.h
Currently, this Fault() function does not work properly on the arm platform.
After modification, sigaltstack_test_runsc_kvm can be passed on
Arm64.
> arm64 test: enabled Fault() function

- test/syscalls/linux/mmap.cc
There is a new random issue on some Arm64 machines.
This scene can be summarized as following:
sometimes, the content pointed to by the function pointer is still 0 opcode, then sigill was generated.
The probability of this kind of issue is very low,
currently only available on some machines.
After inserting a simple memory barrier, this issue was gone.
The code to directly use the memory barrier is as follows:
memcpy(reinterpret_cast<void*>(addr), machine_code, sizeof(machine_code));
############MEMORY BARRIER#######
isb()
#################################
func = reinterpret_cast<uint32_t (*)(void)>(addr);
> avoid the random memory barrier issue in mmap testing on Arm64

- pkg/sentry/platform/kvm/machine_arm64_unsafe.go
Consistent with the linux kernel, bad regs.Sp
return SIGSEGV
> ARM64 KVM: bad regs.Sp return SIGSEGV

- pkg/sentry/platform/kvm/kvm.go
- pkg/sentry/platform/kvm/machine.go
- pkg/sentry/platform/kvm/machine_amd64.go
- pkg/sentry/platform/ring0/defs.go
- pkg/sentry/platform/ring0/defs_amd64.go
- pkg/sentry/platform/ring0/defs_arm64.go
- pkg/sentry/platform/ring0/kernel.go
- pkg/sentry/platform/ring0/kernel_amd64.go
- pkg/sentry/platform/ring0/kernel_arm64.go
- pkg/sentry/platform/ring0/pagetables/pagetables.go
- pkg/sentry/platform/ring0/pagetables/pagetables_aarch64.go
- pkg/sentry/platform/ring0/pagetables/pagetables_amd64.go
- pkg/sentry/platform/ring0/pagetables/pagetables_arm64.go
- pkg/sentry/platform/ring0/pagetables/walker_arm64.go
> kvm: share upper halves among all pagtables

- test/fuse/linux/stat_test.cc
fields order in stat struct is different from
x86 to arm64. Please refer to
x86_64-linux-gnu/bits/stat.h
aarch64-linux-gnu/bits/stat.h
> ARM64:fuse:alian stat struct order on multiarch

- pkg/sentry/platform/ring0/lib_arm64.s
current when save and restore fpsmid register is using following
instruction:
this instruction will compiled to:
D0 is a 64bit register not 128bit, then upper 64bit data
are loss, which will cause application meet many random
crash issue. need use 128bit register v0 or q0 to save
the fpsmid context.
seems golang do not support fpsmid well for arrch64, I do not find related instruction to do this work, so use WORD instead.
> arm64: fix the fpsmid context save/restore issue

- pkg/sentry/platform/kvm/machine_arm64_unsafe.go
- pkg/sentry/platform/ring0/aarch64.go
- pkg/sentry/platform/ring0/entry_arm64.s
- pkg/sentry/platform/ring0/kernel_arm64.go
- pkg/sentry/platform/ring0/offsets_arm64.go
I added 2 unified processing functions for all exceptions of el/el0
Test cases on Arm64:
> arm64 kvm: add the processing functions for all el0/el1 exceptions

- pkg/sentry/platform/ring0/pagetables/pagetables.go
- pkg/sentry/platform/ring0/pagetables/pagetables_aarch64.go
- pkg/sentry/platform/ring0/pagetables/pagetables_amd64.go
- pkg/sentry/platform/ring0/pagetables/pagetables_arm64.go
- pkg/sentry/platform/ring0/pagetables/walker_arm64.go
After applying pr https://github.com/google/gvisor/pull/3617. Both ut & syscall-kvm-test failed on Arm64.
The root cause is that upperSharedPageTables is still a null pointer when doing the walker.
Tests:
Signed-off-by: Robin Luk <lubin.lu@alibaba-inc.com>
> arm64 kvm: pagetables_test & kvm_test failed due to upperSharedPt feature

- test/syscalls/linux/BUILD
- test/syscalls/linux/exceptions.cc
For now, I only added a halt test case for Arm64.
> arm64 test: add exceptions related test cases

- pkg/sentry/platform/kvm/bluepill_amd64_unsafe.go
- pkg/sentry/platform/kvm/bluepill_arm64.go
- pkg/sentry/platform/kvm/bluepill_arm64_unsafe.go
- pkg/sentry/platform/kvm/bluepill_unsafe.go
- pkg/sentry/platform/kvm/kvm_arm64.go
- pkg/sentry/platform/kvm/kvm_const.go
If no vild syndrome(data abort outside memslots) was reported by kvm, let userspace to do the
ext_dabt injection to bail out this issue.
After applying this patch, all the random failure test cases (in general, 10~30+) disappeared in kvm_syscall_test.
Related issue https://github.com/google/gvisor/issues/4642
> arm64 kvm: add to ext_dabt injection support

- pkg/sentry/platform/ring0/kernel_arm64.go
- pkg/sentry/platform/ring0/lib_arm64.go
- pkg/sentry/platform/ring0/lib_arm64.s
This patch adds support for tlbi-vale1ls/tlbi-aside1ls.
And make the code consistent with the flush strategy of the x86 platform.
> arm64 tlb: add support for tlbi-vale1ls/tlbi-aside1ls

- test/syscalls/linux/pipe.cc
- test/syscalls/linux/proc_net.cc
- test/syscalls/linux/proc_net_unix.cc
- test/syscalls/linux/proc_pid_uid_gid_map.cc
- test/syscalls/linux/semaphore.cc
- test/syscalls/linux/socket.cc
- test/syscalls/linux/socket_bind_to_device_distribution.cc
- test/syscalls/linux/socket_ip_udp_generic.cc
- test/syscalls/linux/socket_ipv4_udp_unbound_netlink.cc
- test/syscalls/linux/tuntap.cc
The buildkite syscall tests start with a lot of C++ warnings. This
cleans that up a little.
> Resolve compiler warnings

- website/cmd/server/main.go
Add redirects from any module package path to its corressponding
pkg.go.dev documentation. e.g., gvisor.dev/gvisor/pkg/sentry/kernel ->
https://pkg.go.dev/gvisor.dev/gvisor/pkg/sentry/kernel.
This is a handy way to get to documentation, also used by other vanity
domains, like golang.org/x/tools.
> website: redirect module to pkg.go.dev

- pkg/sentry/platform/kvm/kvm_test.go
According to my understanding, if we call the bluepill() of different vcpus in turn, the previous vcpu will exit due to the redpill() in the next bluepill().
Signed-off-by: Robin Luk <lubin.lu@alibaba-inc.com>
> kvm-test: adjust the check logic in TestWrongVCPU case

- pkg/shim/runsc/runsc.go
- pkg/shim/service.go
Happy to add tests if necessary (not sure where those would go at this point).
Tested by `ctr t pause` and `ctr t resume`-ing a container.
This seems to be necessary to implement checkpoint/restore for containerd (containerd calls pause before checkpointing, then resumes it -- even though that's not strictly necessary for gVisor).
> Add support for pause/resume in containerd shim

- runsc/cgroup/cgroup.go
- runsc/cgroup/cgroup_test.go
in nested container, we see paths from host in /proc/self/cgroup, so we
need to re-process that path to get a relative path to be used inside
the container.
Without it, runsc generates ugly paths that may trip other cgroup
watchers that expect clean paths. An example of ugly path is:
```
/sys/fs/cgroup/memory/docker/e383892b29290ae8005d535f2dadc4a583bb354d5bb1ba8c10bf900d92c4db93/docker/e383892b29290ae8005d535f2dadc4a583bb354d5bb1ba8c10bf900d92c4db93/cgroupPath
```
Notice duplication of `docker/e383892b29290ae8005d535f2dadc4a583bb354d5bb1ba8c10bf900d92c4db93`
`/proc/1/cgroup` looks like
```
12:perf_event:/docker/e383892b29290ae8005d535f2dadc4a583bb354d5bb1ba8c10bf900d92c4db93
11:blkio:/docker/e383892b29290ae8005d535f2dadc4a583bb354d5bb1ba8c10bf900d92c4db93 …
```
> runsc: check for nested cgroup when generating croup paths

- g3doc/user_guide/FAQ.md
The current version of FAQ.md contains an incorrect example of how to instruct kubelet to prefer containerd over docker. More specifically, it refers to a non-existent `--cni-socket` flag whereas it should have been `--cri-socket`.
The suggested PR fixes that.
> FAQ.md: fix kubeadm init instructions

- pkg/ring0/defs_arm64.go
- pkg/ring0/entry_arm64.s
- pkg/ring0/kernel_arm64.go
- pkg/ring0/lib_arm64.go
- pkg/ring0/offsets_arm64.go
- pkg/sentry/arch/signal_arm64.go
- pkg/sentry/platform/kvm/bluepill_arm64.go
- pkg/sentry/platform/kvm/machine_arm64_unsafe.go
There are several modifications to this patch.
1, lazy-usr-fpsimd:  implement basic lazy save and restore for FPSIMD registers, which only
restore FPSIMD state on el0_fpsimd_acc and save FPSIMD state in switch().
2, use STP instead of MOVD in ring0 module.
3, slightly cleaned up the arch module: no red zone on Arm64.
After applying this patch, the data of "BenchmarkWorldSwitchToUserRoundtrip-128" is reduced by 15%.
> arm64 kvm: implement basic lazy save and restore for FPSIMD registers

- pkg/sentry/control/proc.go
- runsc/container/multi_container_test.go
`runsc ps` currently return pid for a task's immediate pid namespace,
which is confusing when there're multiple pid namespaces. We should
return only pids in the root namespace.
Before:
```
1000      1         0         0         ?         02:24     250ms     chrome
1000      1         0         0         ?         02:24     40ms      dumb-init
1000      1         0         0         ?         02:24     240ms     chrome
1000      2         1         0         ?         02:24     2.78s     node
```
After:
```
UID       PID       PPID      C         TTY       STIME     TIME      CMD
1000      1         0         0         ?         12:35     0s        dumb-init
1000      2         1         7         ?         12:35     240ms     node
1000      13        2         21        ?         12:35 …
```
> return root pids with runsc ps

- .github/workflows/build.yml
- .github/workflows/go.yml
👋 hello there! I'm a fellow Googler who works on projects that leverage GitHub Actions for CI/CD. Recently I noticed a large increase in our queue time, and I've tracked it down to the [limit of 180 concurrent jobs](https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration) for an organization. To help be better citizens, I'm proposing changes across a few repositories that will reduce GitHub Actions hours and consumption. I hope these changes are reasonable and I'm happy to talk through them in more detail.
- (**you were already doing this, thank you!**) Only run GitHub Actions for pushes and PRs against the main branch of the repository. If your team uses a forking model, this change will not affect you. If your team pushes branches to the repository directly, …
> Improve Actions hygiene

- tools/make_apt.sh
We can generate more than one apt repo for the same package.  If we will
sign a package again, its file will be changed and all hashes that have
been generated before will be invalid.
> make/release: Sign a package only once

- pkg/ring0/defs.go
- pkg/ring0/kernel_amd64.go
- pkg/ring0/kernel_arm64.go
- pkg/sentry/arch/arch.go
- pkg/sentry/arch/arch_aarch64.go
- pkg/sentry/arch/arch_x86.go
- pkg/sentry/platform/kvm/bluepill_amd64.go
- pkg/sentry/platform/kvm/bluepill_arm64.go
- pkg/sentry/platform/kvm/context.go
- pkg/sentry/platform/kvm/machine_amd64.go
- pkg/sentry/platform/kvm/machine_arm64.go
- pkg/sentry/platform/ptrace/ptrace_unsafe.go
If physical pages of a memory region are not mapped yet, the kernel will
trigger KVM_EXIT_MMIO and we will map physical pages in bluepillHandler().
An instruction that triggered a fault will not be re-executed, it
will be emulated in the kernel, but it can't  emulate complex
instructions like xsave, xrstor. We can touch the memory with
simple instructions to workaround this problem.
Fixes: #5591
> kvm: prefault a floating point state before restoring it

- pkg/ring0/kernel_arm64.go
- pkg/ring0/lib_arm64.go
- pkg/ring0/lib_arm64.s
- pkg/sentry/platform/kvm/machine_arm64.go
It is enough to invalidate the tlb of local vcpu in switch().
TLBI with inner-sharable will invalidate the tlb in other vcpu.
Arm64 hardware supports at least 256 pcid, so I think it's ok
to set the length of pcid pool to 128.
> arm64 ring0: don't use inner-sharable to invalidate tlb

- pkg/ring0/kernel_amd64.go
- pkg/ring0/lib_amd64.go
- pkg/ring0/lib_amd64.s
- pkg/sentry/arch/fpu/fpu_amd64.go
- pkg/sentry/platform/kvm/BUILD
- pkg/sentry/platform/kvm/kvm_amd64_test.go
- pkg/sentry/platform/kvm/kvm_amd64_test.s
Goruntime sets mxcsr once and never changes it.
Reported-by: syzbot+ec55cea6e57ec083b7a6@syzkaller.appspotmail.com
Fixes: #5754
> platform/kvm/x86: restore mxcsr when switching from guest to sentry

- pkg/sentry/platform/kvm/kvm_const.go
- pkg/sentry/platform/kvm/machine.go
- pkg/sentry/platform/kvm/machine_amd64.go
If the host doesn't have TSC scaling feature, then scaling down TSC to
the lowest value will fail, and we will fall back to legacy logic
anyway, but we leave an ugly log message in host's kernel log.
kernel: user requested TSC rate below hardware speed
Instead, check for KVM_CAP_TSC_CONTROL when initializing KVM, and fall
back to legacy logic early if host's cpu doesn't support that.
Signed-off-by: Daniel Dao <dqminh89@gmail.com>
> Fallback to legacy system time logic when host does not have TSC_CONTROL

- pkg/safecopy/atomic_amd64.s
- pkg/safecopy/atomic_arm64.s
- pkg/safecopy/memcpy_amd64.s
- pkg/safecopy/memcpy_arm64.s
Fix typo of arg name on assembly files.
In the `safecopy` package, wrong arg name on assembler files. actually `ptr` but documentation and assembly code both of `addr`.
> Fix typo of arg name on assembly files in the safecopy package

- pkg/sentry/platform/kvm/machine.go
- pkg/sentry/platform/kvm/machine_amd64.go
- pkg/sentry/platform/kvm/machine_arm64.go
- pkg/sentry/platform/kvm/machine_arm64_unsafe.go
- runsc/boot/loader.go
This patch is to solve problem that vCPU timer mess up when
adding vCPU dynamically on ARM64, for detailed information
please refer to:
https://github.com/google/gvisor/issues/5739
There is no influence on x86 and here are main changes for
ARM64:
1. create maxVCPUs number of vCPU in machine initialization
2. we want to sync gvisor vCPU number with host CPU number,
so use smaller number between runtime.NumCPU and
KVM_CAP_MAX_VCPUS to be maxVCPUS
3. put unused vCPUs into architecture-specific map initialvCPUs
4. When machine need to bind a new vCPU with tid, rather
than creating new one, it would pick a vCPU from map initalvCPUs
5. change the setSystemTime function. When vCPU number increasing,
the time cost for function setTSC(use syscall to set cntvoff) is
liner growth from around 300 ns …
> Init all vCPU when initializing machine on ARM64

- runsc/cmd/mitigate.go
- runsc/cmd/mitigate_test.go
- runsc/mitigate/mitigate_test.go
As MDS side channel attack does not affect ARM64, we disable
mitigate on ARM64 in case misusage.
For more detail, please refer to:
https://access.redhat.com/security/vulnerabilities/mds
> Disable mitigate and related test on ARM64

- pkg/atomicbitops/aligned_32bit_unsafe.go
- pkg/atomicbitops/aligned_64bit.go
N.B. we don't explicitly support MIPS, but there's no reason it
shouldn't work.
> enable building //pkg/tcpip on 32-bit MIPS

- runsc/fsgofer/fsgofer.go
We need to make sure that all children are closed before
return. But the last child saved in parent isn't closed
after we successfully iterate all the files in "names".
This patch fixes this issue.
Fixes #5982
Signed-off-by: Tiwei Bie <tiwei.btw@antgroup.com>
> Fix file descriptor leak in MultiGetAttr

- test/syscalls/linux/BUILD
- test/syscalls/linux/pty.cc
The test Truncate set ControllingTTY without releasing
it. This leads to test ReleaseTTYSignals and ReleaseTTY fails
when setting ControllingTTY.
> fix pty_test error by releasing tty received from test

- pkg/sync/README.md
Fix typo of `Syncutil` to `sync` on `sync` packages README.
I assume `Syncutil` is an old name, just fix it to the correct package name.
> Fix typo of Syncutil to sync on sync packages README

- pkg/abi/linux/ioctl_tun.go
- pkg/sentry/socket/netstack/tun.go
Before this fix usage of this flag returns an error.
It affects applications like OpenVPN which sets this flag for legacy reasons. 
According to linux/if_tun.h:
```
/* This flag has no real effect */
#define IFF_ONE_QUEUE	0x2000
```
> Allow use of IFF_ONE_QUEUE

- pkg/sentry/platform/kvm/BUILD
- pkg/sentry/platform/kvm/address_space.go
- pkg/sentry/platform/kvm/address_space_amd64.go
- pkg/sentry/platform/kvm/address_space_arm64.go
on Arm64 platform, we can use TLBI with 'IS' instead of IPI operation.
According to my understanding, the logic in invalidate() is much like
an IPI operation.
On Arm64, we can simply perform vmalle1is invalidation here, not
use IPI.
Reference:
https://github.com/torvalds/linux/blob/v5.12/arch/arm64/kvm/mmu.c#L81
> arm64 kvm:use TLBI with "Inner Shareable" instead of IPI operation

- WORKSPACE
When trying to compile the a syscall test using gcc 11, I get this error:
```
bazel test //test/syscalls:exit_test_native
INFO: Analyzed target //test/syscalls:exit_test_native (18 packages loaded, 3659 targets configured).
INFO: Found 1 test target...
ERROR: /home/esteban/.cache/bazel/_bazel_esteban/c255f9c894dd2f447ce001dac56022de/external/com_google_absl/absl/synchronization/BUILD.bazel:30:11: Compiling absl/synchronization/internal/graphcycles.cc failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF ... (remaining 32 argument(s) skipped)
Use --sandbox_debug to see verbose messages from the sandbox gcc failed: error executing command …
```
> Update abseil dependency

- pkg/sentry/kernel/semaphore/semaphore.go
- test/syscalls/linux/semaphore.cc
semget(2) man page specifies that ENOSPC should be used if "the system
limit for the maximum number of semaphore sets (SEMMNI), or the system
wide maximum number of semaphores (SEMMNS), would be exceeded."
> Use syserror.ENOSPC for system-wide semaphore limits.

- pkg/sentry/time/BUILD
- pkg/sentry/time/sampler.go
- pkg/sentry/time/sampler_amd64.go
- pkg/sentry/time/sampler_arm64.go
Usually ARM counter-timer frequency is range from 1-50Mhz which is
much less than that on x86, so we calibrate defaultOverheadCycles
for ARM.
Signed-off-by: howard zhang <howard.zhang@arm.com>
> calibrate defaultOverheadCycles for ARM64

- pkg/sentry/platform/kvm/bluepill_arm64.go
- pkg/sentry/platform/kvm/bluepill_arm64_unsafe.go
- pkg/sentry/platform/kvm/machine_arm64_unsafe.go
In the event injecting functions, the heap-allocate method should be avoided to reduce the pressure of gc.
>  Fix errors for noescape cases

- pkg/shim/BUILD
- pkg/shim/errors.go
- pkg/shim/errors_test.go
- pkg/shim/proc/exec_state.go
- pkg/shim/service.go
See #6225 for more details.
This pair of changes adds a wrapper around containerd's `errdefs.ToGRPC` function to support Go 1.13's new error wrapping style instead of using `github.com/pkg/errors` and sends signals for stopped exec-processes to a no-op handler, just like for the init-process.
Fixes #6225.
> Fix shim PID leaking on stopped processes

- pkg/control/server/server.go
- pkg/urpc/urpc.go
- runsc/boot/controller.go
- runsc/boot/loader.go
- runsc/sandbox/sandbox.go
The typical sequence of calls to start a container looks like this
ct, err := container.New(conf, containerArgs)
defer ct.Destroy()
ct.Start(conf)
ws, err := ct.Wait()
For the root container, ct.Destroy() kills the sandbox process. This
doesn't look like a right wait to stop it. For example, all ongoing rpc
calls are aborted in this case. If everything is going alright, we can
just wait and it will exit itself.
Reported-by: syzbot+084fca334720887441e7@syzkaller.appspotmail.com
> runsc: don't kill sandbox, let it stop properly

- pkg/tcpip/link/tun/device.go
- test/syscalls/linux/tuntap.cc
When TUN is created with IFF_NO_PI flag, there will be no Ethernet header and no packet info, therefore, both read and write will fail. 
This commit fix this bug.
> Fix TUN IFF_NO_PI bug

- pkg/sentry/socket/netfilter/ipv4.go
- pkg/sentry/socket/netfilter/ipv6.go
In Linux, iptables list entries command returns the name of the input interface assigned to the iptable rule.
```
-A FORWARD -i docker0 -o docker0 -j ACCEPT
```
Meanwhile, in gVsior this interface name is ignored.
```
-A FORWARD -o docker0 -j ACCEPT
```
> Fix iptables List entries Input interface field

- pkg/sentry/platform/kvm/bluepill_amd64.s
When sentry is running in guest ring0, the goroutine stack is changing
and it will not be the stack when bluepill() is called.
If PMU interrupt hits when the CPU is in host ring 0, the perf handler
will try to get the stack of the kernel and the userspace(sentry).  It
can travel back to sighandler() and try to continue to the stack of
the goroutine with the outdated frame pointer if sentry has been running
in the guest.  The perf handler can't record correct addresses
from the outdated and wrong frames.  Those addresses are often
irresolvable, and even if it is resolvable accidentally, it would
be misleading names.
To fix the problem, we just set the frame pointer(%RBP) to zero and
disconnect the link when the zeroed frame pointer is saved in the
frame in bluepillHandler().
Signed-off-by: …
> Disconnect call-chain between sighandler() and bluepill().

- pkg/abi/linux/BUILD
- pkg/abi/linux/msgqueue.go
- pkg/sentry/kernel/BUILD
- pkg/sentry/kernel/ipc/BUILD
- pkg/sentry/kernel/ipc/object.go
- pkg/sentry/kernel/ipc/registry.go
- pkg/sentry/kernel/ipc_namespace.go
- pkg/sentry/kernel/msgqueue/BUILD
- pkg/sentry/kernel/msgqueue/msgqueue.go
- pkg/sentry/kernel/semaphore/BUILD
- pkg/sentry/kernel/semaphore/semaphore.go
- pkg/sentry/kernel/semaphore/semaphore_test.go
- pkg/sentry/kernel/shm/BUILD
- pkg/sentry/kernel/shm/shm.go
- pkg/sentry/syscalls/linux/BUILD
- pkg/sentry/syscalls/linux/linux64.go
- pkg/sentry/syscalls/linux/sys_msgqueue.go
- pkg/sentry/syscalls/linux/sys_sem.go
- pkg/sentry/syscalls/linux/sys_shm.go
- test/syscalls/BUILD
- test/syscalls/linux/BUILD
- test/syscalls/linux/msgqueue.cc
This implements msgget(2), and the IPC_RMID option for msgctl(2). With this we support creation and deletion of sysv message queues, hopefully to be followed by msgsnd, msgrcv, and msgctl's other options.
The PR is separated into several commits, so I think it'll be easier to review one commit at a time, instead of reviewing it as one whole change.
~Also, the commits in this PR use `ipcutil` which is implemented in #6097. The commit is included here until the PR is reviewed and hopefully merged. When #6097 is merged I'll drop the commit from here and rebase the branch over master.~
#6079 was closed, with `ipc`-related changes included here.
Updates #135
> Implement msgget(2) and msgctl(IPC_RMID)

- runsc/cmd/chroot.go
- runsc/cmd/gofer.go
This patch fixes the local timezone support in logs by creating
etc/localtime in the rootfs of sandbox process and gofer process
based on the current /etc/localtime on host.
Before this patch, the timestamps in sandbox and gofer logs will
fallback to UTC timezone after execving "/proc/self/exe" which
may not be very convenient for users to analyse the logs:
I0708 15:37:43.825100       1 chroot.go:69] Setting up sandbox chroot in "/tmp"
I0708 15:37:43.825189       1 chroot.go:31] Mounting "proc" at "/tmp/proc"
......
I0708 15:37:43.850926       1 cmd.go:73] Execve "/proc/self/exe" again, bye!
I0708 07:37:43.856719       1 main.go:218] ***************************
I0708 07:37:43.856751       1 main.go:219] Args: [runsc-sandbox --root=/run/...]
I0708 07:37:43.856785       1 main.go:220] …
> runsc: fix the local timezone support in logs

- pkg/sentry/platform/kvm/bluepill_fault.go
- pkg/sentry/platform/kvm/machine.go
1. Currently, setMemoryRegion is triggered every time, even if the memory region has mapped.
It is supposed to store `physicalStart` in `usedSlot` rather than `physical`.
2. Make `hasSlot` scan allocated slot, rather than the whole slice.
Performance is tuned by applying this PR. e.g.
1. `test/perf/mapping_benchmark`
Before #6358 
```
----------------------------------------------------------------------------
Benchmark                                  Time             CPU   Iterations
----------------------------------------------------------------------------
BM_MapUnmap/1/real_time                32812 ns        33089 ns        21457
BM_MapUnmap/8/real_time                33095 ns        32898 ns        22798
BM_MapUnmap/64/real_time               40419 ns        40751 ns        20122 …
```
> tunning hasSlot function and fix store wrong value in usedSlots

- pkg/bitmap/BUILD
- pkg/bitmap/bitmap.go
- pkg/bitmap/bitmap_test.go
- pkg/sentry/kernel/BUILD
- pkg/sentry/kernel/fd_table.go
- pkg/sentry/kernel/fd_table_unsafe.go
- test/perf/BUILD
- test/perf/linux/BUILD
- test/perf/linux/dup_benchmark.cc
- test/syscalls/linux/BUILD
- test/syscalls/linux/dup.cc
Provides the implementation of bitmap.
Apply bitmap in fd_table to record open file FD. It can accelerate the speed of allocating FD for fdtable.
The time complexity to find an available FD is O(1) in the bitmap.
Fixes #6136
**Current tests status:**
Here is the benchmark for this PR.
1. time of create 10000 socket
| original | bitmap | runc |
| --- | --- | --- |
| 1.076s | 0.700s | 0.070s |
2. time of some syscall tests (run each syscall tests five times and calculate the average time)
|| original | bitmap |
| --- | --- | --- |
|ping_socket_test_runsc_kvm_vfs2| 31.8s | 26.5s |
|socket_inet_loopback_nogotsan_test_runsc_kvm_vfs2| 51.2s | 44.5s |
|socket_ipv4_udp_unbound_loopback_nogotsan_test_runsc_kvm_vfs2| 26.9s | 18.1s |
> Add bitmap library and apply bitmap in fd_table

- pkg/sentry/fsimpl/cgroupfs/cgroupfs.go
Since cgroupfs.dir embedes cgroupfs.implStatFS, and dir.StatFS and
implStatFS.StatFS are identical, dir.StatFS is not needed.
> Delete unnecessary function.

- pkg/atomicbitops/BUILD
- pkg/atomicbitops/aligned_32bit_unsafe.go
- pkg/atomicbitops/aligned_test.go
AlignedAtomicUint64 is 15 bytes and it takes 16 bytes in structures.
On 32-bit systems, variables and structure fields is guaranteed to be 32-bit aligned
and this means that we need only 12 bytes to find 8 contiguous bytes.
> Reduce overhead of AlignedAtomic types

- CONTRIBUTING.md
`tools/go_mod.sh` is not in the repo. In order to update the
WORKSPACE dependencies, we can use the same gazelle command in BUILD file.
Signed-off-by: Daniel Dao <dqminh89@gmail.com>
> Fix instructions refer to `tools/go_mod.sh`

- pkg/sentry/platform/kvm/bluepill_fault.go
Right now, the first slot starts with an address of a memory region and its size is faultBlockSize,
but the second slot starts with (physicalStart + faultBlockSize) & faultBlockMask.
It means they will overlap if a start address of a memory region are not aligned to faultBlockSize.
The kernel doesn't allow to add overlapped regions, but we ignore the EEXIST error.
> platform/kvm: set physical slots without overlapping

- pkg/sentry/kernel/thread_group.go
- test/syscalls/linux/pty.cc
SetForegroundProcessGroup now send a SIGTTOU signal if called by a process belonging to a background group. Fixes #6148
> fix missing SIGTTOU signal in SetForegroundProcessGroup

- runsc/cmd/run.go
Rootless mode seems to work fine for simple containers with runsc run,
so allow its use.
Since runsc run is more widely used, require a workable --network option
is passed rather than automatically switching like runsc do does.
Fixes #3036
> runsc: allow rootless mode for runsc run

- pkg/atomicbitops/atomicbitops_amd64.s
Fix frame pointer is clobbered before saving vet issue on `BP` register.
`BP` should be callee-save. It will be saved automatically if there is nonzero frame size.
```console
$ go1.16.5 vet -framepointer ./pkg/atomicbitops
atomicbitops/atomicbitops_amd64.s:20:1: frame pointer is clobbered before saving
atomicbitops/atomicbitops_amd64.s:27:1: frame pointer is clobbered before saving
atomicbitops/atomicbitops_amd64.s:34:1: frame pointer is clobbered before saving
atomicbitops/atomicbitops_amd64.s:50:1: frame pointer is clobbered before saving
atomicbitops/atomicbitops_amd64.s:57:1: frame pointer is clobbered before saving
atomicbitops/atomicbitops_amd64.s:64:1: frame pointer is clobbered before saving
```
> Fix frame pointer is clobbered before saving vet issue on BP register

- g3doc/user_guide/install.md
As apt-key got deprecated in Debian 11 and will be deleted from Debian 12
Replace apt-key by the supported keyring + signed-by method
Related : docker/docker.github.io#11625
Debian wiki : https://wiki.debian.org/DebianRepository/UseThirdParty
Signed-off-by: Nicolas stig124 FORMICHELLA <stigpro@outlook.fr>
> Deprecating apt-key

- pkg/ring0/pagetables/pagetables.go
- pkg/sentry/platform/kvm/BUILD
- pkg/sentry/platform/kvm/bluepill.go
- pkg/sentry/platform/kvm/bluepill_amd64.s
- pkg/sentry/platform/kvm/bluepill_arm64.s
- pkg/sentry/platform/kvm/bluepill_unsafe.go
- pkg/sentry/platform/kvm/kvm_safecopy_test.go
- pkg/sentry/platform/kvm/machine.go
- pkg/sentry/platform/kvm/machine_amd64.go
- pkg/sentry/platform/kvm/machine_amd64_unsafe.go
- pkg/sentry/platform/kvm/machine_arm64.go
- pkg/sentry/platform/kvm/machine_arm64_unsafe.go
- pkg/sentry/platform/kvm/machine_unsafe.go
- pkg/sentry/platform/kvm/physical_map.go
- pkg/sentry/platform/kvm/testutil/testutil_arm64.go
- pkg/sentry/platform/kvm/testutil/testutil_arm64.s
- pkg/sync/atomicptr/generic_atomicptr_unsafe.go
Currently, we map memory regions to the guest from the KVM_EXIT_MMIO handler, but we see too many problems this way. In the case of KVM_EXIT_MMIO, instructions are not executed natively, they are emulated by the kernel KVM code. But this emulator doesn't support all instructions, and it doesn't support all possible cases like faulting on page tables. We already introduces a few hacks to avoid such cases.
Recently, syskaller found another bug when KVM_EXIT_MMIO happens on safecopy code that can trigger SIGBUS or SIGSEGV signals, and there are signal handlers for them. The problem is that KVM_EXIT_MMIO is handled either in the SEGV handler with blocked signals.
This PR is another way to map memory to the guest physical address space.
> kvm: use seccomp to trap mmap syscalls to map new regions to the guest

- pkg/sentry/inet/BUILD
- pkg/sentry/kernel/task.go
- pkg/sentry/kernel/task_clone.go
- pkg/sentry/kernel/task_net.go
- pkg/sentry/kernel/task_start.go
This allows to avoind unnecessary lock-ordering dependencies on task.mu.
> kernel: allow to access Task.netns without taking Task.mu

- test/syscalls/BUILD
- test/syscalls/linux/BUILD
- test/syscalls/linux/proc.cc
- test/syscalls/linux/proc_defaults.cc
Some /proc files are static in gVisor, but can be updated in native linux. To test the values of these files, move them to a separate test and run it using "container" tag to avoid faulty comparisons in native.
Since a separate IPC namespace is used, update shm comparisons to check the actual value, not an interval.
> Run proc's static-file tests in a container.

- pkg/atomicbitops/atomicbitops_amd64.s
- pkg/atomicbitops/atomicbitops_arm64.s
- pkg/atomicbitops/atomicbitops_noasm.go
No split to assembly and noasm functions on atomicbitops package.
The atomic operation should `NOSPLIT`.
This PR revert #2287 but only `pkg/atomicbitops/atomicbitops_amd64.s,atomicbitops_arm64.s,atomicbitops_noasm.go`.
> No split to assmebly and noasm functions on atomicbitops package

- runsc/boot/network.go
- runsc/sandbox/network.go
copy and setup PERMANENT (static) ARP entries
from CNI namespace to the sandbox
Fixes #3301
> copy PERM ARP entries from namespace on boot

- pkg/atomicbitops/aligned_32bit_unsafe.go
- pkg/atomicbitops/aligned_64bit.go
mips was supported, but mipsle had been forgotten.
Fixes google/gvisor#6804
> pkg/atomicbitops: support 32-bit GOARCH value "mipsle"

- runsc/cgroup/cgroup.go
- runsc/cgroup/cgroup_test.go
- runsc/container/container.go
- runsc/sandbox/sandbox.go
This is part of cgroupv2 patch set. Here we add a Cgroup interface that
both v1 and v2 need to conform to, and port cgroupv1 to use that first.
> Add common Cgroup interface

- runsc/config/config.go
- runsc/config/flags.go
- runsc/container/container.go
If it is specified, runsc doesn't configure cgroups and starts a
container in a current cgroup set.
This can be used as a workaround for hosts with cgroupv2.
> runsc: Add the --ignore-cgroups option

- runsc/cmd/capability_test.go
- runsc/cmd/debug.go
- runsc/container/container.go
- runsc/container/container_test.go
- runsc/container/multi_container_test.go
- runsc/sandbox/sandbox.go
- test/root/oom_score_adj_test.go
```
==================
WARNING: DATA RACE
Write at 0x00c000115be0 by main goroutine:
gvisor.dev/gvisor/runsc/sandbox.(*Sandbox).waitForStopped()
runsc/sandbox/sandbox.go:1275 +0x24b
gvisor.dev/gvisor/runsc/sandbox.(*Sandbox).Wait()
runsc/sandbox/sandbox.go:823 +0xa2c
gvisor.dev/gvisor/runsc/container.(*Container).Wait()
runsc/container/container.go:524 +0x131
gvisor.dev/gvisor/runsc/cmd.startContainerAndWait()
runsc/cmd/do.go:398 +0xa18
gvisor.dev/gvisor/runsc/cmd.(*Do).Execute()
runsc/cmd/do.go:156 +0xc16
github.com/google/subcommands.(*Commander).Execute()
external/com_github_google_subcommands/subcommands.go:200 +0x66b
github.com/google/subcommands.Execute()
external/com_github_google_subcommands/subcommands.go:481 +0x2096
gvisor.dev/gvisor/runsc/cli.Main()
runsc/cli/main.go:243 …
```
> runsc: Fix the data race

- g3doc/user_guide/containerd/configuration.md
I'm not a containerd expert, after some testing and verifying with `containerd config dump` the config needs to specify `options` not `option`.
> Configuration needs to use `options` not `option`

- runsc/cmd/do.go
Cleans up the iptables rules created by `runsc do` during network cleanup on exit.
Adds a comment to the nat rule, so that the cleanup code doesn't delete rules from a separate invocation.
> cleanup iptables rules created by runsc do

- pkg/sentry/arch/stack.go
`auxv` in `arch/stack.go` is initialized with the capacity of `len(aux)` but `len(aux)*2+1` elements are appended.
> Allocate auxv with better capacity while loading stack

- pkg/sentry/kernel/task_clone.go
- pkg/sentry/kernel/task_exit.go
mntns.DecRef can be called without holding task.Mu.
```
panic: WARNING: circular locking detected: kernel.taskMutex -> kernfs.filesystemRWMutex:
goroutine 68 [running]:
gvisor.dev/gvisor/pkg/log.Stacks(0x40)
pkg/log/log.go:313 +0x9e
gvisor.dev/gvisor/pkg/sync/locking.checkLock(0xc0000b2780, 0xc0000b3b80, {0x0, 0x0, 0x739539})
pkg/sync/locking/lockdep.go:53 +0x14a
gvisor.dev/gvisor/pkg/sync/locking.AddGLock(0xc0000b2780, 0x0)
pkg/sync/locking/lockdep.go:102 +0x27d
gvisor.dev/gvisor/pkg/sentry/fsimpl/kernfs.(*filesystemRWMutex).Lock(0xc0001e0230)
bazel-out/k8-fastbuild-ST-1a50d7a562c6/bin/pkg/sentry/fsimpl/kernfs/filesystem_mutex.go:16 +0x34
gvisor.dev/gvisor/pkg/sentry/fsimpl/kernfs.(*Filesystem).Release(0xc0001e01e0, {0x158ef50, 0xc00046ca80})
pkg/sentry/fsimpl/kernfs/filesystem.go:266 …
```
> Fix circular locking of kernel.taskMutex and kernfs.filesystemRWMutex

- pkg/tcpip/stack/packet_buffer.go
The reset may be defensive, however, the code as-is is missing a clone
of EgressRoute, and was previously also missing the should-not-be-set
PreserveObject. The reset provides clarity of intent and safety against
missing field assignments.
> packet_buffer: reset packet buffer state in Clone

- pkg/sentry/kernel/fd_table.go
This change breaks dependency of FDTable.mu and kernfs.filesystemRWMutex.
panic: WARNING: circular locking detected: kernel.taskMutex -> kernel.fdTableMutex:
gvisor.dev/gvisor/pkg/sentry/kernel.(*fdTableMutex).Lock(0xc00491a110)
bazel-out/k8-fastbuild-ST-1a50d7a562c6/bin/pkg/sentry/kernel/fd_table_mutex.go:16 +0x34
gvisor.dev/gvisor/pkg/sentry/kernel.(*FDTable).Fork(0xc00491a100, {0x158ef70, 0xc005fdb500}, 0x2073b60)
pkg/sentry/kernel/fd_table.go:637 +0xca
gvisor.dev/gvisor/pkg/sentry/kernel.(*Task).Unshare(0xc005fdb500, 0x4040400)
pkg/sentry/kernel/task_clone.go:483 +0x72d
known lock chain: kernel.fdTableMutex -> kernfs.filesystemRWMutex -> kernel.taskSetRWMutex -> kernel.signalHandlersMutex -> kernel.taskMutex
gvisor.dev/gvisor/pkg/sentry/kernel.(*FDTable).String(0xc000cd36c0) …
> kernel: release FDTable lock before calling file methods

- pkg/sentry/socket/hostinet/socket.go
- runsc/boot/filter/config.go
> hostinet: allow getsockopt(SO_RCVTIMEO) and getsockopt(SO_SNDTIMEO)

- pkg/atomicbitops/BUILD
- pkg/atomicbitops/atomicbitops_arm64.go
- pkg/atomicbitops/atomicbitops_arm64.s
- pkg/atomicbitops/atomicbitops_benchmark_test.go
- pkg/tcpip/BUILD
benchmark for the atomics instructions:
Without LSE instructions:
BenchmarkAndUint32-80                           138205774                8.562 ns/op
BenchmarkAndUint64-80                           139365404                8.571 ns/op
BenchmarkAndUint32Parallel-80                   16887577               259.6 ns/op
BenchmarkAndUint64Parallel-80                    6202482               281.2 ns/op
BenchmarkOrUint32-80                            138791865                8.592 ns/op
BenchmarkOrUint64-80                            138424888                8.670 ns/op
BenchmarkOrUint32Parallel-80                    15080332               175.1 ns/op
BenchmarkOrUint64Parallel-80                     8891142               262.2 ns/op
BenchmarkXorUint32-80                           139146337 …
> Arm64 atomic: add LSE atomics instructions to arm64

- runsc/boot/filter/BUILD
- runsc/boot/filter/extra_filters_race_amd64.go
- runsc/boot/filter/extra_filters_race_arm64.go
- runsc/fsgofer/filter/BUILD
- runsc/fsgofer/filter/extra_filters_race_amd64.go
- runsc/fsgofer/filter/extra_filters_race_arm64.go
runsc/fsgofer/filter/extra_filters_race.go:38:3: undefined: unix.SYS_OPEN
runsc/fsgofer/filter/extra_filters_race.go:42:3: undefined: unix.SYS_TIME
> runsc-race: Fix compile time errors on arm64

- runsc/cmd/gofer.go
The -traceback flag sets the Debug.SetTraceback for runsc-sandbox.
We need this for gofer too. Fixes #7583
> Add debug.SetTraceback for runsc-gofer

- test/syscalls/linux/socket_inet_loopback.cc
- test/syscalls/linux/socket_inet_loopback_isolated.cc
SO_BINDTODEVICE required CAP_NET_RAW beofre the 5.7 kernel. This was
fixed in the kernel by c427bfec18f2 ("net: core: enable SO_BINDTODEVICE
for non-root users").
> Move BindToDeviceReusePort to socket_inet_loopback_isolated

- pkg/tcpip/transport/internal/network/endpoint.go
- pkg/tcpip/transport/raw/endpoint.go
Reported-by: syzbot+5cccbb7c0511ad1aa175@syzkaller.appspotmail.com
> tcpip/transport/raw: check MTU before copying a buffer from user memory

- pkg/sync/locking/lockdep.go
It is lockless and so it guarantes to avoid nested locks (deadlocks).
Reported-by: syzbot+7f2b94fef2e1109bcd40@syzkaller.appspotmail.com
> sync/lockdep: use RangeRepeatable instead of Range

- pkg/sentry/platform/kvm/filters.go
They are used in bluepillReadyStopGuest to ajust rflags.
Fixes: #7600
> platform/kvm: allow KVM_{G,S}ET_REGS in seccomp filters

- pkg/context/context.go
- pkg/log/log.go
bgContext is set during package initialization. However, the global
logger's SetTarget() method doesn't apply to instances of
context.Background() loaded after the first one.
See https://github.com/google/gvisor/issues/7795
> context: initialize and use bgContext once

- pkg/atomicbitops/BUILD
- pkg/atomicbitops/atomicbitops_arm64.go
- pkg/cpuid/native_arm64.go
- pkg/tcpip/BUILD
> atomicbitops, cpuid: fix warnings, lack of atomics on macOS

- pkg/tcpip/adapters/gonet/gonet.go
- pkg/tcpip/adapters/gonet/gonet_test.go
* Fix a panic that would occur when calling gonet.(*TCPListener).Shutdown twice.
* Add test for gonet.(*TCPListener).Shutdown and gonet.(*TCPListener).Close
unblocking gonet.(*TCPListener).Accept.
> Fix double gonet.(*TCPListener).Shutdown panic.

- pkg/ring0/defs_amd64.go
- pkg/ring0/defs_arm64.go
- pkg/ring0/entry_amd64.s
- pkg/sentry/platform/kvm/bluepill_amd64.go
- pkg/sentry/platform/kvm/bluepill_arm64.go
- pkg/sentry/platform/kvm/bluepill_unsafe.go
- pkg/sentry/platform/kvm/machine_arm64.go
Here are not visible perfomance effects:
Before:
```
goos: linux
goarch: amd64
cpu: Intel(R) Xeon(R) W-2135 CPU @ 3.70GHz
BenchmarkApplicationSyscall
I0401 16:23:28.351151  2594711 physical_map.go:145] region: virtual [3f1eaf85f000,7f202f85f000)
I0401 16:23:28.351260  2594711 physical_map.go:197] physicalRegion: virtual [1000,3f1eaf85f000) => physical [100001000,3f1faf85f000)
I0401 16:23:28.351287  2594711 physical_map.go:197] physicalRegion: virtual [7f202f85f000,7ffffffff000) => physical [3f1faf85f000,3fff7ffff000)
BenchmarkApplicationSyscall-6           	 2574579	       408.2 ns/op
BenchmarkKernelSyscall
BenchmarkKernelSyscall-6                	 2268025	       500.0 ns/op
BenchmarkKernelVDSO
BenchmarkKernelVDSO-6                   	26895987	        41.30 ns/op …
```
> kvm: add a few sanity checks on vmexit-s

- tools/images.mk
images.mk: make sort result stable to generate the same image tag at diffrent machines
sort result is not stable with different environment, such as LC_ALL or LC_COLLATE,
we may get diffrent tag at diffrent machines,
sort with ignore case and use dictionary order is better.
Signed-off-by: Tan Yifeng <yiftan@163.com>
> images.mk: make sort result stable to generate the same image tag

- pkg/sentry/socket/hostinet/socket.go
- runsc/boot/filter/config.go
Support set or get tcpsockopt TCP_MAXSEG, TCP_CONGESTION for hostnetwork mode.
This will fix iperf3 3.9 version running error.
Signed-off-by: Tan Yifeng <yiftan@163.com>
> support set or get tcpsockopt TCP_MAXSEG, TCP_CONGESTION for hostnetwork.

- pkg/sentry/socket/hostinet/socket.go
This will fix error that gvisor returned EINVAL in hostnetwork mode
if outLen of user process passed in is less than length of linux.SizeOfTCPInfo in gvisor.
Signed-off-by: Tan Yifeng <yiftan@163.com>
> Truncate the output buffer to outLen size when getsockopt with TCP_INFO.

- vdso/vdso.cc
Current vdso(implemented by sentry, and used by the real application) is a partial implimentation. More specifically, the clock_gettime() vdso interface only works for CLOCK_REALTIME, CLOCK_BOOTTIME, and CLOCK_MONOTONIC.
So we support more flags for clock_gettime() vdso interface here, like CLOCK_REALTIME_COARSE, CLOCK_MONOTONIC_RAW, and CLOCK_MONOTONIC_COARSE, to accelerate clock_gettime() call of real application.
And their implementations refer to the internal syscall of gvisor. See function getClock() in pkg/sentry/syscalls/linux/sys_time.go.
Signed-off-by: Chen Hui <cedriccchen@tencent.com>
> vdso: support more flags for clock_gettime() vdso interface

- pkg/sentry/seccheck/README.md
This PR adjusts typos, grammar, and minor formatting in the `seccheck` README.  These are admittedly nits, but while reading this doc, I found that they distracted from the content.
Thanks!
> Update seccheck README for typos

- images/benchmarks/hackbench/Dockerfile
- images/benchmarks/syscallbench/Dockerfile
- images/benchmarks/syscallbench/syscallbench.c
- test/benchmarks/base/BUILD
- test/benchmarks/base/hackbench_test.go
- test/benchmarks/base/sysbench_test.go
- test/benchmarks/base/syscallbench_test.go
- test/benchmarks/fs/fio_test.go
- test/benchmarks/network/iperf_test.go
- test/benchmarks/tools/BUILD
- test/benchmarks/tools/hackbench.go
- test/benchmarks/tools/iperf.go
benchmarks: add and fix some benchmarks
1. add syscallbench benchmark for syscall performance
2. add hackbench benchmark for scheduler performance
3. add more threads arguments for sysbench benchmark
4. fix wrong file size for fio read
5. add more blocksize arguments for fio benchmark
6. fix invalid option of length for iperf benchmark
7. add length and parallel options for iperf benchmark
> benchmarks: add and fix some benchmarks

- pkg/refs/refcounter.go
First, they call a destructor that can be without the nosplit tag. Second, they calls Mutex.Lock and Mutex.Unlock that are not marked as nosplit.
Fixes: #8149
> refs: remove the nosplit annotation from DecRefWithDestructor and DecDef

- pkg/sentry/platform/kvm/machine_unsafe.go
unix.RawSyscall is a wrapper of syscall.RawSyscall:
gvisor.dev/gvisor/pkg/sentry/platform/kvm.sigsysHandler: nosplit stack over 792 byte limit gvisor.dev/gvisor/pkg/sentry/platform/kvm.sigsysHandler<0>
grows 16 bytes, calls gvisor.dev/gvisor/pkg/sentry/platform/kvm.seccompMmapHandler<0>
grows 32 bytes, calls gvisor.dev/gvisor/pkg/sentry/platform/kvm.seccompMmapHandler<1>
grows 144 bytes, calls gvisor.dev/gvisor/pkg/sentry/platform/kvm.(*machine).mapPhysical<1>
grows 96 bytes, calls gvisor.dev/gvisor/pkg/sentry/platform/kvm.handleBluepillFault<1>
grows 128 bytes, calls gvisor.dev/gvisor/pkg/sentry/platform/kvm.(*machine).setMemoryRegion<1>
grows 160 bytes, calls golang.org/x/sys/unix.RawSyscall<0>
grows 0 bytes, calls syscall.RawSyscall<0>
grows 80 bytes, calls syscall.RawSyscall<1>
grows …
> kvm: use syscall.RawSyscall to fit the nosplit stack limit.

- pkg/tcpip/stack/BUILD
- pkg/tcpip/stack/addressable_endpoint_state.go
In this case, we don't need to take a read-write lock in IncRef and DecRef.
> tcpip/stack: use atomic refs for addressState

- pkg/sentry/fsimpl/gofer/BUILD
- pkg/sentry/fsimpl/gofer/directory.go
- pkg/sentry/fsimpl/gofer/filesystem.go
- pkg/sentry/fsimpl/gofer/gofer.go
- pkg/sentry/fsimpl/gofer/gofer_test.go
Fix issue #8267
when create and remove file, dentry.children will cache the name to speedup file access,
memory will increse infinitely if we remove huge amount of different files,
limit the length of negative file names is necessary since most of removed files will never access again.
Signed-off-by: Tan Yifeng <yiftan@tencent.com>
> limit numbers of negative children to avoid infinitely increment of memory

- .github/workflows/go.yml
Starting 1st June 2023 (planned) workflows, `::set-output name...::` syntax cannot be used. You can see the example warnings here: https://github.com/google/gvisor/actions/runs/3791389619
ref. [GitHub Actions: Deprecating save-state and set-output commands | GitHub Changelog](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
This PR fixes the issue by using the `GITHUB_OUTPUT` environment variable as instructed in the above article.
> ci: update GitHub Actions to avoid set-output deprecation

- pkg/tcpip/adapters/gonet/gonet_test.go
I fixed to use `UDPConn` instead of `TCPConn` in `udp.NewForwarder` callback
> fixed to use NewUDPConn instead of NewTCPConn

- pkg/sentry/fsimpl/proc/task.go
- pkg/sentry/fsimpl/proc/task_files.go
- pkg/sentry/fsimpl/proc/tasks_test.go
- pkg/sentry/limits/limits.go
- test/syscalls/linux/BUILD
- test/syscalls/linux/rlimits.cc
- test/util/proc_util.cc
- test/util/proc_util.h
This adds support for the `/proc/[pid]/limits` file to view information from `ulimit` or `setrlimit`. It prints the output in the exact format that the Linux kernel uses, which is hand-spaced columns instead of tabs or a columnar printer. In order to support the file format, helpers have been added to get the textual names and units for the limit types.
> Add support for /proc/[pid]/limits

- .bazelrc
- tools/bazel.mk
* We build all binaries in a build container but then we execute them in
another evironments, so we don't want to have a dependency on glibc.
* runsc is build without cgo, so it looks reasonable to build tests with
the same flags.
* If we build all packeges with the same flags, they all shares the same
cache.
This change adds the race config to build with the race detector
> Disable cgo by default

- pkg/sighandling/sighandling.go
- runsc/cmd/do.go
- runsc/cmd/exec.go
- runsc/console/BUILD
- runsc/console/pty_linux.go
- runsc/container/container.go
- runsc/specutils/namespace.go
When executing `runsc` directly inside a host terminal (e.g. using `runsc --ignore-cgroups --network=sandbox --file-access=shared --rootless --host-uds=all do --force-overlay=false -- bash`), `Ctrl+C` currently terminates the sandbox instead of causing the signal to be handled by the terminal in the guest.
Therefore, this commit adds terminal support to the `do`, `exec` and `run` commands.
> Add terminal support to do, exec and run commands

- pkg/sentry/platform/systrap/sysmsg/pie.lds.S
Currently, runsc fails to build on systems which still use the legacy GNU linker (i.e. not gold), which is still the default linker on many systems:
```
ERROR: /gvisor/pkg/sentry/platform/systrap/sysmsg/BUILD:62:8: Executing genrule //pkg/sentry/platform/systrap/sysmsg:sighandler.built-in.object failed: (Exit 1): bash failed: error executing command (from target //pkg/sentry/platform/systrap/sysmsg:sighandler.built-in.object) /bin/bash -c ... (remaining 1 argument skipped)
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
/usr/bin/ld: section .note.gnu.property LMA [0000000000000000,000000000000002f] overlaps section .crblob LMA [0000000000000000,0000000000005e3f]
/usr/bin/ld: warning: …
```
> Support building runsc with legacy GNU linker

- .buildkite/hooks/pre-command
- BUILD
- tools/go_branch.sh
With the link mode, we see stale files from previous runs in bazel-bin/gopath.
> gopath: switch to the archive mode

- pkg/tcpip/adapters/gonet/gonet_test.go
- pkg/tcpip/transport/tcp/endpoint.go
This PR includes the changes to unblock all the waiters as part of net stack close.
https://github.com/google/gvisor/issues/8748
1. Testing the fix by porting the fix to "go" branch and confirmed that all the readers get unblocked when net stack is closed.
2. Added the unit test and confirmed unit test is running as expected.
> [bugfix/close_endpoints_on_stack_close] On net stack close, wake up all the waiters

- pkg/sentry/control/proc.go
- pkg/sentry/fsimpl/host/host.go
- runsc/boot/loader.go
- runsc/boot/vfs.go
- runsc/cmd/boot.go
- runsc/cmd/exec.go
- runsc/cmd/exec_test.go
- runsc/cmd/run.go
- runsc/container/console_test.go
- runsc/container/container.go
- runsc/container/container_test.go
- runsc/container/metric_server_test.go
- runsc/container/multi_container_test.go
- runsc/sandbox/sandbox.go
Hi,
this commit adds support for program execution via a host file descriptor. To make use of this feature, the host file descriptor must be mapped to -1 in the guest. For example,
exec 3</usr/bin/echo
runsc exec --pass-fd=3:-1 mycontainer hello world
will run the host's echo binary inside gVisor. In this case, "hello" is supplied to echo as argv[0]. As a result, the output of the above command is "world".
This feature is useful for bootstrapping unknown guest environments and allows static executables to perform setup actions inside the container while they need not be part of the guest file system.
Again, I am not sure whether this is a feature you would agree on merging. If not, please feel free to close this PR. Otherwise, I am happy about feedback on the implementation details (for …
> Add support for execution via host file descriptor

- g3doc/user_guide/quick_start/docker.md
Regarding #8957, running runsc with debugging enabled will always crash (and not mention SELinux as the root cause in debug logs), as it fails due to a permissions error. This addition warns to disable SELinux as it's not mentioned elsewhere in the g3docs.
> Added SELinux warning to documentation

- pkg/sentry/syscalls/linux/sys_read_write.go
- pkg/tcpip/transport/tcp/endpoint.go
- pkg/tcpip/transport/tcp/rcv.go
- pkg/tcpip/transport/tcp/snd.go
- test/syscalls/linux/socket_inet_loopback.cc
Hi,
I am proposing a change that should fix issue #6015. 
As per my understanding POLLRDHUP triggers when there is a half-closed TCP connection (either remote shutdown(SHUT\_WR) or local shutdown(SHUT\_RD)), therefore I have added a new equivalent event to waiter - `waiter.EventRdHUp` and added the event to `allEvents` and a "list" of events that can get triggered on read in `sys_read.go`. The TCP endpoint now checks whether the connection is half-closed and sets the appropriate flag. Additionally, TCP shutdown function notifies when only read end of the endpoint connection is closed. I have updated the syscall tests to reflect this change.
It is possible that some things are missing here but I will gladly update the PR if something was overlooked.
Let me know what you think.
> POLLRDHUP delivery fix

- g3doc/user_guide/FAQ.md
https://github.com/google/gvisor/issues/9006 - gvisor does not work in Yama mode 2 and --directfs=false because sandbox lacks cap_sys_ptrace
> doc/faq/ptrace/attach: yama lsm supported mode

- runsc/sandbox/network.go
In practice, we found that createSocket() could cost up to 40ms, which is an unacceptable overhead in FaaS(Function as a Service) scenario. The root cause is the bind() syscall runs into the slow path in kernel and invokes synchronize_net(), which is an expensive call.
From kernel commit[1] we learned that we could bypass this slow path by adjusting the socket() syscall before we call bind(). By giving the empty protocal number, the packet_create() will not call __register_prot_hook(), in which the kernel turn on the flag packet_sock.running. So when it comes to packet_do_bind(), it won't call synchronize_net() for there is no prot_hook to unregister.
Worst cost for bind() tested on Intel Xeon E5-2682 with Linux kernel 5.4 over 100 times:
* before: 39633.274 us
* after:     25.098 us …
> network: speed up createSocket() by giving protocal 0 in socket()

- tools/checklocks/analysis.go
- tools/checklocks/test/atomics.go
This allows the use of wrappers such as atomic.Int32 introduced in Go 1.19 without triggering the `unexpected call to atomic function`.
I tried running recent checklocks on `github.com/kopia/kopia` and got a ton of such errors, which I don't think should be reported since the wrappers are there to ensure safety of atomic operations. This PR fixes the issue.
> checklocks: always allow calls to methods of atomic wrappers

- g3doc/user_guide/containerd/quick_start.md
- Updated apiVersion of RuntimeClass.
https://kubernetes.io/docs/concepts/containers/runtime-class/#2-create-the-corresponding-runtimeclass-resources
> docs(k8s): updated apiVersion for RuntimeClass

- runsc/cmd/boot.go
The Go runtime can run GC at any point once it falls into the branch of `setupRoot && !rootless && !applyCaps`, so `specFile` becomes eligible for closing. This results in the occasional crash on re-exec where the FD was recycled for the proc-mount-sync-fd pipe created in that branch and causes the seek back to 0 to re-read the spec to fail with an ESPIPE error.
> Keep spec-file FD alive past point of exec as nobody

- pkg/xdp/xdp.go
- runsc/sandbox/BUILD
- runsc/sandbox/bpf/BUILD
- runsc/sandbox/bpf/bpf.go
- runsc/sandbox/network.go
- test/benchmarks/tcp/BUILD
- test/benchmarks/tcp/tcp_benchmark.sh
- test/benchmarks/tcp/tcp_proxy.go
- test/benchmarks/tcp/xdp.go
This just swaps out the fdbased endpoint for an XDP one. Some related changes in here:
- Moved the AF_XDP BPF program into its own Go package so it can be shared.
- Added a flag to tcp_benchmark to disable user namespaces. This helps when running as root, which is required to install BPF programs.
> netstack: benchmark xdp endpoint

- pkg/sentry/fsimpl/devpts/devpts_test.go
- pkg/sentry/fsimpl/devpts/line_discipline.go
- pkg/sentry/fsimpl/devpts/queue.go
This fixes the ctrl-d part of #9333.
Disclaimer: new to this codebase.
> Fix EOF (^D) handling in devpts (partially addr #9333)

- pkg/sentry/fsimpl/devpts/master.go
- pkg/sentry/fsimpl/devpts/replica.go
- test/syscalls/linux/pty.cc
While there is a difference between flavors of this ioctl (`TCSETS`, `TCSETSF`, `TCSETSW`), in practice it seems not to matter. We should let users call `TCSETSF` and can implement those differences if necessary.
Fixes #9335.
> tty: enable `TCSETSF`

- .github/workflows/codeql.yml
CodeQL will scan and analyze specified languages at gVisor's master branch weekly on Sunday. The config is mostly identical to the default CodeQL other than disabling CodeQL workflow at push and pull request stage.
> Add initial CodeQL config for gVisor.

- runsc/container/container.go
This call is repeated on every container startup sequence, but it is expensive, consistently taking between 2-3 seconds to run each time. This adds a significant amount of startup latency to every container. From `strace` output, the main issue appears to be a call to `openat(AT_FDCWD, "/dev/nvidia0", O_RDWR|O_CLOEXEC)`. The first time this is called, it creates a new open device file descriptor and blocks for 2 seconds while doing so. This was measured on a `g4dn.2xlarge` instance on AWS, running a Tesla T4 GPU.
For comparison, the `nvidia-container-prestart-hook` for runc also runs `nvidia-container-cli` during container boot, but it only calls it once for the `configure` command. gVisor appears to call it twice, once for `info` and then for `configure`.
By removing the `info` call, or …
> perf: Remove call to nvidia-container-cli info

- pkg/sentry/platform/systrap/subprocess.go
- pkg/sentry/platform/systrap/sysmsg_thread_unsafe.go
container_test:TestGoferExits fails by timeout, because there are some sysmsg threads survived sandbox process death. When we fork a new sysmsg thread, it is traced with PTRACE_O_EXITKILL, so we need to set PDEATHSIG before detaching from it.
> systrap: set PDEATHSIG right after forking a sysmsg thread

- g3doc/user_guide/debugging.md
Updated based on current state of `master` and it works 🙂 
<kbd>
</kbd>
> fix: outdated line in debugging.md doc

- images/default/Dockerfile
- pkg/abi/linux/file.go
- pkg/erofs/BUILD
- pkg/erofs/erofs.go
- pkg/erofs/erofs_test.go
- pkg/sentry/fsimpl/erofs/BUILD
- pkg/sentry/fsimpl/erofs/directory.go
- pkg/sentry/fsimpl/erofs/erofs.go
- pkg/sentry/fsimpl/erofs/filesystem.go
- pkg/sentry/fsimpl/erofs/regular_file.go
- pkg/sentry/fsimpl/erofs/save_restore.go
- runsc/boot/BUILD
- runsc/boot/controller.go
- runsc/boot/vfs.go
- runsc/cmd/debug.go
- runsc/container/container_test.go
- runsc/sandbox/BUILD
- runsc/sandbox/sandbox.go
- test/cmd/test_app/main.go
This PR adds initial support for EROFS [1].  Below is a brief summary of the supported features.
Both inode formats are supported:
- compact format (32 bytes);
- extended format (64 bytes);
Below data layouts are supported:
- flat file data without data inline (no extent);
- flat file data with tail packing data inline (no extent);
Below file types are supported:
- directory;
- regular file;
- symlink;
Special files (e.g. fifo) can be listed, but cannot be accessed.
With this PR, sentry will be able to mount the EROFS image created with below command and access the files on it.
```
mkfs.erofs -E noinline_data <IMAGE FILE> <SOURCE DIRECTORY>
```
Other features, e.g. checkpoint/restore, mounting EROFS as rootfs will be added in the follow up RPs.
Updates #8956
[1] …
> Add initial support for EROFS

- pkg/erofs/erofs.go
- pkg/sentry/fsimpl/erofs/directory.go
- runsc/container/container_test.go
For each directory, _all_ the on-disk directory entries are _strictly_
recorded in alphabetical order. There is no special treatment of "." and
"..". Thanks to @hsiangkao for pointing out this bug.
Fixes: eca83ac68cda ("Add initial support for EROFS")
Reported-by: Gao Xiang <xiang@kernel.org>
Signed-off-by: Tiwei Bie <tiwei.btw@antgroup.com>
> erofs: fix wrong assumption on the order of on-disk directory entries

- pkg/tcpip/checksum/BUILD
- pkg/tcpip/checksum/checksum_amd64.s
- pkg/tcpip/checksum/checksum_mips64.go
- pkg/tcpip/checksum/checksum_noasm.go
- pkg/tcpip/checksum/checksum_noasm_unsafe.go
- pkg/tcpip/checksum/checksum_test.go
- When buffers aren't 64 bit aligned, use the slower unrolled checksum that's safe across different architectures.
- Remove the copied checksum implementation in checksum_test so we don't have to update both.
- Play with build tags such that checksum_test tests all checksum implementations, not just the preferred one on that architecture.
Fixes #9499.
> netstack: fall back to slower checksum when buffer isn't aligned

- pkg/erofs/erofs.go
- pkg/sentry/fsimpl/erofs/erofs.go
- pkg/sentry/fsimpl/erofs/regular_file.go
- pkg/sentry/fsimpl/erofs/save_restore.go
- pkg/sentry/fsimpl/gofer/save_restore.go
- pkg/sentry/vfs/context.go
- runsc/boot/vfs.go
This PR adds the checkpoint/restore support to EROFS. A test for checkpoint/restore will be included in the rootfs support PR (https://github.com/google/gvisor/pull/9486).
cc @ayushr2
> Add the checkpoint/restore support to EROFS

- pkg/erofs/BUILD
- pkg/erofs/erofs.go
- pkg/erofs/erofs_test.go
- pkg/erofs/erofs_unsafe.go
Currently, when we access the on-disk filesystem objects, the objects will be copied to temporary buffers and will escape to heap. This patch gets rid of these unnecessary copies and escapes by casting and using the memory backed the image file directly.
> erofs: avoid unnecessary escapes and memory copies

- runsc/cli/BUILD
- runsc/cli/main.go
- runsc/cmd/nvproxy/BUILD
- runsc/cmd/nvproxy/list_supported_drivers.go
- runsc/cmd/nvproxy/nvproxy.go
Since the driver versions are hard-coded, determining the supported version list requires code inspection, which is difficult to automate. Add a sub-command (and category) to print the list of nvidia driver versions supported by nvproxy for a given build of runsc.
> Add subcommand to list nvproxy supported driver versions

- runsc/container/container_test.go
When ws is not zero (i.e. the app in container exited with a non-zero status), executeCombinedOutput should still read and return app's output, because it may contain the contents that app sent to stdout/stderr which can be helpful for diagnosing the failures.
> runsc/container_test: fix executeCombinedOutput's output

- pkg/tcpip/sample/tun_tcp_echo/main.go
should not call `tcpip.endpoint.Write` in `tcpip.endpoint.Read`.
```shell
ip tuntap add abc mode tun
ip link set abc up
ip addr add 192.168.140.2/24 dev abc
```
In one shell:
```shell
./tun_tcp_echo abc 192.168.140.1 8000
```
In another shell:
```shell
nc 192.168.140.2 8000
```
**The program blocks forever.**
pkg/tcpip/sample/tun_tcp_echo.go:91: ep.Read calls
pkg/tcpip/transport/tcp/endpoint.go:1402: Read, and locks e.mu.
pkg/tcpip/sample/tun_tcp_echo.go:64 e.ep.Write needs to aquire e.mu
> Fix a lock problem in pkg/tcpip/sample/tun_tcp_echo

- pkg/sentry/fsimpl/proc/tasks_sys.go
- pkg/sentry/kernel/auth/id.go
- test/syscalls/linux/proc.cc
We have a user application attempting to use [bubblewrap](https://github.com/containers/bubblewrap) inside `gvisor`, and it's hitting errors because of these proc files being missing. 
```
bwrap: Can't read /proc/sys/kernel/overflowuid: No such file or directory
```
This changeset adds the files with their default Linux values, but they're not writeable. https://docs.kernel.org/admin-guide/sysctl/fs.html#overflowgid-overflowuid
> provide (read only) /proc/sys/kernel/overflowuid and overflowgid

- pkg/buffer/chunk.go
- pkg/safemem/block_unsafe.go
- pkg/sentry/arch/fpu/fpu_amd64.go
- pkg/sentry/pgalloc/pgalloc.go
- pkg/sentry/syscalls/linux/sys_getdents.go
- pkg/tcpip/header/ipv4.go
- pkg/tcpip/header/ipv6_extension_headers.go
- pkg/usermem/bytes_io.go
- tools/go_marshal/analysis/analysis_unsafe.go
This PR is really simple,
Go 1.21 added the `clear` builtin which clears slices,
using it here can give up to 15% performance increase in use cases pertaining to high volume of small buffers
> use new clear builtin to clear bufferv2 data

- pkg/sentry/kernel/task_sched.go
- pkg/sentry/kernel/task_test.go
- test/syscalls/linux/getcpu.cc
When tid % allowed.NumCPUs() equals 0, e.g. when there is only one
allowed CPU, we will always pick CPU 0 even if it's not in the allow
list. This patch fixes this issue by checking the counter first.
Fixes #3133
> Make sure we will always pick a valid CPU

- images/README.md
This reverts commit 12c2c6ae3, as commit a855a814d ("Refactor the Makefile to avoid recursive Make.") recreated tools/images.mk and removed images/Makefile.
> docs: images/Makefile does not exist.

- pkg/sentry/socket/netfilter/tcp_matcher.go
- test/iptables/filter_input.go
- test/iptables/filter_output.go
- test/iptables/iptables_test.go
Add support for inverting --dport and --sport matches in netfilter. This allows support for Istio versions 1.18 and higher
Fixes: #9865
> sentry/netfilter: support inverse dport/sport

- .bazelrc
Without this, bazel keeps creating empty MODULE.bazel and MODULE.bazel.lock files. We should switch over to bzlmod, but for now don't pollute repositories.
> add --noenable_bzlmod to .bazelrc

- pkg/sentry/fsimpl/devpts/line_discipline.go
- test/syscalls/linux/pty.cc
Fixes #9955
Unfortunately I'm not familiar with the codebase or Linux terminals so I don't know if this fix is correct, but it does fix the problems I'm seeing in #9955.
The `queue.write` function already returns `linux.ErrWouldBlock` if the wait buffer is out of room, I think.
> Do not return ErrWouldBlock when writing nothing to PTY output queue

- test/syscalls/linux/pty.cc
Following [this discussion](https://github.com/google/gvisor/pull/9954#discussion_r1475151051), I reduced the timeout period in the PTY tests for cases where we expect to see a timeout to 2 seconds to help speed up tests.
> Reduce timeouts for reading input in PTY tests

- pkg/sentry/fsimpl/devpts/line_discipline.go
- test/syscalls/linux/pty.cc
When switching from canonical to non-canonical mode, only mark inQueue as readable if there is input to be read. This fixes a bug where a program running in a PTY in canonical mode switches to non-canonical mode with nothing in the canonical read buffer, and then proceeds to read from the standard input, which erroneously results in an EOF error.
Closes #9953
> Fix EOFs when reading from an empty canon->noncanon PTY

- Makefile
- pkg/sentry/platform/kvm/filters_arm64.go
The comma character should be put into the argument value by variable substitution.
> make: fix unit-tests

- pkg/log/log.go
- pkg/sentry/kernel/rseq.go
- pkg/sentry/kernel/seccomp.go
- pkg/sentry/kernel/task.go
- pkg/sentry/kernel/task_clone.go
- pkg/sentry/kernel/task_log.go
- pkg/sentry/kernel/task_start.go
- pkg/sentry/kernel/thread_group.go
- pkg/sentry/pgalloc/pgalloc.go
- pkg/sentry/pgalloc/save_restore.go
- pkg/sync/seqatomic/seqatomic_test.go
Convert atomic.Value usages for *T to atomic.Pointer[T]
Fixes: #10089 
Left one usage of atomic.Value for the TCPProbeFunc as Pointer do not directly support functions.
Quite new to go, but wanted to give this a shot as a learning experience.
The unit-tests at least passed on my computer so hopefully it won't break anything!
But feel free to give feedback :)
> Convert atomic.Value to atomic.Pointer[T]

- g3doc/user_guide/install.md
gVisor supports x86\_64 and ARM64 for now, but [Installation document in User Guide](https://gvisor.dev/docs/user_guide/install/) still says the x86\_64 is supported only. This PR is posted to correct it.
> doc: correct the supported architecture in the Installation guide

- pkg/tcpip/stack/tcp.go
- pkg/tcpip/transport/tcp/BUILD
- pkg/tcpip/transport/tcp/cubic.go
- pkg/tcpip/transport/tcp/cubic_test.go
- pkg/tcpip/transport/tcp/reno.go
- pkg/tcpip/transport/tcp/snd.go
Adds support for the HyStart algorithm to TCP with CUBIC congestion control.
HyStart addresses a common problem during slow-start on paths with high bandwidth delay product (BDP), where using only dropped packets as an indication of congestion detects the congestion too late, and the congestion window (cwnd) has vastly overshot the usable bandwidth of the path, causing many many lost packets.
This implementation of HyStart is based on the Linux Kernel, with some additional commentary on [constant values taken from the HyStart++ RFC](https://www.rfc-editor.org/rfc/rfc9406.html#section-4.3) (note we do not implement the RFC algorithm, preferring to follow Linux).
I have tested this implementation via an embedded Tailscale data plane on a path from Abu Dhabi to Helsinki (140 ms RTT). …
> Add support for TCP HyStart

- .github/dependabot.yml
Noticed a few actions used in the workflows here are outdated, proposing a Dependabot configuration to update - reference https://docs.github.com/en/actions/security-guides/using-githubs-security-features-to-secure-your-use-of-github-actions#keeping-the-actions-in-your-workflows-secure-and-up-to-date
Resolves dependency warnings on workflow executions ex. https://github.com/google/gvisor/actions/runs/8903339648
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/stale@v5
Suggest enabling https://docs.github.com/en/code-security/dependabot/working-with-dependabot/about-dependabot-on-github-actions-runners#enabling-or-disabling-for-your-repository as well.
> Dependabot configuration to update actions in workflows

- pkg/sentry/strace/linux64_amd64.go
- pkg/sentry/strace/linux64_arm64.go
Trivial change that would have made debugging `nvidia-smi topo -m` problems easier. 
**Status quo**
```
0x7ec93d642705 "0-4\n", 0xa) = 4 (0x4) (1.52µs)
I0507 19:46:54.276168  1868651 strace.go:561] [   7:   7] nvidia-smi E close(0xb /sys/devices/system/cpu/online)
I0507 19:46:54.276174  1868651 strace.go:599] [   7:   7] nvidia-smi X close(0xb /sys/devices/system/cpu/online) = 0 (0x0) (1.61µs)
I0507 19:46:54.276188  1868651 strace.go:576] [   7:   7] nvidia-smi E sys_439(0xffffffff, 0x7ebada99f057, 0x5, 0x0, 0x1999999999999999, 0x0)
I0507 19:46:54.276200  1868651 strace.go:614] [   7:   7] nvidia-smi X sys_439(0xffffffff, 0x7ebada99f057, 0x5, 0x0, 0x1999999999999999, 0x0) = 0 (0x0) (6.99µs)
I0507 19:46:54.276210  1868651 strace.go:576] [   7:   7] nvidia-smi E sys_439(0xffffffff, …
```
> add strace dbg processing for 'faccessat2'

- runsc/boot/restore.go
As we switch to a new watchdog during restore, there is no need to keep the old one running anymore.
> Stop the old watchdog during restore

- .bazelrc
- WORKSPACE
- images/default/Dockerfile
- tools/bazel.mk
- tools/crosstool-arm-dirs.patch
The key highlight from the release notes:
Build without the Bytes for builds using remote caching and/or remote execution is now enabled by default (i.e. --remote_download_outputs defaults to toplevel). This means that Bazel will no longer try to download any intermediate outputs from the remote server, but only the outputs of requested top-level targets instead. This significantly improves build performance. Bazel now also handles the case of an artifact falling out of the remote cache gracefully, by rewinding the build.
> Update bazel to 7.1.2

- pkg/tcpip/transport/internal/network/endpoint.go
- pkg/tcpip/transport/udp/endpoint.go
The caller will wait for the endpoint to become writable and try again.
Fixes #8566
> upd: don't read any data from payloader if a send buffer is full

- tools/checklocks/facts.go
- tools/checklocks/test/basics.go
- tools/checklocks/test/test.go
This allows specifying guards in the format:
type foo struct {
mu  sync.Mutex
bar int // +checklocks:mu
}
This syntax, while more limited, makes writing lock guards less verbose for structures where field documentation isn't attached to each field. For example, being able to write something like the following with field comments reduces the number of lines in the struct by >25% and is, in my opinion, easier to read.
type widget struct {
mu sync.Mutex // guards following
// The following counters track [...]
success  int // +checklocks:mu
failure  int // +checklocks:mu
retries  int // +checklocks:mu
timeouts int // +checklocks:mu
}
> tools/checklocks: support field comments for guard specifications

- pkg/abi/nvgpu/uvm.go
- pkg/sentry/devices/nvproxy/seccomp_filters.go
- pkg/sentry/devices/nvproxy/version.go
Adding ioctls to provide only a partial fix to a simple Huggingface `accelerate` program that does not work on H100s.
---
**Machine info**
* **NVIDIA driver:** `Driver Version: 550.54.15      CUDA Version: 12.4` 
* **NVIDIA device:**  NVIDIA H100 PCIe
* **uname -a:** `Linux worker-prod-lat-h100-dal-0-d22375e2688d4e5caa12deca256c79ec 5.15.0-113-generic #123-Ubuntu SMP Mon Jun 10 08:16:17 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux` 
**Steps**
**1. Install gvisor**
```bash
ARCH="x86_64"  # all workers are x86
URL="https://storage.googleapis.com/gvisor/releases/master/latest/${ARCH}"
wget -nc "${URL}/runsc" "${URL}/runsc.sha512"
chmod +x runsc
sudo cp runsc /usr/local/bin/runsc
sudo /usr/local/bin/runsc install
sudo systemctl reload docker
```
**2. Add GPU enabling gvisor options**
In …
> nvproxy: add missing UVM peer access ioctls

- g3doc/user_guide/gpu.md
This notes which GPU architecture each of the supported GPU types belong to, and some other consumer-oriented GPUs that also belong to these architectures. If a workload is broken on them, it is likely also broken on a supported GPU, and therefore is a valid bug report to improve compatibility of supported GPU types in gVisor.
It also mentions the existence of the `--nvproxy-driver-version` flag and the `ioctl_sniffer` tool.
Fixes #10624
> Reword "Supported GPUs" documentation

- Makefile
- images/gpu/vllm/Dockerfile.x86_64
- test/gpu/vllm/BUILD
- test/gpu/vllm/vllm_test.go
- tools/images.mk
Hi,
I was playing around with a vLLM benchmark and wanted to get your opinion on how to best deal with large files in benchmarks. The vLLM benchmark serves a model (facebook/opt-125m) and uses vLLM's own benchmark tooling to query it with a widely-used dataset (..). For development I just mounted the model and dataset into the container-under-test. But that seems impractical for CI/other devs.
Should I embed the model files into the benchmark image? Is there another way you would prefer?
Please don't do an actual review yet. Just wanted to get some early feedback. I still have to understand `metricsviz` and how to incorporate it.
> Add vllm benchmark

- pkg/abi/nvgpu/ctrl.go
- pkg/sentry/devices/nvproxy/version.go
This PR adds support for the `NV2080_CTRL_CMD_PERF_GET_CURRENT_PSTATE` ioctl in nvproxy.
Currently, when `nvidia-smi` is executed in a container, `nvproxy: unknown control command 0x20802068 (paramsSize=4)` appears in the debug logs. Additionally, the output of `nvidia-smi` shows `ERR!` under the `Perf` column for each GPU. This error effects T4s and L4s, although it likely effects other GPUs. This PR fixes both of these issues.
This is one of the five unimplemented ioctls mentioned in #10627. I also plan on completing #10627.
To reproduce this, simply run `nvidia-smi` in any gVisor container with the NVIDIA drivers installed. This can be done in many ways; here is one.
1. Dockerfile
```dockerfile
FROM nvidia/cuda:12.5.1-cudnn-runtime-ubuntu20.04
CMD ["nvidia-smi"]
```
2. Build the …
> nvproxy: Implement missing CTRL_CMD_PERF_GET_CURRENT_PSTATE control cmd

- pkg/cpuid/cpuid_amd64.go
- test/syscalls/linux/proc.cc
Linux prints this field when cache information is available. This field is conditional (see arch/x86/kernel/cpu/proc.c:x86_cache_size()). It a different meaning and implementation on each vendor. For example, as of Linux 6.1.0 it returns LLC size on Intel and L2 size on AMD CPUs.
Even though usefullness of this field in its current implementation debatable, some relatively popular software such as PyPy (as of 7.3.11) relies on it and prints a warning if it is not available.
> procfs: add cache size x86 cpuinfo field

- runsc/container/container.go
When the container finds that the container already exists, checked by `LockForNew()`, it returns an error and starts the clean-up process. The clean-up process will clean up the metadata file of the container, which was created by others. What's worse, the clean-up process only deletes metadata files rather than all resources of the container, leaking resources including the socket, makes it impossible to create a new container with this ID anymore.
See #10724 for the bug description.
> runsc: Fix bug of container creation clean-up process

- g3doc/user_guide/debugging.md
Was reading the doc online and noticed it. Since this document was authored a handful of new options have been introduced, so I've attempted to edit the language to be more future-proof.
> docs: update out-of-date and mispelled lines in debugging.md

- pkg/abi/nvgpu/classes.go
- pkg/abi/nvgpu/ctrl.go
- pkg/sentry/devices/nvproxy/version.go
This PR adds support for the GF100_PROFILER allocation class and the NV2080_CTRL_CMD_TIMER_SET_GR_TICK_FREQ control command, both of which are needed for gVisor to work with the PyTorch profiler.
```py
import torch
from torch.profiler import profile, record_function, ProfilerActivity
ff1 = torch.nn.Linear(8192, 8192).to("cuda")
ff2 = torch.nn.Linear(8192, 8192).to("cuda")
ff3 = torch.nn.Linear(8192, 8192).to("cuda")
def do_work(x: torch.Tensor):
return ff3(ff2(ff1(x)))
x = torch.randn((8192, 8192)).to("cuda")
with profile(activities=[ProfilerActivity.CPU, ProfilerActivity.CUDA], record_shapes=True, profile_memory=True, with_stack=True) as prof:
for i in range(10):
do_work(x)
print(prof.key_averages(group_by_input_shape=True).table(sort_by="cpu_time_total", row_limit=10)) …
```
> nvproxy: Add support for PyTorch CUDA profiler

- pkg/sentry/fsimpl/gofer/socket.go
- pkg/sentry/fsimpl/testutil/kernel.go
- pkg/sentry/kernel/kernel.go
- pkg/sentry/socket/netlink/socket.go
- pkg/sentry/socket/unix/transport/connectioned.go
- pkg/sentry/socket/unix/transport/connectionless.go
- pkg/sentry/socket/unix/transport/host.go
- pkg/sentry/socket/unix/transport/unix.go
- pkg/sentry/socket/unix/unix.go
- runsc/boot/BUILD
- runsc/boot/loader.go
- runsc/config/config.go
- runsc/config/flags.go
As discussed in [gvisor issue #10897](https://github.com/google/gvisor/issues/10897), this change extends the -net-disconnect-ok flag to handle unsaveable Unix domain sockets. When enabled, any Unix socket backed by host FDs that cannot be saved will instead be closed before checkpointing, and will be saved in a closed state. This makes it possible to checkpoint containers even when they have connected to host-mounted Unix sockets.
Most of the changes in the diff involve passing the new setting to where host-backed domain sockets are created -- if there's a less invasive approach, please let me know.
> Extend -net-disconnect-ok to close unsaveable unix sockets on save

- tools/crosstool-arm-dirs.patch
This should fix the compile time error:
ERROR: Compiling absl/base/log_severity.cc failed: absolute path inclusion(s) found in rule '@@com_google_absl//absl/base:log_severity': the source file 'absl/base/log_severity.cc' includes the following non-builtin files with absolute paths (if these are builtin files, make sure these paths are in your toolchain):
'/usr/lib/gcc-cross/x86_64-linux-gnu/11/include/stddef.h'
'/usr/lib/gcc-cross/x86_64-linux-gnu/11/include/stdarg.h'
'/usr/lib/gcc-cross/x86_64-linux-gnu/11/include/stdint.h'
'/usr/lib/gcc-cross/x86_64-linux-gnu/11/include/limits.h'
'/usr/lib/gcc-cross/x86_64-linux-gnu/11/include/syslimits.h'
> crosstool: add /usr/lib/gcc-cross/ to the toolchain

- runsc/container/container.go
- runsc/specutils/nvidia.go
Was reading through code and noticed these two instances of outdated commentary.
> nvproxy: remove outdated commentary

- pkg/aio/BUILD
- pkg/aio/aio_test.go
- pkg/buffer/BUILD
- pkg/buffer/buffer_test.go
- pkg/buffer/view_test.go
- pkg/lisafs/BUILD
- pkg/lisafs/sock_test.go
- pkg/lisafs/testsuite/BUILD
- pkg/lisafs/testsuite/testsuite.go
- pkg/p9/p9test/BUILD
- pkg/p9/p9test/client_test.go
- pkg/tcpip/BUILD
- pkg/tcpip/link/fdbased/BUILD
- pkg/tcpip/link/fdbased/endpoint_test.go
- pkg/tcpip/network/internal/testutil/BUILD
- pkg/tcpip/network/internal/testutil/testutil.go
- pkg/tcpip/tcpip.go
- pkg/test/testutil/BUILD
- pkg/test/testutil/testutil.go
- test/benchmarks/tcp/BUILD
- test/benchmarks/tcp/tcp_proxy.go
- test/cmd/test_app/BUILD
- test/cmd/test_app/main.go
- test/packetimpact/testbench/BUILD
- test/packetimpact/testbench/testbench.go
- test/packetimpact/tests/BUILD
- test/packetimpact/tests/ipv4_fragment_reassembly_test.go
- test/packetimpact/tests/ipv6_fragment_reassembly_test.go
- tools/go_marshal/analysis/BUILD
- tools/go_marshal/analysis/analysis_unsafe.go
The helper function is deprecated. The package gvisor.dev/gvisor/pkg/rand depends on crypto/rand which performs worse thatn math/rand, the changes are fine since they are not at any gVisor's hot path.
The ultimate goal is to migrate math/rand to math/rand/v2.
> Remove references to math/rand package's Read function.

- WORKSPACE
- tools/go_types_memoize.patch
The go_types_memoize.patch was generated using the git diff command, with the 'go' field manually added to the path. It would be more appropriate to set the patch_strip value to 1 when applying such patches.
> Strip the extra path in go_types_memoize.patch

- g3doc/user_guide/tutorials/docker-in-gvisor.md
The tutorial doesn't work because `iptables-legacy` errors out when it attempts to use a raw netlink socket. The tests use `--net-raw` to verify docker inside gvisor works, and I verified it works as well.
> Update docker-in-gvisor.md to mention raw sockets

- pkg/sentry/fsimpl/proc/tasks_sys.go
Previously, /proc/sys/kernel/pid_max did not exist in sandboxes, making some processes which depend on it fail. This commit populates it with kernel.TasksLimit.
Resolves #11120
> Implement /proc/sys/kernel/pid_max with TasksLimit

- runsc/cmd/chroot.go
It is required to initialize cpuid.hostFeatureSet.
> runsc: add cpuinfo to the sandbox proc

- runsc/boot/restore.go
- runsc/config/config.go
- runsc/config/flags.go
This PR adds a new flag entitled `skip-restore-spec-validation-unsafe`, defaulting to false. If the flag is set, the container spec given when restoring a checkpoint will no longer be validated against the original container spec given when the checkpoint was taken. In practice, many spec differences are benign, and it can be useful to allow the container specs to vary somewhat between checkpoint and restore. See https://github.com/google/gvisor/issues/11307 .
> Add flag to disable container spec validation when restoring checkpoints

- runsc/cmd/boot.go
- runsc/cmd/checkpoint.go
- runsc/cmd/create.go
- runsc/cmd/debug.go
- runsc/cmd/delete.go
- runsc/cmd/gofer.go
- runsc/cmd/install.go
- runsc/cmd/kill.go
- runsc/cmd/list.go
- runsc/cmd/metric_export.go
- runsc/cmd/metricserver/metricservercmd/metricservercmd.go
- runsc/cmd/nvproxy/list_supported_drivers.go
- runsc/cmd/pause.go
- runsc/cmd/platforms.go
- runsc/cmd/restore.go
- runsc/cmd/resume.go
- runsc/cmd/run.go
- runsc/cmd/start.go
- runsc/cmd/state.go
- runsc/cmd/statefile.go
- runsc/cmd/syscalls.go
- runsc/cmd/trace/create.go
- runsc/cmd/trace/delete.go
- runsc/cmd/trace/list.go
- runsc/cmd/trace/metadata.go
- runsc/cmd/trace/procfs.go
- runsc/cmd/umount_unsafe.go
- runsc/cmd/usage.go
- runsc/cmd/wait.go
Originally, some of the commands' usage display didn't achieved to show newline, while some of them does, which are more user-friendly, and won't confuse the message if there're more which should be in the nextline.
Fix this issue by returning usage string with a newline.
Before the change some commands display their usage like the following, for example `runsc start`
```
vax-r@vaxr-ASUSPRO-D840MB-M840MB:~/gvisor$ runsc start
start <container id> - start a secure container.vax-r@vaxr-ASUSPRO-D840MB-M840MB:~/gvisor$
```
Or `runsc wait`
```
vax-r@vaxr-ASUSPRO-D840MB-M840MB:~/gvisor$ runsc wait
wait [flags] <container id>  -checkpoint
wait for the next checkpoint to complete
-pid int
select a PID in the container's PID namespace to wait on instead of the container's root process (default -1) …
```
> runsc: Fix newline for cmd usage display

- images/basic/integrationtest/Dockerfile
- pkg/lisafs/client_file.go
- pkg/lisafs/fd.go
- pkg/lisafs/handlers.go
- pkg/lisafs/message.go
- pkg/sentry/fsimpl/gofer/dentry_impl.go
- pkg/sentry/fsimpl/gofer/directfs_dentry.go
- pkg/sentry/kernel/auth/context.go
- runsc/cmd/gofer.go
- runsc/fsgofer/filter/config.go
- runsc/fsgofer/lisafs.go
- test/e2e/integration_runtime_test.go
Dear gvisor developers,
Thank you very much for maintaining / developing gvisor!
We had a use case (which I believe is a wide use case) that the sandboxes send requests over a unix domain socket on host, which is mapped to the container's file system and listened to by a server on the local host.
The sandboxed application is started with a prescribed uid. To authenticate the request, the server verifies the request's uid.
However, as the gofer process (which usually runs as root) executes [connect(unix_domain_socket) call](https://github.com/google/gvisor/blob/bd0cbf807169db29837d238209c02c816f3c8dbf/runsc/fsgofer/lisafs.go#L819) on behalf of the sandbox, the server always sees a uid 0. Hence the server cannot authenticate the UDS requests coming from the sandbox.
I propose to Add a new …
> Add a new RPC `ConnectWithCreds` to allow gofer to connect to a unix domain socket with application's credentials

- Makefile
This should fix the test failure for `ffmpeg_test` in `gpu-all-tests`. 
There is an additional failure in `cos-gpu-all-tests`. Briefly looking at the code, it seems like there is special logic mounting NVIDIA libraries https://github.com/google/gvisor/blob/c5c74f4c90ac8f9556a251117765cb951da369e7/pkg/test/dockerutil/gpu.go#L131
and probably `libcuvid.so` is not getting mounted properly (or isn't even installed). I don't know about how the COS instances are configured so I'd have to look deeper into this, potentially we could remove the test for now.
@EtiennePerot @ayushr2
> Add video and graphics capability for `gpu-all-tests` target

- runsc/config/flags.go
This flag's behavior was removed back in 29234bc44b51, so clarify for the user not to bother with it anymore.
> Clarify -cgroupfs

- pkg/abi/linux/netfilter.go
- pkg/abi/linux/netfilter_test.go
- pkg/sentry/socket/netfilter/BUILD
- pkg/sentry/socket/netfilter/extensions.go
- pkg/sentry/socket/netfilter/multiport_matcher.go
- pkg/sentry/socket/netfilter/multiport_matcher_v1.go
- pkg/sentry/socket/netfilter/netfilter.go
- pkg/sentry/socket/netstack/netstack.go
- test/iptables/filter_input.go
- test/iptables/filter_output.go
- test/iptables/iptables_test.go
This set of changes adds:
- support for `xt_multiport_{,v1}` matchers for matching for a range of ports and their inverse, i.e.,:
```
-m multiport [!] --[s|d]ports (PORT,...|PORT:PORT,...)
```
- support for `IP{,6}T_SO_GET_REVISION_MATCH` socket options, which allows `iptables` to query for the highest supported revision for a given matcher
> netfilter: Support multiport matching (-m multiport)

- pkg/ring0/lib_amd64.go
Currently ring0.PhysicalAddressBits will be set in ring0.Init() even if it has already been initialized elsewhere. For example, when compiling runsc with cgo enabled, function init() of the package kvm(machine_cgo.go) sets this variable. And this value would be updated by ring0.Init() when creating a new KVM context. If two values are inconsistent, the sandbox would panic during later memory region setting.
This patch fixes it by checking the PhysicalAddressBits in ring0.Init() and setting the value only if it is uninitialized.
> ring0: set PhysicalAddressBits only when uninitialized

- pkg/sentry/mm/mm_test.go
- pkg/sentry/mm/pma.go
- pkg/sentry/mm/vma.go
Hello gVisor community! This is Xuzhou (Joe) from Snowflake Inc. We are currently working on utilizing gVisor internally as our secured sandboxing mechanism. We have met in-person with gVisor team last October sharing our use case and experiences with the gVisor team. As part of the meeting, we (Snowflake team) committed to contribute our internal fixes/improvements back to the upstream.
As part of compatibility testing with our previous mechanism, we found some behavior discrepancies between gVisor-emulated kernel and native linux kernel when making mmap system calls. Thus wanted to raise a pull request and see if this makes sense.
Exactly the same workload creates ~100 kernel VMA entries with native linux kernel, while it creates ~70,000 VMA entries under gVisor.
```
def alloc(mb): …
```
> Adjust memfd offset allocation direction properly

- pkg/sentry/syscalls/linux/sys_mmap.go
- test/syscalls/linux/BUILD
- test/syscalls/linux/mount.cc
This is Xuzhou (Joe) from `Snowflake Inc`. We are currently working on utilizing gVisor internally as our secured sandboxing mechanism. We have met in-person with gVisor team last October sharing our use case and experiences with the gVisor team. As part of the meeting, we (Snowflake team) committed to contribute our internal fixes/improvements back to the upstream.
As part of compatibility testing with our previous mechanism, we found some behavior discrepancies between gVisor-emulated kernel and native linux kernel when making `mmap` system calls. Thus wanted to raise a pull request and see if this makes sense.
On native linux kernel, when calling `mmap` syscall with PROT_EXEC on a file, linux kernel checks if the volume/file system backing the file is executable (ie. Has `NOEXEC` flag …
> Fix EXEC permission of the volume mount when calling mmap with PROT_EXEC

- runsc/specutils/specutils.go
I see an error like
```
W0209 17:31:57.513990       1 util.go:64] FATAL ERROR: error setting up chroot: error converting mounts: permission denied
```
and have no idea, what operation exactly fails.
> [runsc] When mount files, add arguments to error message

- runsc/container/state_file.go
When `runsc` does not work, there are messages like
```
loading container: file does not exist
...
loading sandbox: file does not exist
```
The problem here is, there is no indication of file path, making it harder to debug.
I don't have access to environment where these errors appear, so I cannot repro. Better diagnostics would help.
There's a comment in code suggesting that error code is important, so we cannot modify error IIUC
https://github.com/google/gvisor/blob/9c490f813d37882f0374b7aebdad9961277623b8/runsc/container/state_file.go#L81
so my suggestion is to log the file name.
> [runsc] Print file name when cannot load state file

- images/gpu/cuda-tests/Dockerfile.aarch64
- test/gpu/cuda_test.go
Add image for ARM workloads for cuda-tests and mark tests that work on ARM.
Most tests don't work due to cross-compiling between sbma and aarch64. However, a few do. Add an image to support them.
> Update cuda-tests for ARM workloads

- test/syscalls/linux/mmap.cc
Currently, the NoSigBusOnPagesBeforeEOF and NoSigBusOnPageContainingEOF test cases are identical. This patch corrects the addr accessed in the former test to match the corresponding comment.
> test/syscalls: fix the duplicate test case

- pkg/sentry/kernel/task_run.go
When the sandboxed application is killed externally (for example, when it requests more memory than what cgroup allows), the whole sandbox should exit as well. We find this commit https://github.com/google/gvisor/commit/16dba7fa76771007a2969b44a93807e255d5964a#diff-06bbaf439d32bed64b39754ca405a6b8fe4227925bfa92c11428b6ddfc91b962 changed this behavior. This commit led to the fact that when the application is killed, the sandbox is still hanging around.
This PR fixes it.
The hang can be reproduced in any release version including the commit above. Here we use `release-20250319.0` as an example.
```go
package main
import (
"fmt"
"time"
)
func main() {
fmt.Println("Application started")
var loop = 0
for {
time.Sleep(2 * time.Second)
loop++
fmt.Printf("Application is running %d\n", loop)
} …
```
> Sentry systrap: exit the entire process when one stubprocess is dead

- pkg/sentry/socket/hostinet/socket_unsafe.go
We are currently using gVisor with `--network=host` in our infrastructure environment. In addition, the environment is not configured with any network interfaces (There is even no loopback interface). This has triggered an edge case when running Java workloads which calls `ioctl` to list current available network interfaces on a socket.
```
import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.LogManager;
public class Reproduce {
private static final Logger LOGGER = LogManager.getLogger();
public static String handle(final Session session) {
return "Success";
}
}
``` 
The `LogManager.getLogger()` here will trigger a network interface lookup from Java's native code, stacktrace:
```
org.apache.logging.log4j.LogManager.getLogger
- …
```
> Fix host socket ioctl when len == 0 and ifc_buf != 0

- pkg/tcpip/network/ipv4/icmp.go
- pkg/tcpip/network/ipv4/ipv4.go
- pkg/tcpip/stack/addressable_endpoint_state.go
- pkg/tcpip/stack/registration.go
The gVisor network stack is extensively employed in user-space tunneling software, often operating in promiscuous mode. In this configuration, the stack directly responds to all ICMPv4 Echo Request packets, irrespective of whether a [transport defaultHandler](https://github.com/google/gvisor/blob/6b2bcc44e061f48c6dd9cc6048ae17d389a2f22d/pkg/tcpip/stack/stack.go#L49) has already processed them. This behavior is often unintended in certain scenarios, as evidenced by issues such as:
- https://github.com/google/gvisor/issues/8657
- https://github.com/containers/gvisor-tap-vsock/issues/428
- https://github.com/xjasonlyu/tun2socks/issues/361
- etc.
In these scenarios, users may prefer to utilize [SetTransportProtocolHandler](https://github.com/google/gvisor/blob/6b2bcc44e061f48c6dd9cc6048ae17d38 …
> netstack: allow defaultHandler respond ICMPv4Echo in promiscuous mode

- pkg/sentry/arch/fpu/fpu_amd64.s
MPX has been deprected in Linux Kernel and it is completely disabled in VM-s (kvm).
Fixes #11687
> x86/fpu: Exclude MPX states from the initial fpu

- .github/workflows/build.yml
The workflow is configured to:
* Run on every push to any branch.
* Build the runsc binary.
* Upload the built runsc artifact, making it available for consumption.
This ensures that runsc is continuously built and provides readily accessible build artifacts for testing purposes.
> github: Add CI workflow for building runsc

- runsc/cmd/exec.go
```
$ ./runsc -root runsc-test/var exec k20663363928921 /toybox
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1085ed1]
goroutine 1 [running]:
gvisor.dev/gvisor/runsc/cmd.capabilities(0xc00016b9c8?, {0x0?, 0xc0000b8910?, 0xc00016baf0?}, 0x0)
runsc/cmd/exec.go:452 +0x31
gvisor.dev/gvisor/runsc/cmd.(*Exec).argsFromCLI(0xc0000d9ba0, 0xc000172870, {0xc0000b61d0, 0x1, 0x1}, 0x0)
runsc/cmd/exec.go:348 +0x2ce
gvisor.dev/gvisor/runsc/cmd.(*Exec).parseArgs(0x0?, 0x7ffe493e5e6d?, 0xe?, 0xe7?)
runsc/cmd/exec.go:324 +0x78
gvisor.dev/gvisor/runsc/cmd.(*Exec).Execute(0xc0000d9ba0, {0xc0000b61c0?, 0x114a5c0?}, 0xc00017e620, {0xc0000b4400?, 0x5b6689?, 0x0?})
runsc/cmd/exec.go:129 +0x1d9 …
```
> Fix nil deref in exec command

- Makefile
- runsc/config/config_test.go
Updates https://github.com/google/gvisor/issues/10045
Before:
```
--- FAIL: TestBundleValidate (0.00s)
--- FAIL: TestBundleValidate/invalid_value (0.00s)
config_test.go:713: Validate failed: mismatch error: got: "parse error" want: "parsing \"invalid\": invalid syntax"
FAIL
```
Different flags is used in OSS and internal versions, check comment below.
> Fix TestBundleValidate

- runsc/cgroup/cgroup_v2.go
Just noticed constant is there but not used.
> Use controllersFile and similar constants

- runsc/config/flags.go
Might be convenient to learn how a program works without digging into program sources.
> Add default --root flag value to help

- SECURITY.md
The https links redirects to google group page that does not show email, and does not allow posting to the group.
> Make instruction how to contact security more clear

- pkg/tcpip/transport/tcp/endpoint.go
When a handshake times out, the endpoint may remain stuck in the lEP's pendingEndpoints queue.
Related to #11536
It has passed the test-case for `//pkg/tcpip:tcpip_test`
> netstack: remove timed-out endpoints from pendingEndpoints queue.

- tools/checklocks/README.md
This annotation only works as an inline comment.
> checklocks: correctly document field-level `checklocksignore`

- pkg/sentry/vfs/vfs.go
See #11910 for details — this potentially fixes a divergence between gVisor and runc behavior where having the `cwd` of the OCI container spec set to a symlink to a folder causes gVisor to exit with this error:
```
running container: starting container: starting root container: starting sandbox: failed to create process working directory "/cwd-folder-name-here": not a directory
```
I'm not sure if this is the best way to fix the issue, just sending in the PR in case it helps!
> Follow symlinks in MkdirAllAt

- pkg/sentry/fsimpl/host/tty.go
Fix a nil pointer dereference panic when attempting to call `SetForegroundProcessGroupID` on a TTY that has lost its session leader.
Fixes: #11943
> sentry: fix panic in TTY `TIOCSPGRP`

- pkg/tcpip/header/virtionet.go
This change updates the encoding of several fields in `VirtioNetHeader.Encode` from big endian to little endian.
Although this code path is not currently exercised in production (the current usage always passes an all-zero structure, where big endian and little endian encoding yield the same result), I encountered this issue while using this method in my own project, where the values are non-zero. According to the [Virtual I/O Device Specification](https://docs.oasis-open.org/virtio/virtio/v1.1/csprd01/virtio-v1.1-csprd01.html), these fields (`HdrLen`, `GSOSize`, `CSumStart`, `CSumOffset`)should be encoded in little endian format. Using big endian encoding here is incorrect and leads to failures when interoperating with compliant Virtio implementations(for example tun devices).
This PR …
> fix: use LittleEndian for VirtioNetHeader field encoding

- g3doc/user_guide/networking.md
Fix the markdown syntax for the Production guide reference in networking.md and add the proper link definition at the end of the file.
> docs: fix markdown link to Production guide in networking user guide

- runsc/cmd/BUILD
- runsc/cmd/exec.go
- runsc/cmd/pidfile.go
- runsc/cmd/pidfile_test.go
Fixes #11851. Alternative to #11861.
> Write pidfile atomically

- tools/show_paths.bzl
This is needed for releases. For some reason, prior to this CL `make debian` would succeed, despite the obvious failure in the logs, and the script using show_paths.bzl doing `set -euo`.
> Fix //debian:debian build target.

- runsc/specutils/specutils.go
Currently in OCI config it is possible to add any extra json data, which will be ignored by runsc.
I found it is a bit confusing when was learning OCI implementation of gvisor (adding wrong/non existent  fields does not produce any error or warning), therefore decided to add flag `allow-unknown-fields`, which is `true` by default (does not modify current behavior).
In case of being `false`, gvisor produces error like this:
```
reading spec: error unmarshaling spec from file "config.json": json: unknown field "oooooo"
```
> Add option to enable/disable unknown fields in OCI config

- pkg/tcpip/link/fdbased/processors.go
This hook is supposed to "quiesce" data structures before the stateify system serializes them to a memory checkpoint. `processorManager` has a packet-processing goroutine which needs to be stopped before we can serialize the object.
A more detailed investigation is in https://github.com/google/gvisor/issues/12072.
> Implement the `beforeSave` hook for `processorManager`

- runsc/specutils/specutils.go
Someone seem to confuse a pair of words `errLooseDecode` and `errStrictDecode`. I think this person feels guilty and regrets about that.
> typo fix for errLooseDecode

- runsc/cmd/boot.go
- runsc/cmd/gofer.go
- runsc/container/container.go
- runsc/sandbox/sandbox.go
Fix #9918.
Currently, the rootless mode(runsc is called by no-root user) is not working well with the filesystem if we uses a non-root user in runsc container. This is because the runsc is mapping the host non-root user to root-user in container.
In some cases we need to map the host non-root user to runsc container non-root user (with the same uid).
After this patch, the following filesystem operations works well.
test@test-virtual-machine:~/test$ ./runsc   -ignore-cgroups --network host run abc
id
uid=1000(test) gid=1000(test) groups=1000(test)
touch /tmp/runsctest
echo aaa > /tmp/runsctest
ls -lh /tmp/runsctest
-rw-r--r-- 1 test test 4 Jun 29 18:46 /tmp/runsctest
exit
test@test-virtual-machine:~/test$ ls -lh /tmp/runsctest
-rw-r--r-- 1 test test 4  6月 29 18:46 /tmp/runsctest …
> runsc: Allow map host user to non-root user in rootless mode
